// Code generated by abstraction-idl from abstraction-asks/asks.thrift. DO NOT EDIT.

#![allow(dead_code)]

use std::collections::BTreeMap;

// An opaque payload is bytes the contract forbids us to reinterpret, and String
// would refuse to hold one that is not UTF-8 rather than carry it back out.
pub type Raw = Vec<u8>;

const HEX: &[u8; 16] = b"0123456789abcdef";

fn esc_byte(out: &mut Vec<u8>, c: u8) {
    match c {
        b'"' => out.extend_from_slice(b"\\\""),
        b'\\' => out.extend_from_slice(b"\\\\"),
        0x08 => out.extend_from_slice(b"\\b"),
        0x0c => out.extend_from_slice(b"\\f"),
        b'\n' => out.extend_from_slice(b"\\n"),
        b'\r' => out.extend_from_slice(b"\\r"),
        b'\t' => out.extend_from_slice(b"\\t"),
        _ if c < 0x20 => {
            out.extend_from_slice(b"\\u00");
            out.push(HEX[(c >> 4) as usize]);
            out.push(HEX[(c & 0x0F) as usize]);
        }
        _ => out.push(c),
    }
}

pub fn num(out: &mut Vec<u8>, n: i64) {
    out.extend_from_slice(n.to_string().as_bytes());
}

pub fn pad(out: &mut Vec<u8>, depth: i32) {
    for _ in 0..depth * 2 {
        out.push(b' ');
    }
}

pub fn strs(out: &mut Vec<u8>, v: &[String], depth: i32) {
    if v.is_empty() {
        out.extend_from_slice(b"[]");
        return;
    }
    out.extend_from_slice(b"[\n");
    for (i, s) in v.iter().enumerate() {
        pad(out, depth + 1);
        esc(out, s);
        if i + 1 < v.len() {
            out.push(b',');
        }
        out.push(b'\n');
    }
    pad(out, depth);
    out.push(b']');
}

fn ws(c: u8) -> bool {
    c == b' ' || c == b'\t' || c == b'\n' || c == b'\r'
}

pub fn raw(out: &mut Vec<u8>, b: &[u8], depth: i32) {
    let mut depth = depth;
    let mut i = 0;
    while i < b.len() {
        let c = b[i];
        if ws(c) {
            i += 1;
        } else if c == b'"' {
            let mut j = i + 1;
            while j < b.len() {
                if b[j] == b'\\' {
                    j += 2;
                    continue;
                }
                if b[j] == b'"' {
                    j += 1;
                    break;
                }
                j += 1;
            }
            out.extend_from_slice(&b[i..j]);
            i = j;
        } else if c == b'{' || c == b'[' {
            out.push(c);
            i += 1;
            let mut j = i;
            while j < b.len() && ws(b[j]) {
                j += 1;
            }
            if j < b.len() && (b[j] == b'}' || b[j] == b']') {
                out.push(b[j]);
                i = j + 1;
            } else {
                depth += 1;
                out.push(b'\n');
                pad(out, depth);
            }
        } else if c == b'}' || c == b']' {
            depth -= 1;
            out.push(b'\n');
            pad(out, depth);
            out.push(c);
            i += 1;
        } else if c == b',' {
            out.extend_from_slice(b",\n");
            pad(out, depth);
            i += 1;
        } else if c == b':' {
            out.extend_from_slice(b": ");
            i += 1;
        } else {
            out.push(c);
            i += 1;
        }
    }
}

// A BTreeMap<String, _> walks its keys in String's Ord, which compares the
// UTF-8 bytes — the order the definition declares. Nothing sorts here.
pub fn rawmap(out: &mut Vec<u8>, m: &BTreeMap<String, Raw>, depth: i32) {
    if m.is_empty() {
        out.extend_from_slice(b"{}");
        return;
    }
    out.extend_from_slice(b"{\n");
    for (i, (k, v)) in m.iter().enumerate() {
        pad(out, depth + 1);
        esc(out, k);
        out.extend_from_slice(b": ");
        raw(out, v, depth + 1);
        if i + 1 < m.len() {
            out.push(b',');
        }
        out.push(b'\n');
    }
    pad(out, depth);
    out.push(b'}');
}

pub fn esc(out: &mut Vec<u8>, s: &str) {
    out.push(b'"');
    for c in s.as_bytes() {
        esc_byte(out, *c);
    }
    out.push(b'"');
}

pub fn strmap(out: &mut Vec<u8>, m: &BTreeMap<String, String>, depth: i32) {
    if m.is_empty() {
        out.extend_from_slice(b"{}");
        return;
    }
    out.extend_from_slice(b"{\n");
    for (i, (k, v)) in m.iter().enumerate() {
        pad(out, depth + 1);
        esc(out, k);
        out.extend_from_slice(b": ");
        esc(out, v);
        if i + 1 < m.len() {
            out.push(b',');
        }
        out.push(b'\n');
    }
    pad(out, depth);
    out.push(b'}');
}

pub fn enc_list<T>(out: &mut Vec<u8>, v: &[T], depth: i32, enc: fn(&mut Vec<u8>, &T, i32)) {
    if v.is_empty() {
        out.extend_from_slice(b"[]");
        return;
    }
    out.extend_from_slice(b"[\n");
    for (i, x) in v.iter().enumerate() {
        pad(out, depth + 1);
        enc(out, x, depth + 1);
        if i + 1 < v.len() {
            out.push(b',');
        }
        out.push(b'\n');
    }
    pad(out, depth);
    out.push(b']');
}

pub const OBSERVATIONOUTCOME_NAMES: [&str; 8] = ["pending", "answered", "unknown", "gone", "invalid", "conflict", "forbidden", "unavailable"];
pub const OBSERVATIONOUTCOME_UNKNOWN: &str = "refuse";

pub const OPERATORPAGEOUTCOME_NAMES: [&str; 5] = ["page", "gap", "invalid", "forbidden", "unavailable"];
pub const OPERATORPAGEOUTCOME_UNKNOWN: &str = "refuse";

pub const OPERATORDECISIONOUTCOME_NAMES: [&str; 6] = ["answered", "conflict", "unknown", "invalid", "forbidden", "unavailable"];
pub const OPERATORDECISIONOUTCOME_UNKNOWN: &str = "refuse";

pub const OPERATORRETIREMENTOUTCOME_NAMES: [&str; 5] = ["retired", "unknown", "invalid", "forbidden", "unavailable"];
pub const OPERATORRETIREMENTOUTCOME_UNKNOWN: &str = "refuse";

pub const OPERATIONS: [&str; 5] = ["ask", "pending", "answered", "answer", "forget"];

pub const REFUSAL_CODES: [&str; 11] = ["internal", "invalid_request", "caller_refused", "unknown_operation", "not_administrator", "withdrawn", "unknown_question", "unknown_option", "bad_slot", "nothing_pending", "no_record"];

#[derive(Default)]
pub struct Question {
    pub asker: String,
    pub key: String,
    pub slots: BTreeMap<String, String>,
}

#[derive(Default)]
pub struct Request {
    pub op: String,
    pub ask: Option<Question>,
    pub wait: bool,
    pub id: String,
    pub option: String,
    pub admin: String,
}

#[derive(Default)]
pub struct Answer {
    pub id: String,
    pub pending: bool,
    pub option: String,
    pub yes: bool,
    pub kept: bool,
}

#[derive(Default)]
pub struct RecordMetadata {
    pub id: String,
    pub asker: String,
    pub key: String,
    pub about: String,
    pub text: String,
    pub options: Vec<String>,
    pub asked: String,
    pub option: String,
    pub answered: String,
    pub kept: bool,
    pub yes: bool,
}

#[derive(Default)]
pub struct ResponseMetadata {
    pub code: String,
    pub error: String,
    pub answer: Option<Answer>,
    pub records: Vec<RecordMetadata>,
}

#[derive(Default)]
pub struct ApplicationQuestion {
    pub request_key: String,
    pub key: String,
    pub slots: BTreeMap<String, String>,
}

#[derive(Default)]
pub struct QuestionObservation {
    pub outcome: String,
    pub answer: Option<Answer>,
}

#[derive(Default)]
pub struct OperatorPage {
    pub outcome: String,
    pub records: Vec<RecordMetadata>,
    pub next: String,
    pub complete: bool,
}

#[derive(Default)]
pub struct OperatorDecision {
    pub outcome: String,
    pub record: Option<RecordMetadata>,
}

#[derive(Default)]
pub struct OperatorRetirement {
    pub outcome: String,
    pub record: Option<RecordMetadata>,
}

#[derive(Default)]
pub struct OAQuestionApplicationAskArguments {
    pub question: ApplicationQuestion,
}

#[derive(Default)]
pub struct OAQuestionApplicationObserveArguments {
    pub request_key: String,
    pub wait_ms: i64,
}

#[derive(Default)]
pub struct OAQuestionOperatorListQuestionsArguments {
    pub cursor: String,
    pub limit: i64,
}

#[derive(Default)]
pub struct OAQuestionOperatorAnswerQuestionArguments {
    pub id: String,
    pub option: String,
}

#[derive(Default)]
pub struct OAQuestionOperatorRetireQuestionArguments {
    pub id: String,
}

#[derive(Default)]
pub struct OAServiceFrame {
    pub version: i32,
    pub service: String,
    pub method: String,
    pub arguments: Raw,
}

#[derive(Default)]
pub struct OAServiceReply {
    pub version: i32,
    pub service: String,
    pub method: String,
    pub ok: bool,
    pub payload: Raw,
}

#[derive(Default)]
pub struct OAServiceError {
    pub code: String,
    pub message: String,
}

#[derive(Default)]
pub struct OAQuestionApplicationAskResult {
    pub value: QuestionObservation,
}

#[derive(Default)]
pub struct OAQuestionApplicationObserveResult {
    pub value: QuestionObservation,
}

#[derive(Default)]
pub struct OAQuestionOperatorListQuestionsResult {
    pub value: OperatorPage,
}

#[derive(Default)]
pub struct OAQuestionOperatorAnswerQuestionResult {
    pub value: OperatorDecision,
}

#[derive(Default)]
pub struct OAQuestionOperatorRetireQuestionResult {
    pub value: OperatorRetirement,
}

pub fn enc_question(out: &mut Vec<u8>, v: &Question, depth: i32) {
    out.push(b'{');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "asker");
    out.extend_from_slice(b": ");
    esc(out, &v.asker);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "key");
    out.extend_from_slice(b": ");
    esc(out, &v.key);
    if !v.slots.is_empty() {
        out.push(b',');
        out.push(b'\n');
        pad(out, depth + 1);
        esc(out, "slots");
        out.extend_from_slice(b": ");
        strmap(out, &v.slots, depth + 1);
    }
    out.push(b'\n');
    pad(out, depth);
    out.push(b'}');
}

pub fn enc_request(out: &mut Vec<u8>, v: &Request, depth: i32) {
    out.push(b'{');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "op");
    out.extend_from_slice(b": ");
    esc(out, &v.op);
    if v.ask.is_some() {
        out.push(b',');
        out.push(b'\n');
        pad(out, depth + 1);
        esc(out, "ask");
        out.extend_from_slice(b": ");
        enc_question(out, v.ask.as_ref().unwrap(), depth + 1);
    }
    if v.wait {
        out.push(b',');
        out.push(b'\n');
        pad(out, depth + 1);
        esc(out, "wait");
        out.extend_from_slice(b": ");
        out.extend_from_slice(if v.wait { b"true" } else { b"false" });
    }
    if !v.id.is_empty() {
        out.push(b',');
        out.push(b'\n');
        pad(out, depth + 1);
        esc(out, "id");
        out.extend_from_slice(b": ");
        esc(out, &v.id);
    }
    if !v.option.is_empty() {
        out.push(b',');
        out.push(b'\n');
        pad(out, depth + 1);
        esc(out, "option");
        out.extend_from_slice(b": ");
        esc(out, &v.option);
    }
    if !v.admin.is_empty() {
        out.push(b',');
        out.push(b'\n');
        pad(out, depth + 1);
        esc(out, "admin");
        out.extend_from_slice(b": ");
        esc(out, &v.admin);
    }
    out.push(b'\n');
    pad(out, depth);
    out.push(b'}');
}

pub fn enc_answer(out: &mut Vec<u8>, v: &Answer, depth: i32) {
    out.push(b'{');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "id");
    out.extend_from_slice(b": ");
    esc(out, &v.id);
    if v.pending {
        out.push(b',');
        out.push(b'\n');
        pad(out, depth + 1);
        esc(out, "pending");
        out.extend_from_slice(b": ");
        out.extend_from_slice(if v.pending { b"true" } else { b"false" });
    }
    if !v.option.is_empty() {
        out.push(b',');
        out.push(b'\n');
        pad(out, depth + 1);
        esc(out, "option");
        out.extend_from_slice(b": ");
        esc(out, &v.option);
    }
    if v.yes {
        out.push(b',');
        out.push(b'\n');
        pad(out, depth + 1);
        esc(out, "yes");
        out.extend_from_slice(b": ");
        out.extend_from_slice(if v.yes { b"true" } else { b"false" });
    }
    if v.kept {
        out.push(b',');
        out.push(b'\n');
        pad(out, depth + 1);
        esc(out, "kept");
        out.extend_from_slice(b": ");
        out.extend_from_slice(if v.kept { b"true" } else { b"false" });
    }
    out.push(b'\n');
    pad(out, depth);
    out.push(b'}');
}

pub fn enc_recordmetadata(out: &mut Vec<u8>, v: &RecordMetadata, depth: i32) {
    out.push(b'{');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "id");
    out.extend_from_slice(b": ");
    esc(out, &v.id);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "asker");
    out.extend_from_slice(b": ");
    esc(out, &v.asker);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "key");
    out.extend_from_slice(b": ");
    esc(out, &v.key);
    if !v.about.is_empty() {
        out.push(b',');
        out.push(b'\n');
        pad(out, depth + 1);
        esc(out, "about");
        out.extend_from_slice(b": ");
        esc(out, &v.about);
    }
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "text");
    out.extend_from_slice(b": ");
    esc(out, &v.text);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "options");
    out.extend_from_slice(b": ");
    strs(out, &v.options, depth + 1);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "asked");
    out.extend_from_slice(b": ");
    esc(out, &v.asked);
    if !v.option.is_empty() {
        out.push(b',');
        out.push(b'\n');
        pad(out, depth + 1);
        esc(out, "option");
        out.extend_from_slice(b": ");
        esc(out, &v.option);
    }
    if !v.answered.is_empty() {
        out.push(b',');
        out.push(b'\n');
        pad(out, depth + 1);
        esc(out, "answered");
        out.extend_from_slice(b": ");
        esc(out, &v.answered);
    }
    if v.kept {
        out.push(b',');
        out.push(b'\n');
        pad(out, depth + 1);
        esc(out, "kept");
        out.extend_from_slice(b": ");
        out.extend_from_slice(if v.kept { b"true" } else { b"false" });
    }
    if v.yes {
        out.push(b',');
        out.push(b'\n');
        pad(out, depth + 1);
        esc(out, "yes");
        out.extend_from_slice(b": ");
        out.extend_from_slice(if v.yes { b"true" } else { b"false" });
    }
    out.push(b'\n');
    pad(out, depth);
    out.push(b'}');
}

pub fn enc_responsemetadata(out: &mut Vec<u8>, v: &ResponseMetadata, depth: i32) {
    out.push(b'{');
    let mut first = true;
    if !v.code.is_empty() {
        first = false;
        out.push(b'\n');
        pad(out, depth + 1);
        esc(out, "code");
        out.extend_from_slice(b": ");
        esc(out, &v.code);
    }
    if !v.error.is_empty() {
        if !first {
            out.push(b',');
        }
        first = false;
        out.push(b'\n');
        pad(out, depth + 1);
        esc(out, "error");
        out.extend_from_slice(b": ");
        esc(out, &v.error);
    }
    if v.answer.is_some() {
        if !first {
            out.push(b',');
        }
        first = false;
        out.push(b'\n');
        pad(out, depth + 1);
        esc(out, "answer");
        out.extend_from_slice(b": ");
        enc_answer(out, v.answer.as_ref().unwrap(), depth + 1);
    }
    if !v.records.is_empty() {
        if !first {
            out.push(b',');
        }
        first = false;
        out.push(b'\n');
        pad(out, depth + 1);
        esc(out, "records");
        out.extend_from_slice(b": ");
        enc_list(out, &v.records, depth + 1, enc_recordmetadata);
    }
    if !first {
        out.push(b'\n');
        pad(out, depth);
    }
    out.push(b'}');
}

pub fn enc_applicationquestion(out: &mut Vec<u8>, v: &ApplicationQuestion, depth: i32) {
    out.push(b'{');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "request_key");
    out.extend_from_slice(b": ");
    esc(out, &v.request_key);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "key");
    out.extend_from_slice(b": ");
    esc(out, &v.key);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "slots");
    out.extend_from_slice(b": ");
    strmap(out, &v.slots, depth + 1);
    out.push(b'\n');
    pad(out, depth);
    out.push(b'}');
}

pub fn enc_questionobservation(out: &mut Vec<u8>, v: &QuestionObservation, depth: i32) {
    if v.outcome != "pending" && v.outcome != "answered" && v.outcome != "unknown" && v.outcome != "gone" && v.outcome != "invalid" && v.outcome != "conflict" && v.outcome != "forbidden" && v.outcome != "unavailable" { std::panic::panic_any(Refusal{word:"bad_enum",offset:0}); }
    out.push(b'{');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "outcome");
    out.extend_from_slice(b": ");
    esc(out, &v.outcome);
    if v.answer.is_some() {
        out.push(b',');
        out.push(b'\n');
        pad(out, depth + 1);
        esc(out, "answer");
        out.extend_from_slice(b": ");
        enc_answer(out, v.answer.as_ref().unwrap(), depth + 1);
    }
    out.push(b'\n');
    pad(out, depth);
    out.push(b'}');
}

pub fn enc_operatorpage(out: &mut Vec<u8>, v: &OperatorPage, depth: i32) {
    if v.outcome != "page" && v.outcome != "gap" && v.outcome != "invalid" && v.outcome != "forbidden" && v.outcome != "unavailable" { std::panic::panic_any(Refusal{word:"bad_enum",offset:0}); }
    out.push(b'{');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "outcome");
    out.extend_from_slice(b": ");
    esc(out, &v.outcome);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "records");
    out.extend_from_slice(b": ");
    enc_list(out, &v.records, depth + 1, enc_recordmetadata);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "next");
    out.extend_from_slice(b": ");
    esc(out, &v.next);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "complete");
    out.extend_from_slice(b": ");
    out.extend_from_slice(if v.complete { b"true" } else { b"false" });
    out.push(b'\n');
    pad(out, depth);
    out.push(b'}');
}

pub fn enc_operatordecision(out: &mut Vec<u8>, v: &OperatorDecision, depth: i32) {
    if v.outcome != "answered" && v.outcome != "conflict" && v.outcome != "unknown" && v.outcome != "invalid" && v.outcome != "forbidden" && v.outcome != "unavailable" { std::panic::panic_any(Refusal{word:"bad_enum",offset:0}); }
    out.push(b'{');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "outcome");
    out.extend_from_slice(b": ");
    esc(out, &v.outcome);
    if v.record.is_some() {
        out.push(b',');
        out.push(b'\n');
        pad(out, depth + 1);
        esc(out, "record");
        out.extend_from_slice(b": ");
        enc_recordmetadata(out, v.record.as_ref().unwrap(), depth + 1);
    }
    out.push(b'\n');
    pad(out, depth);
    out.push(b'}');
}

pub fn enc_operatorretirement(out: &mut Vec<u8>, v: &OperatorRetirement, depth: i32) {
    if v.outcome != "retired" && v.outcome != "unknown" && v.outcome != "invalid" && v.outcome != "forbidden" && v.outcome != "unavailable" { std::panic::panic_any(Refusal{word:"bad_enum",offset:0}); }
    out.push(b'{');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "outcome");
    out.extend_from_slice(b": ");
    esc(out, &v.outcome);
    if v.record.is_some() {
        out.push(b',');
        out.push(b'\n');
        pad(out, depth + 1);
        esc(out, "record");
        out.extend_from_slice(b": ");
        enc_recordmetadata(out, v.record.as_ref().unwrap(), depth + 1);
    }
    out.push(b'\n');
    pad(out, depth);
    out.push(b'}');
}

pub fn enc_oaquestionapplicationaskarguments(out: &mut Vec<u8>, v: &OAQuestionApplicationAskArguments, depth: i32) {
    out.push(b'{');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "question");
    out.extend_from_slice(b": ");
    enc_applicationquestion(out, &v.question, depth + 1);
    out.push(b'\n');
    pad(out, depth);
    out.push(b'}');
}

pub fn enc_oaquestionapplicationobservearguments(out: &mut Vec<u8>, v: &OAQuestionApplicationObserveArguments, depth: i32) {
    out.push(b'{');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "request_key");
    out.extend_from_slice(b": ");
    esc(out, &v.request_key);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "wait_ms");
    out.extend_from_slice(b": ");
    num(out, v.wait_ms);
    out.push(b'\n');
    pad(out, depth);
    out.push(b'}');
}

pub fn enc_oaquestionoperatorlistquestionsarguments(out: &mut Vec<u8>, v: &OAQuestionOperatorListQuestionsArguments, depth: i32) {
    out.push(b'{');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "cursor");
    out.extend_from_slice(b": ");
    esc(out, &v.cursor);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "limit");
    out.extend_from_slice(b": ");
    num(out, v.limit);
    out.push(b'\n');
    pad(out, depth);
    out.push(b'}');
}

pub fn enc_oaquestionoperatoranswerquestionarguments(out: &mut Vec<u8>, v: &OAQuestionOperatorAnswerQuestionArguments, depth: i32) {
    out.push(b'{');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "id");
    out.extend_from_slice(b": ");
    esc(out, &v.id);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "option");
    out.extend_from_slice(b": ");
    esc(out, &v.option);
    out.push(b'\n');
    pad(out, depth);
    out.push(b'}');
}

pub fn enc_oaquestionoperatorretirequestionarguments(out: &mut Vec<u8>, v: &OAQuestionOperatorRetireQuestionArguments, depth: i32) {
    out.push(b'{');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "id");
    out.extend_from_slice(b": ");
    esc(out, &v.id);
    out.push(b'\n');
    pad(out, depth);
    out.push(b'}');
}

pub fn enc_oaserviceframe(out: &mut Vec<u8>, v: &OAServiceFrame, depth: i32) {
    out.push(b'{');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "version");
    out.extend_from_slice(b": ");
    num(out, v.version as i64);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "service");
    out.extend_from_slice(b": ");
    esc(out, &v.service);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "method");
    out.extend_from_slice(b": ");
    esc(out, &v.method);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "arguments");
    out.extend_from_slice(b": ");
    out.extend_from_slice(&v.arguments);
    out.push(b'\n');
    pad(out, depth);
    out.push(b'}');
}

pub fn enc_oaservicereply(out: &mut Vec<u8>, v: &OAServiceReply, depth: i32) {
    out.push(b'{');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "version");
    out.extend_from_slice(b": ");
    num(out, v.version as i64);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "service");
    out.extend_from_slice(b": ");
    esc(out, &v.service);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "method");
    out.extend_from_slice(b": ");
    esc(out, &v.method);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "ok");
    out.extend_from_slice(b": ");
    out.extend_from_slice(if v.ok { b"true" } else { b"false" });
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "payload");
    out.extend_from_slice(b": ");
    out.extend_from_slice(&v.payload);
    out.push(b'\n');
    pad(out, depth);
    out.push(b'}');
}

pub fn enc_oaserviceerror(out: &mut Vec<u8>, v: &OAServiceError, depth: i32) {
    out.push(b'{');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "code");
    out.extend_from_slice(b": ");
    esc(out, &v.code);
    out.push(b',');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "message");
    out.extend_from_slice(b": ");
    esc(out, &v.message);
    out.push(b'\n');
    pad(out, depth);
    out.push(b'}');
}

pub fn enc_oaquestionapplicationaskresult(out: &mut Vec<u8>, v: &OAQuestionApplicationAskResult, depth: i32) {
    out.push(b'{');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "value");
    out.extend_from_slice(b": ");
    enc_questionobservation(out, &v.value, depth + 1);
    out.push(b'\n');
    pad(out, depth);
    out.push(b'}');
}

pub fn enc_oaquestionapplicationobserveresult(out: &mut Vec<u8>, v: &OAQuestionApplicationObserveResult, depth: i32) {
    out.push(b'{');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "value");
    out.extend_from_slice(b": ");
    enc_questionobservation(out, &v.value, depth + 1);
    out.push(b'\n');
    pad(out, depth);
    out.push(b'}');
}

pub fn enc_oaquestionoperatorlistquestionsresult(out: &mut Vec<u8>, v: &OAQuestionOperatorListQuestionsResult, depth: i32) {
    out.push(b'{');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "value");
    out.extend_from_slice(b": ");
    enc_operatorpage(out, &v.value, depth + 1);
    out.push(b'\n');
    pad(out, depth);
    out.push(b'}');
}

pub fn enc_oaquestionoperatoranswerquestionresult(out: &mut Vec<u8>, v: &OAQuestionOperatorAnswerQuestionResult, depth: i32) {
    out.push(b'{');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "value");
    out.extend_from_slice(b": ");
    enc_operatordecision(out, &v.value, depth + 1);
    out.push(b'\n');
    pad(out, depth);
    out.push(b'}');
}

pub fn enc_oaquestionoperatorretirequestionresult(out: &mut Vec<u8>, v: &OAQuestionOperatorRetireQuestionResult, depth: i32) {
    out.push(b'{');
    out.push(b'\n');
    pad(out, depth + 1);
    esc(out, "value");
    out.extend_from_slice(b": ");
    enc_operatorretirement(out, &v.value, depth + 1);
    out.push(b'\n');
    pad(out, depth);
    out.push(b'}');
}

pub fn encode(v: &Request) -> Vec<u8> {
    let mut out = Vec::new();
    enc_request(&mut out, v, 0);
    out.push(b'\n');
    out
}

const DEPTH_LIMIT: i32 = 64;

#[derive(Debug)]
pub struct Refusal {
    pub word: &'static str,
    pub offset: usize,
}

impl std::fmt::Display for Refusal {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "refused: {} at byte {}", self.word, self.offset)
    }
}

impl std::error::Error for Refusal {}

fn append_rune(out: &mut Vec<u8>, cp: u32) {
    if cp < 0x80 {
        out.push(cp as u8);
    } else if cp < 0x800 {
        out.push(0xC0 | (cp >> 6) as u8);
        out.push(0x80 | (cp & 0x3F) as u8);
    } else if cp < 0x10000 {
        out.push(0xE0 | (cp >> 12) as u8);
        out.push(0x80 | ((cp >> 6) & 0x3F) as u8);
        out.push(0x80 | (cp & 0x3F) as u8);
    } else {
        out.push(0xF0 | (cp >> 18) as u8);
        out.push(0x80 | ((cp >> 12) & 0x3F) as u8);
        out.push(0x80 | ((cp >> 6) & 0x3F) as u8);
        out.push(0x80 | (cp & 0x3F) as u8);
    }
}

struct Reader<'a> {
    buf: &'a [u8],
    pos: usize,
    depth: i32,
}

impl<'a> Reader<'a> {
    fn refuse<T>(&self, word: &'static str) -> Result<T, Refusal> {
        Err(Refusal { word, offset: self.pos })
    }

    fn at(&self) -> u8 {
        if self.pos < self.buf.len() { self.buf[self.pos] } else { 0 }
    }

    fn skip_ws(&mut self) {
        while self.pos < self.buf.len() && ws(self.buf[self.pos]) {
            self.pos += 1;
        }
    }

    fn enter(&mut self) -> Result<(), Refusal> {
        self.depth += 1;
        if self.depth > DEPTH_LIMIT {
            return self.refuse("depth_exceeded");
        }
        Ok(())
    }

    fn string(&mut self) -> Result<String, Refusal> {
        if self.at() != b'"' {
            return self.refuse("wrong_type");
        }
        self.pos += 1;
        let mut out: Vec<u8> = Vec::new();
        loop {
            if self.pos >= self.buf.len() {
                return self.refuse("malformed");
            }
            let c = self.buf[self.pos];
            if c == b'"' {
                self.pos += 1;
                return match String::from_utf8(out) {
                    Ok(s) => Ok(s),
                    Err(_) => self.refuse("bad_string"),
                };
            }
            if c < 0x20 {
                return self.refuse("bad_string");
            }
            if c == b'\\' {
                self.escape(&mut out)?;
            } else {
                out.push(c);
                self.pos += 1;
            }
        }
    }

    fn escape(&mut self, out: &mut Vec<u8>) -> Result<(), Refusal> {
        self.pos += 1;
        if self.pos >= self.buf.len() {
            return self.refuse("malformed");
        }
        let c = self.buf[self.pos];
        self.pos += 1;
        match c {
            b'"' | b'\\' | b'/' => out.push(c),
            b'b' => out.push(0x08),
            b'f' => out.push(0x0c),
            b'n' => out.push(b'\n'),
            b'r' => out.push(b'\r'),
            b't' => out.push(b'\t'),
            b'u' => {
                let mut u = self.hex4()?;
                if (0xDC00..=0xDFFF).contains(&u) {
                    return self.refuse("bad_string");
                }
                if (0xD800..=0xDBFF).contains(&u) {
                    if self.pos + 1 >= self.buf.len()
                        || self.buf[self.pos] != b'\\'
                        || self.buf[self.pos + 1] != b'u'
                    {
                        return self.refuse("bad_string");
                    }
                    self.pos += 2;
                    let low = self.hex4()?;
                    if !(0xDC00..=0xDFFF).contains(&low) {
                        return self.refuse("bad_string");
                    }
                    u = 0x10000 + ((u - 0xD800) << 10) + (low - 0xDC00);
                }
                append_rune(out, u);
            }
            _ => return self.refuse("bad_string"),
        }
        Ok(())
    }

    fn hex4(&mut self) -> Result<u32, Refusal> {
        if self.pos + 4 > self.buf.len() {
            return self.refuse("bad_string");
        }
        let mut u: u32 = 0;
        for i in 0..4 {
            let c = self.buf[self.pos + i];
            let d = match c {
                b'0'..=b'9' => c - b'0',
                b'a'..=b'f' => c - b'a' + 10,
                b'A'..=b'F' => c - b'A' + 10,
                _ => return self.refuse("bad_string"),
            };
            u = u << 4 | d as u32;
        }
        self.pos += 4;
        Ok(u)
    }

    fn integer(&mut self, low: i64, high: i64) -> Result<i64, Refusal> {
        let c = self.at();
        if c != b'-' && !c.is_ascii_digit() {
            return self.refuse("wrong_type");
        }
        let negative = c == b'-';
        if negative {
            self.pos += 1;
        }
        if !self.at().is_ascii_digit() {
            return self.refuse("malformed");
        }
        let mut u: u64 = 0;
        if self.at() == b'0' {
            self.pos += 1;
        } else {
            while self.at().is_ascii_digit() {
                if u > 922337203685477580 {
                    return self.refuse("number_spelling");
                }
                u = u * 10 + (self.at() - b'0') as u64;
                self.pos += 1;
            }
        }
        let after = self.at();
        if after == b'.' || after == b'e' || after == b'E' || after.is_ascii_digit() {
            return self.refuse("number_spelling");
        }
        if negative && u == 0 {
            return self.refuse("number_spelling");
        }
        let n = if negative {
            if u > 1u64 << 63 {
                return self.refuse("number_spelling");
            }
            if u == 1u64 << 63 { i64::MIN } else { -(u as i64) }
        } else {
            if u > i64::MAX as u64 {
                return self.refuse("number_spelling");
            }
            u as i64
        };
        if n < low || n > high {
            return self.refuse("number_spelling");
        }
        Ok(n)
    }

    fn boolean(&mut self) -> Result<bool, Refusal> {
        match self.at() {
            b't' => {
                self.literal(b"true")?;
                Ok(true)
            }
            b'f' => {
                self.literal(b"false")?;
                Ok(false)
            }
            _ => self.refuse("wrong_type"),
        }
    }

    fn literal(&mut self, word: &[u8]) -> Result<(), Refusal> {
        if self.pos + word.len() > self.buf.len() || &self.buf[self.pos..self.pos + word.len()] != word {
            return self.refuse("malformed");
        }
        self.pos += word.len();
        Ok(())
    }

    fn str_list(&mut self) -> Result<Vec<String>, Refusal> {
        if self.at() != b'[' {
            return self.refuse("wrong_type");
        }
        self.enter()?;
        self.pos += 1;
        let mut out = Vec::new();
        self.skip_ws();
        if self.at() != b']' {
            loop {
                self.skip_ws();
                out.push(self.string()?);
                self.skip_ws();
                if self.at() != b',' {
                    break;
                }
                self.pos += 1;
            }
        }
        if self.at() != b']' {
            return self.refuse("malformed");
        }
        self.pos += 1;
        self.depth -= 1;
        Ok(out)
    }

    fn raw_map(&mut self) -> Result<BTreeMap<String, Raw>, Refusal> {
        if self.at() != b'{' {
            return self.refuse("wrong_type");
        }
        self.enter()?;
        self.pos += 1;
        let mut out = BTreeMap::new();
        self.skip_ws();
        if self.at() != b'}' {
            loop {
                self.skip_ws();
                if self.at() != b'"' {
                    return self.refuse("malformed");
                }
                let k = self.string()?;
                if out.contains_key(&k) {
                    return self.refuse("duplicate_key");
                }
                self.skip_ws();
                if self.at() != b':' {
                    return self.refuse("malformed");
                }
                self.pos += 1;
                self.skip_ws();
                let v = self.raw_value()?;
                out.insert(k, v);
                self.skip_ws();
                if self.at() != b',' {
                    break;
                }
                self.pos += 1;
            }
        }
        if self.at() != b'}' {
            return self.refuse("malformed");
        }
        self.pos += 1;
        self.depth -= 1;
        Ok(out)
    }

    fn raw_value(&mut self) -> Result<Raw, Refusal> {
        let start = self.pos;
        self.skip_value()?;
        Ok(self.buf[start..self.pos].to_vec())
    }

    fn skip_value(&mut self) -> Result<(), Refusal> {
        let c = self.at();
        match c {
            b'"' => self.skip_string(),
            b'{' | b'[' => self.skip_container(),
            b't' => self.literal(b"true"),
            b'f' => self.literal(b"false"),
            b'n' => self.literal(b"null"),
            b'-' => self.skip_number(),
            _ if c.is_ascii_digit() => self.skip_number(),
            _ => self.refuse("malformed"),
        }
    }

    // An opaque value is validated and carried, never interpreted. Its syntax is
    // the record's own — the same string reader, so an escape, a control byte or
    // a lone surrogate is judged identically at any depth — and what it is free
    // to spell, it keeps: the bytes between these two offsets are what a writer
    // re-emits. A number is walked, never converted, so a value no host type
    // holds survives the reader that carried it.
    fn skip_string(&mut self) -> Result<(), Refusal> {
        self.string()?;
        Ok(())
    }

    fn some_digits(&mut self) -> Result<(), Refusal> {
        let mut n = 0;
        while self.at().is_ascii_digit() {
            self.pos += 1;
            n += 1;
        }
        if n == 0 {
            return self.refuse("number_spelling");
        }
        Ok(())
    }

    fn skip_number(&mut self) -> Result<(), Refusal> {
        if self.at() == b'-' {
            self.pos += 1;
        }
        match self.at() {
            b'0' => self.pos += 1,
            c if c.is_ascii_digit() => {
                while self.at().is_ascii_digit() {
                    self.pos += 1;
                }
            }
            _ => return self.refuse("number_spelling"),
        }
        if self.at() == b'.' {
            self.pos += 1;
            self.some_digits()?;
        }
        if self.at() == b'e' || self.at() == b'E' {
            self.pos += 1;
            if self.at() == b'+' || self.at() == b'-' {
                self.pos += 1;
            }
            self.some_digits()?;
        }
        Ok(())
    }

    fn skip_container(&mut self) -> Result<(), Refusal> {
        let opener = self.at();
        let shut = if opener == b'{' { b'}' } else { b']' };
        self.enter()?;
        self.pos += 1;
        self.skip_ws();
        let mut seen: BTreeMap<String, bool> = BTreeMap::new();
        if self.at() != shut {
            loop {
                self.skip_ws();
                if opener == b'{' {
                    if self.at() != b'"' {
                        return self.refuse("malformed");
                    }
                    let k = self.string()?;
                    if seen.insert(k, true).is_some() {
                        return self.refuse("duplicate_key");
                    }
                    self.skip_ws();
                    if self.at() != b':' {
                        return self.refuse("malformed");
                    }
                    self.pos += 1;
                    self.skip_ws();
                }
                self.skip_value()?;
                self.skip_ws();
                if self.at() != b',' {
                    break;
                }
                self.pos += 1;
            }
        }
        if self.at() != shut {
            return self.refuse("malformed");
        }
        self.pos += 1;
        self.depth -= 1;
        Ok(())
    }
}

fn str_map(r: &mut Reader) -> Result<BTreeMap<String, String>, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut out = BTreeMap::new();
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let k = r.string()?;
            if out.contains_key(&k) {
                return r.refuse("duplicate_key");
            }
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            let v = r.string()?;
            out.insert(k, v);
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    Ok(out)
}

fn decode_list<T>(
    r: &mut Reader,
    elem: fn(&mut Reader) -> Result<T, Refusal>,
) -> Result<Vec<T>, Refusal> {
    if r.at() != b'[' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut out = Vec::new();
    r.skip_ws();
    if r.at() != b']' {
        loop {
            r.skip_ws();
            out.push(elem(r)?);
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b']' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    Ok(out)
}

fn decode_question(r: &mut Reader) -> Result<Question, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut v = Question::default();
    let mut seen: u32 = 0;
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let key = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            match key.as_str() {
                "asker" => {
                    if seen & 1 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1;
                    v.asker = r.string()?;
                }
                "key" => {
                    if seen & 2 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 2;
                    v.key = r.string()?;
                }
                "slots" => {
                    if seen & 4 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 4;
                    v.slots = str_map(r)?;
                }
                _ => {
                    return r.refuse("unknown_field");
                }
            }
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    if seen & 3 != 3 {
        return r.refuse("missing_field");
    }
    Ok(v)
}

fn decode_request(r: &mut Reader) -> Result<Request, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut v = Request::default();
    let mut seen: u32 = 0;
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let key = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            match key.as_str() {
                "op" => {
                    if seen & 1 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1;
                    v.op = r.string()?;
                }
                "ask" => {
                    if seen & 2 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 2;
                    v.ask = Some(decode_question(r)?);
                }
                "wait" => {
                    if seen & 4 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 4;
                    v.wait = r.boolean()?;
                }
                "id" => {
                    if seen & 8 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 8;
                    v.id = r.string()?;
                }
                "option" => {
                    if seen & 16 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 16;
                    v.option = r.string()?;
                }
                "admin" => {
                    if seen & 32 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 32;
                    v.admin = r.string()?;
                }
                _ => {
                    return r.refuse("unknown_field");
                }
            }
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    if seen & 1 != 1 {
        return r.refuse("missing_field");
    }
    Ok(v)
}

fn decode_answer(r: &mut Reader) -> Result<Answer, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut v = Answer::default();
    let mut seen: u32 = 0;
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let key = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            match key.as_str() {
                "id" => {
                    if seen & 1 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1;
                    v.id = r.string()?;
                }
                "pending" => {
                    if seen & 2 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 2;
                    v.pending = r.boolean()?;
                }
                "option" => {
                    if seen & 4 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 4;
                    v.option = r.string()?;
                }
                "yes" => {
                    if seen & 8 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 8;
                    v.yes = r.boolean()?;
                }
                "kept" => {
                    if seen & 16 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 16;
                    v.kept = r.boolean()?;
                }
                _ => {
                    return r.refuse("unknown_field");
                }
            }
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    if seen & 1 != 1 {
        return r.refuse("missing_field");
    }
    Ok(v)
}

fn decode_recordmetadata(r: &mut Reader) -> Result<RecordMetadata, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut v = RecordMetadata::default();
    let mut seen: u32 = 0;
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let key = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            match key.as_str() {
                "id" => {
                    if seen & 1 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1;
                    v.id = r.string()?;
                }
                "asker" => {
                    if seen & 2 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 2;
                    v.asker = r.string()?;
                }
                "key" => {
                    if seen & 4 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 4;
                    v.key = r.string()?;
                }
                "about" => {
                    if seen & 8 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 8;
                    v.about = r.string()?;
                }
                "text" => {
                    if seen & 16 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 16;
                    v.text = r.string()?;
                }
                "options" => {
                    if seen & 32 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 32;
                    v.options = r.str_list()?;
                }
                "asked" => {
                    if seen & 64 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 64;
                    v.asked = r.string()?;
                }
                "option" => {
                    if seen & 128 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 128;
                    v.option = r.string()?;
                }
                "answered" => {
                    if seen & 256 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 256;
                    v.answered = r.string()?;
                }
                "kept" => {
                    if seen & 512 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 512;
                    v.kept = r.boolean()?;
                }
                "yes" => {
                    if seen & 1024 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1024;
                    v.yes = r.boolean()?;
                }
                _ => {
                    return r.refuse("unknown_field");
                }
            }
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    if seen & 119 != 119 {
        return r.refuse("missing_field");
    }
    Ok(v)
}

fn decode_responsemetadata(r: &mut Reader) -> Result<ResponseMetadata, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut v = ResponseMetadata::default();
    let mut seen: u32 = 0;
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let key = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            match key.as_str() {
                "code" => {
                    if seen & 1 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1;
                    v.code = r.string()?;
                }
                "error" => {
                    if seen & 2 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 2;
                    v.error = r.string()?;
                }
                "answer" => {
                    if seen & 4 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 4;
                    v.answer = Some(decode_answer(r)?);
                }
                "records" => {
                    if seen & 8 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 8;
                    v.records = decode_list(r, decode_recordmetadata)?;
                }
                _ => {
                    return r.refuse("unknown_field");
                }
            }
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    Ok(v)
}

fn decode_applicationquestion(r: &mut Reader) -> Result<ApplicationQuestion, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut v = ApplicationQuestion::default();
    let mut seen: u32 = 0;
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let key = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            match key.as_str() {
                "request_key" => {
                    if seen & 1 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1;
                    v.request_key = r.string()?;
                }
                "key" => {
                    if seen & 2 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 2;
                    v.key = r.string()?;
                }
                "slots" => {
                    if seen & 4 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 4;
                    v.slots = str_map(r)?;
                }
                _ => {
                    return r.refuse("unknown_field");
                }
            }
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    if seen & 7 != 7 {
        return r.refuse("missing_field");
    }
    Ok(v)
}

fn decode_questionobservation(r: &mut Reader) -> Result<QuestionObservation, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut v = QuestionObservation::default();
    let mut seen: u32 = 0;
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let key = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            match key.as_str() {
                "outcome" => {
                    if seen & 1 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1;
                    v.outcome = r.string()?;
                }
                "answer" => {
                    if seen & 2 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 2;
                    v.answer = Some(decode_answer(r)?);
                }
                _ => {
                    return r.refuse("unknown_field");
                }
            }
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    if seen & 1 != 1 {
        return r.refuse("missing_field");
    }
    if v.outcome != "pending" && v.outcome != "answered" && v.outcome != "unknown" && v.outcome != "gone" && v.outcome != "invalid" && v.outcome != "conflict" && v.outcome != "forbidden" && v.outcome != "unavailable" { return r.refuse("bad_enum"); }
    Ok(v)
}

fn decode_operatorpage(r: &mut Reader) -> Result<OperatorPage, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut v = OperatorPage::default();
    let mut seen: u32 = 0;
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let key = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            match key.as_str() {
                "outcome" => {
                    if seen & 1 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1;
                    v.outcome = r.string()?;
                }
                "records" => {
                    if seen & 2 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 2;
                    v.records = decode_list(r, decode_recordmetadata)?;
                }
                "next" => {
                    if seen & 4 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 4;
                    v.next = r.string()?;
                }
                "complete" => {
                    if seen & 8 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 8;
                    v.complete = r.boolean()?;
                }
                _ => {
                    return r.refuse("unknown_field");
                }
            }
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    if seen & 15 != 15 {
        return r.refuse("missing_field");
    }
    if v.outcome != "page" && v.outcome != "gap" && v.outcome != "invalid" && v.outcome != "forbidden" && v.outcome != "unavailable" { return r.refuse("bad_enum"); }
    Ok(v)
}

fn decode_operatordecision(r: &mut Reader) -> Result<OperatorDecision, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut v = OperatorDecision::default();
    let mut seen: u32 = 0;
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let key = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            match key.as_str() {
                "outcome" => {
                    if seen & 1 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1;
                    v.outcome = r.string()?;
                }
                "record" => {
                    if seen & 2 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 2;
                    v.record = Some(decode_recordmetadata(r)?);
                }
                _ => {
                    return r.refuse("unknown_field");
                }
            }
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    if seen & 1 != 1 {
        return r.refuse("missing_field");
    }
    if v.outcome != "answered" && v.outcome != "conflict" && v.outcome != "unknown" && v.outcome != "invalid" && v.outcome != "forbidden" && v.outcome != "unavailable" { return r.refuse("bad_enum"); }
    Ok(v)
}

fn decode_operatorretirement(r: &mut Reader) -> Result<OperatorRetirement, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut v = OperatorRetirement::default();
    let mut seen: u32 = 0;
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let key = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            match key.as_str() {
                "outcome" => {
                    if seen & 1 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1;
                    v.outcome = r.string()?;
                }
                "record" => {
                    if seen & 2 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 2;
                    v.record = Some(decode_recordmetadata(r)?);
                }
                _ => {
                    return r.refuse("unknown_field");
                }
            }
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    if seen & 1 != 1 {
        return r.refuse("missing_field");
    }
    if v.outcome != "retired" && v.outcome != "unknown" && v.outcome != "invalid" && v.outcome != "forbidden" && v.outcome != "unavailable" { return r.refuse("bad_enum"); }
    Ok(v)
}

fn decode_oaquestionapplicationaskarguments(r: &mut Reader) -> Result<OAQuestionApplicationAskArguments, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut v = OAQuestionApplicationAskArguments::default();
    let mut seen: u32 = 0;
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let key = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            match key.as_str() {
                "question" => {
                    if seen & 1 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1;
                    v.question = decode_applicationquestion(r)?;
                }
                _ => {
                    return r.refuse("unknown_field");
                }
            }
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    if seen & 1 != 1 {
        return r.refuse("missing_field");
    }
    Ok(v)
}

fn decode_oaquestionapplicationobservearguments(r: &mut Reader) -> Result<OAQuestionApplicationObserveArguments, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut v = OAQuestionApplicationObserveArguments::default();
    let mut seen: u32 = 0;
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let key = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            match key.as_str() {
                "request_key" => {
                    if seen & 1 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1;
                    v.request_key = r.string()?;
                }
                "wait_ms" => {
                    if seen & 2 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 2;
                    v.wait_ms = r.integer(i64::MIN, i64::MAX)?;
                }
                _ => {
                    return r.refuse("unknown_field");
                }
            }
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    if seen & 3 != 3 {
        return r.refuse("missing_field");
    }
    Ok(v)
}

fn decode_oaquestionoperatorlistquestionsarguments(r: &mut Reader) -> Result<OAQuestionOperatorListQuestionsArguments, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut v = OAQuestionOperatorListQuestionsArguments::default();
    let mut seen: u32 = 0;
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let key = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            match key.as_str() {
                "cursor" => {
                    if seen & 1 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1;
                    v.cursor = r.string()?;
                }
                "limit" => {
                    if seen & 2 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 2;
                    v.limit = r.integer(i64::MIN, i64::MAX)?;
                }
                _ => {
                    return r.refuse("unknown_field");
                }
            }
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    if seen & 3 != 3 {
        return r.refuse("missing_field");
    }
    Ok(v)
}

fn decode_oaquestionoperatoranswerquestionarguments(r: &mut Reader) -> Result<OAQuestionOperatorAnswerQuestionArguments, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut v = OAQuestionOperatorAnswerQuestionArguments::default();
    let mut seen: u32 = 0;
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let key = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            match key.as_str() {
                "id" => {
                    if seen & 1 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1;
                    v.id = r.string()?;
                }
                "option" => {
                    if seen & 2 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 2;
                    v.option = r.string()?;
                }
                _ => {
                    return r.refuse("unknown_field");
                }
            }
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    if seen & 3 != 3 {
        return r.refuse("missing_field");
    }
    Ok(v)
}

fn decode_oaquestionoperatorretirequestionarguments(r: &mut Reader) -> Result<OAQuestionOperatorRetireQuestionArguments, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut v = OAQuestionOperatorRetireQuestionArguments::default();
    let mut seen: u32 = 0;
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let key = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            match key.as_str() {
                "id" => {
                    if seen & 1 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1;
                    v.id = r.string()?;
                }
                _ => {
                    return r.refuse("unknown_field");
                }
            }
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    if seen & 1 != 1 {
        return r.refuse("missing_field");
    }
    Ok(v)
}

fn decode_oaserviceframe(r: &mut Reader) -> Result<OAServiceFrame, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut v = OAServiceFrame::default();
    let mut seen: u32 = 0;
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let key = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            match key.as_str() {
                "version" => {
                    if seen & 1 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1;
                    v.version = r.integer(-2147483648, 2147483647)? as i32;
                }
                "service" => {
                    if seen & 2 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 2;
                    v.service = r.string()?;
                }
                "method" => {
                    if seen & 4 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 4;
                    v.method = r.string()?;
                }
                "arguments" => {
                    if seen & 8 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 8;
                    v.arguments = r.raw_value()?;
                }
                _ => {
                    return r.refuse("unknown_field");
                }
            }
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    if seen & 15 != 15 {
        return r.refuse("missing_field");
    }
    Ok(v)
}

fn decode_oaservicereply(r: &mut Reader) -> Result<OAServiceReply, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut v = OAServiceReply::default();
    let mut seen: u32 = 0;
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let key = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            match key.as_str() {
                "version" => {
                    if seen & 1 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1;
                    v.version = r.integer(-2147483648, 2147483647)? as i32;
                }
                "service" => {
                    if seen & 2 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 2;
                    v.service = r.string()?;
                }
                "method" => {
                    if seen & 4 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 4;
                    v.method = r.string()?;
                }
                "ok" => {
                    if seen & 8 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 8;
                    v.ok = r.boolean()?;
                }
                "payload" => {
                    if seen & 16 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 16;
                    v.payload = r.raw_value()?;
                }
                _ => {
                    return r.refuse("unknown_field");
                }
            }
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    if seen & 31 != 31 {
        return r.refuse("missing_field");
    }
    Ok(v)
}

fn decode_oaserviceerror(r: &mut Reader) -> Result<OAServiceError, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut v = OAServiceError::default();
    let mut seen: u32 = 0;
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let key = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            match key.as_str() {
                "code" => {
                    if seen & 1 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1;
                    v.code = r.string()?;
                }
                "message" => {
                    if seen & 2 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 2;
                    v.message = r.string()?;
                }
                _ => {
                    return r.refuse("unknown_field");
                }
            }
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    if seen & 3 != 3 {
        return r.refuse("missing_field");
    }
    Ok(v)
}

fn decode_oaquestionapplicationaskresult(r: &mut Reader) -> Result<OAQuestionApplicationAskResult, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut v = OAQuestionApplicationAskResult::default();
    let mut seen: u32 = 0;
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let key = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            match key.as_str() {
                "value" => {
                    if seen & 1 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1;
                    v.value = decode_questionobservation(r)?;
                }
                _ => {
                    return r.refuse("unknown_field");
                }
            }
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    if seen & 1 != 1 {
        return r.refuse("missing_field");
    }
    Ok(v)
}

fn decode_oaquestionapplicationobserveresult(r: &mut Reader) -> Result<OAQuestionApplicationObserveResult, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut v = OAQuestionApplicationObserveResult::default();
    let mut seen: u32 = 0;
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let key = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            match key.as_str() {
                "value" => {
                    if seen & 1 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1;
                    v.value = decode_questionobservation(r)?;
                }
                _ => {
                    return r.refuse("unknown_field");
                }
            }
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    if seen & 1 != 1 {
        return r.refuse("missing_field");
    }
    Ok(v)
}

fn decode_oaquestionoperatorlistquestionsresult(r: &mut Reader) -> Result<OAQuestionOperatorListQuestionsResult, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut v = OAQuestionOperatorListQuestionsResult::default();
    let mut seen: u32 = 0;
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let key = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            match key.as_str() {
                "value" => {
                    if seen & 1 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1;
                    v.value = decode_operatorpage(r)?;
                }
                _ => {
                    return r.refuse("unknown_field");
                }
            }
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    if seen & 1 != 1 {
        return r.refuse("missing_field");
    }
    Ok(v)
}

fn decode_oaquestionoperatoranswerquestionresult(r: &mut Reader) -> Result<OAQuestionOperatorAnswerQuestionResult, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut v = OAQuestionOperatorAnswerQuestionResult::default();
    let mut seen: u32 = 0;
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let key = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            match key.as_str() {
                "value" => {
                    if seen & 1 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1;
                    v.value = decode_operatordecision(r)?;
                }
                _ => {
                    return r.refuse("unknown_field");
                }
            }
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    if seen & 1 != 1 {
        return r.refuse("missing_field");
    }
    Ok(v)
}

fn decode_oaquestionoperatorretirequestionresult(r: &mut Reader) -> Result<OAQuestionOperatorRetireQuestionResult, Refusal> {
    if r.at() != b'{' {
        return r.refuse("wrong_type");
    }
    r.enter()?;
    r.pos += 1;
    let mut v = OAQuestionOperatorRetireQuestionResult::default();
    let mut seen: u32 = 0;
    r.skip_ws();
    if r.at() != b'}' {
        loop {
            r.skip_ws();
            if r.at() != b'"' {
                return r.refuse("malformed");
            }
            let key = r.string()?;
            r.skip_ws();
            if r.at() != b':' {
                return r.refuse("malformed");
            }
            r.pos += 1;
            r.skip_ws();
            match key.as_str() {
                "value" => {
                    if seen & 1 != 0 {
                        return r.refuse("duplicate_field");
                    }
                    seen |= 1;
                    v.value = decode_operatorretirement(r)?;
                }
                _ => {
                    return r.refuse("unknown_field");
                }
            }
            r.skip_ws();
            if r.at() != b',' {
                break;
            }
            r.pos += 1;
        }
    }
    if r.at() != b'}' {
        return r.refuse("malformed");
    }
    r.pos += 1;
    r.depth -= 1;
    if seen & 1 != 1 {
        return r.refuse("missing_field");
    }
    Ok(v)
}

pub fn decode(data: &[u8]) -> Result<Request, Refusal> {
    let mut r = Reader { buf: data, pos: 0, depth: 0 };
    r.skip_ws();
    let v = decode_request(&mut r)?;
    r.skip_ws();
    if r.pos < r.buf.len() {
        return r.refuse("trailing_bytes");
    }
    Ok(v)
}

// REFUSALS is in the order two of them are chosen between.
pub const REFUSALS: [&str; 11] = ["malformed", "bad_string", "number_spelling", "wrong_type", "depth_exceeded", "duplicate_key", "duplicate_field", "unknown_field", "missing_field", "bad_enum", "trailing_bytes"];

pub fn refusal_rank(word: &str) -> i32 {
    match REFUSALS.iter().position(|w| *w == word) {
        Some(i) => i as i32,
        None => -1,
    }
}

#[allow(unused_variables)]
fn service_check_question(v: &Question) -> Result<(), Refusal> {
    let r = Reader { buf: &[], pos: 0, depth: 0 };
    Ok(())
}

#[allow(unused_variables)]
fn service_check_request(v: &Request) -> Result<(), Refusal> {
    let r = Reader { buf: &[], pos: 0, depth: 0 };
    if let Some(value) = &v.ask { service_check_question(value)?; }
    Ok(())
}

#[allow(unused_variables)]
fn service_check_answer(v: &Answer) -> Result<(), Refusal> {
    let r = Reader { buf: &[], pos: 0, depth: 0 };
    Ok(())
}

#[allow(unused_variables)]
fn service_check_recordmetadata(v: &RecordMetadata) -> Result<(), Refusal> {
    let r = Reader { buf: &[], pos: 0, depth: 0 };
    Ok(())
}

#[allow(unused_variables)]
fn service_check_responsemetadata(v: &ResponseMetadata) -> Result<(), Refusal> {
    let r = Reader { buf: &[], pos: 0, depth: 0 };
    if let Some(value) = &v.answer { service_check_answer(value)?; }
    for value in &v.records { service_check_recordmetadata(value)?; }
    Ok(())
}

#[allow(unused_variables)]
fn service_check_applicationquestion(v: &ApplicationQuestion) -> Result<(), Refusal> {
    let r = Reader { buf: &[], pos: 0, depth: 0 };
    Ok(())
}

#[allow(unused_variables)]
fn service_check_questionobservation(v: &QuestionObservation) -> Result<(), Refusal> {
    let r = Reader { buf: &[], pos: 0, depth: 0 };
    if v.outcome != "pending" && v.outcome != "answered" && v.outcome != "unknown" && v.outcome != "gone" && v.outcome != "invalid" && v.outcome != "conflict" && v.outcome != "forbidden" && v.outcome != "unavailable" { return r.refuse("bad_enum"); }
    if let Some(value) = &v.answer { service_check_answer(value)?; }
    Ok(())
}

#[allow(unused_variables)]
fn service_check_operatorpage(v: &OperatorPage) -> Result<(), Refusal> {
    let r = Reader { buf: &[], pos: 0, depth: 0 };
    if v.outcome != "page" && v.outcome != "gap" && v.outcome != "invalid" && v.outcome != "forbidden" && v.outcome != "unavailable" { return r.refuse("bad_enum"); }
    for value in &v.records { service_check_recordmetadata(value)?; }
    Ok(())
}

#[allow(unused_variables)]
fn service_check_operatordecision(v: &OperatorDecision) -> Result<(), Refusal> {
    let r = Reader { buf: &[], pos: 0, depth: 0 };
    if v.outcome != "answered" && v.outcome != "conflict" && v.outcome != "unknown" && v.outcome != "invalid" && v.outcome != "forbidden" && v.outcome != "unavailable" { return r.refuse("bad_enum"); }
    if let Some(value) = &v.record { service_check_recordmetadata(value)?; }
    Ok(())
}

#[allow(unused_variables)]
fn service_check_operatorretirement(v: &OperatorRetirement) -> Result<(), Refusal> {
    let r = Reader { buf: &[], pos: 0, depth: 0 };
    if v.outcome != "retired" && v.outcome != "unknown" && v.outcome != "invalid" && v.outcome != "forbidden" && v.outcome != "unavailable" { return r.refuse("bad_enum"); }
    if let Some(value) = &v.record { service_check_recordmetadata(value)?; }
    Ok(())
}

#[allow(unused_variables)]
fn service_check_oaquestionapplicationaskarguments(v: &OAQuestionApplicationAskArguments) -> Result<(), Refusal> {
    let r = Reader { buf: &[], pos: 0, depth: 0 };
    service_check_applicationquestion(&v.question)?;
    Ok(())
}

#[allow(unused_variables)]
fn service_check_oaquestionapplicationobservearguments(v: &OAQuestionApplicationObserveArguments) -> Result<(), Refusal> {
    let r = Reader { buf: &[], pos: 0, depth: 0 };
    Ok(())
}

#[allow(unused_variables)]
fn service_check_oaquestionoperatorlistquestionsarguments(v: &OAQuestionOperatorListQuestionsArguments) -> Result<(), Refusal> {
    let r = Reader { buf: &[], pos: 0, depth: 0 };
    Ok(())
}

#[allow(unused_variables)]
fn service_check_oaquestionoperatoranswerquestionarguments(v: &OAQuestionOperatorAnswerQuestionArguments) -> Result<(), Refusal> {
    let r = Reader { buf: &[], pos: 0, depth: 0 };
    Ok(())
}

#[allow(unused_variables)]
fn service_check_oaquestionoperatorretirequestionarguments(v: &OAQuestionOperatorRetireQuestionArguments) -> Result<(), Refusal> {
    let r = Reader { buf: &[], pos: 0, depth: 0 };
    Ok(())
}

#[allow(unused_variables)]
fn service_check_oaserviceframe(v: &OAServiceFrame) -> Result<(), Refusal> {
    let r = Reader { buf: &[], pos: 0, depth: 0 };
    Ok(())
}

#[allow(unused_variables)]
fn service_check_oaservicereply(v: &OAServiceReply) -> Result<(), Refusal> {
    let r = Reader { buf: &[], pos: 0, depth: 0 };
    Ok(())
}

#[allow(unused_variables)]
fn service_check_oaserviceerror(v: &OAServiceError) -> Result<(), Refusal> {
    let r = Reader { buf: &[], pos: 0, depth: 0 };
    Ok(())
}

#[allow(unused_variables)]
fn service_check_oaquestionapplicationaskresult(v: &OAQuestionApplicationAskResult) -> Result<(), Refusal> {
    let r = Reader { buf: &[], pos: 0, depth: 0 };
    service_check_questionobservation(&v.value)?;
    Ok(())
}

#[allow(unused_variables)]
fn service_check_oaquestionapplicationobserveresult(v: &OAQuestionApplicationObserveResult) -> Result<(), Refusal> {
    let r = Reader { buf: &[], pos: 0, depth: 0 };
    service_check_questionobservation(&v.value)?;
    Ok(())
}

#[allow(unused_variables)]
fn service_check_oaquestionoperatorlistquestionsresult(v: &OAQuestionOperatorListQuestionsResult) -> Result<(), Refusal> {
    let r = Reader { buf: &[], pos: 0, depth: 0 };
    service_check_operatorpage(&v.value)?;
    Ok(())
}

#[allow(unused_variables)]
fn service_check_oaquestionoperatoranswerquestionresult(v: &OAQuestionOperatorAnswerQuestionResult) -> Result<(), Refusal> {
    let r = Reader { buf: &[], pos: 0, depth: 0 };
    service_check_operatordecision(&v.value)?;
    Ok(())
}

#[allow(unused_variables)]
fn service_check_oaquestionoperatorretirequestionresult(v: &OAQuestionOperatorRetireQuestionResult) -> Result<(), Refusal> {
    let r = Reader { buf: &[], pos: 0, depth: 0 };
    service_check_operatorretirement(&v.value)?;
    Ok(())
}

/// Common generated framing boundary; implementation owns waiting and identity.
pub use abstraction_frame::FrameTransport;

#[derive(Debug)]
pub struct ServiceError { pub code: String, pub message: String }
#[derive(Debug)]
pub enum CallError<E> {
    /// Transport failure does not establish whether the receiver accepted work.
    Transport(E),
    Refusal(Refusal),
    Dispatch(&'static str),
    Service(ServiceError),
}
fn service_decode<T>(data: &[u8], decode: fn(&mut Reader) -> Result<T, Refusal>) -> Result<T, Refusal> {
    let mut r = Reader { buf: data, pos: 0, depth: 0 };
    r.skip_ws();
    let value = decode(&mut r)?;
    r.skip_ws();
    if r.pos != data.len() { return r.refuse("trailing_bytes"); }
    Ok(value)
}
fn service_encode<T>(value: &T, check: fn(&T) -> Result<(), Refusal>, encode: fn(&mut Vec<u8>, &T, i32), decode: fn(&mut Reader) -> Result<T, Refusal>) -> Result<Vec<u8>, Refusal> {
    check(value)?;
    let mut data = Vec::new();
    encode(&mut data, value, 0);
    service_decode(&data, decode)?;
    Ok(data)
}

#[allow(non_snake_case)]
pub trait QuestionApplication {
    type Error;
    fn Ask(&self, arg0: ApplicationQuestion) -> Result<QuestionObservation, Self::Error>;
    fn Observe(&self, arg0: String, arg1: i64) -> Result<QuestionObservation, Self::Error>;
}

pub struct QuestionApplicationClient<T> { transport: T }
impl<T> QuestionApplicationClient<T> {
    pub fn new(transport: T) -> Self { Self { transport } }
    pub fn transport(&self) -> &T { &self.transport }
}
#[allow(non_snake_case)]
impl<T: FrameTransport> QuestionApplication for QuestionApplicationClient<T> {
    type Error = CallError<T::Error>;
    fn Ask(&self, arg0: ApplicationQuestion) -> Result<QuestionObservation, Self::Error> {
        let args = OAQuestionApplicationAskArguments { question: arg0, };
        let arguments = service_encode(&args, service_check_oaquestionapplicationaskarguments, enc_oaquestionapplicationaskarguments, decode_oaquestionapplicationaskarguments).map_err(CallError::Refusal)?;
        let request = OAServiceFrame { version: 1, service: "abstraction.asks/application@1".into(), method: "Ask".into(), arguments };
        let frame = service_encode(&request, service_check_oaserviceframe, enc_oaserviceframe, decode_oaserviceframe).map_err(CallError::Refusal)?;
        let reply = self.transport.exchange_frame(&frame).map_err(CallError::Transport)?;
        let reply = service_decode(&reply, decode_oaservicereply).map_err(CallError::Refusal)?;
        if reply.version != 1 { return Err(CallError::Dispatch("unknown_version")); }
        if reply.service != "abstraction.asks/application@1" || reply.method != "Ask" { return Err(CallError::Dispatch("mismatched_response")); }
        if !reply.ok {
            let error = service_decode(&reply.payload, decode_oaserviceerror).map_err(CallError::Refusal)?;
            if error.code.is_empty() { return Err(CallError::Dispatch("invalid_error")); }
            return Err(CallError::Service(ServiceError { code: error.code, message: error.message }));
        }
        let result = service_decode(&reply.payload, decode_oaquestionapplicationaskresult).map_err(CallError::Refusal)?;
        Ok(result.value)
    }
    fn Observe(&self, arg0: String, arg1: i64) -> Result<QuestionObservation, Self::Error> {
        let args = OAQuestionApplicationObserveArguments { request_key: arg0, wait_ms: arg1, };
        let arguments = service_encode(&args, service_check_oaquestionapplicationobservearguments, enc_oaquestionapplicationobservearguments, decode_oaquestionapplicationobservearguments).map_err(CallError::Refusal)?;
        let request = OAServiceFrame { version: 1, service: "abstraction.asks/application@1".into(), method: "Observe".into(), arguments };
        let frame = service_encode(&request, service_check_oaserviceframe, enc_oaserviceframe, decode_oaserviceframe).map_err(CallError::Refusal)?;
        let reply = self.transport.exchange_frame(&frame).map_err(CallError::Transport)?;
        let reply = service_decode(&reply, decode_oaservicereply).map_err(CallError::Refusal)?;
        if reply.version != 1 { return Err(CallError::Dispatch("unknown_version")); }
        if reply.service != "abstraction.asks/application@1" || reply.method != "Observe" { return Err(CallError::Dispatch("mismatched_response")); }
        if !reply.ok {
            let error = service_decode(&reply.payload, decode_oaserviceerror).map_err(CallError::Refusal)?;
            if error.code.is_empty() { return Err(CallError::Dispatch("invalid_error")); }
            return Err(CallError::Service(ServiceError { code: error.code, message: error.message }));
        }
        let result = service_decode(&reply.payload, decode_oaquestionapplicationobserveresult).map_err(CallError::Refusal)?;
        Ok(result.value)
    }
}

#[allow(non_snake_case)]
pub trait QuestionOperator {
    type Error;
    fn ListQuestions(&self, arg0: String, arg1: i64) -> Result<OperatorPage, Self::Error>;
    fn AnswerQuestion(&self, arg0: String, arg1: String) -> Result<OperatorDecision, Self::Error>;
    fn RetireQuestion(&self, arg0: String) -> Result<OperatorRetirement, Self::Error>;
}

pub struct QuestionOperatorClient<T> { transport: T }
impl<T> QuestionOperatorClient<T> {
    pub fn new(transport: T) -> Self { Self { transport } }
    pub fn transport(&self) -> &T { &self.transport }
}
#[allow(non_snake_case)]
impl<T: FrameTransport> QuestionOperator for QuestionOperatorClient<T> {
    type Error = CallError<T::Error>;
    fn ListQuestions(&self, arg0: String, arg1: i64) -> Result<OperatorPage, Self::Error> {
        let args = OAQuestionOperatorListQuestionsArguments { cursor: arg0, limit: arg1, };
        let arguments = service_encode(&args, service_check_oaquestionoperatorlistquestionsarguments, enc_oaquestionoperatorlistquestionsarguments, decode_oaquestionoperatorlistquestionsarguments).map_err(CallError::Refusal)?;
        let request = OAServiceFrame { version: 1, service: "abstraction.asks/operator@1".into(), method: "ListQuestions".into(), arguments };
        let frame = service_encode(&request, service_check_oaserviceframe, enc_oaserviceframe, decode_oaserviceframe).map_err(CallError::Refusal)?;
        let reply = self.transport.exchange_frame(&frame).map_err(CallError::Transport)?;
        let reply = service_decode(&reply, decode_oaservicereply).map_err(CallError::Refusal)?;
        if reply.version != 1 { return Err(CallError::Dispatch("unknown_version")); }
        if reply.service != "abstraction.asks/operator@1" || reply.method != "ListQuestions" { return Err(CallError::Dispatch("mismatched_response")); }
        if !reply.ok {
            let error = service_decode(&reply.payload, decode_oaserviceerror).map_err(CallError::Refusal)?;
            if error.code.is_empty() { return Err(CallError::Dispatch("invalid_error")); }
            return Err(CallError::Service(ServiceError { code: error.code, message: error.message }));
        }
        let result = service_decode(&reply.payload, decode_oaquestionoperatorlistquestionsresult).map_err(CallError::Refusal)?;
        Ok(result.value)
    }
    fn AnswerQuestion(&self, arg0: String, arg1: String) -> Result<OperatorDecision, Self::Error> {
        let args = OAQuestionOperatorAnswerQuestionArguments { id: arg0, option: arg1, };
        let arguments = service_encode(&args, service_check_oaquestionoperatoranswerquestionarguments, enc_oaquestionoperatoranswerquestionarguments, decode_oaquestionoperatoranswerquestionarguments).map_err(CallError::Refusal)?;
        let request = OAServiceFrame { version: 1, service: "abstraction.asks/operator@1".into(), method: "AnswerQuestion".into(), arguments };
        let frame = service_encode(&request, service_check_oaserviceframe, enc_oaserviceframe, decode_oaserviceframe).map_err(CallError::Refusal)?;
        let reply = self.transport.exchange_frame(&frame).map_err(CallError::Transport)?;
        let reply = service_decode(&reply, decode_oaservicereply).map_err(CallError::Refusal)?;
        if reply.version != 1 { return Err(CallError::Dispatch("unknown_version")); }
        if reply.service != "abstraction.asks/operator@1" || reply.method != "AnswerQuestion" { return Err(CallError::Dispatch("mismatched_response")); }
        if !reply.ok {
            let error = service_decode(&reply.payload, decode_oaserviceerror).map_err(CallError::Refusal)?;
            if error.code.is_empty() { return Err(CallError::Dispatch("invalid_error")); }
            return Err(CallError::Service(ServiceError { code: error.code, message: error.message }));
        }
        let result = service_decode(&reply.payload, decode_oaquestionoperatoranswerquestionresult).map_err(CallError::Refusal)?;
        Ok(result.value)
    }
    fn RetireQuestion(&self, arg0: String) -> Result<OperatorRetirement, Self::Error> {
        let args = OAQuestionOperatorRetireQuestionArguments { id: arg0, };
        let arguments = service_encode(&args, service_check_oaquestionoperatorretirequestionarguments, enc_oaquestionoperatorretirequestionarguments, decode_oaquestionoperatorretirequestionarguments).map_err(CallError::Refusal)?;
        let request = OAServiceFrame { version: 1, service: "abstraction.asks/operator@1".into(), method: "RetireQuestion".into(), arguments };
        let frame = service_encode(&request, service_check_oaserviceframe, enc_oaserviceframe, decode_oaserviceframe).map_err(CallError::Refusal)?;
        let reply = self.transport.exchange_frame(&frame).map_err(CallError::Transport)?;
        let reply = service_decode(&reply, decode_oaservicereply).map_err(CallError::Refusal)?;
        if reply.version != 1 { return Err(CallError::Dispatch("unknown_version")); }
        if reply.service != "abstraction.asks/operator@1" || reply.method != "RetireQuestion" { return Err(CallError::Dispatch("mismatched_response")); }
        if !reply.ok {
            let error = service_decode(&reply.payload, decode_oaserviceerror).map_err(CallError::Refusal)?;
            if error.code.is_empty() { return Err(CallError::Dispatch("invalid_error")); }
            return Err(CallError::Service(ServiceError { code: error.code, message: error.message }));
        }
        let result = service_decode(&reply.payload, decode_oaquestionoperatorretirequestionresult).map_err(CallError::Refusal)?;
        Ok(result.value)
    }
}
