// Code generated by abstraction-idl from abstraction-asks/asks.thrift. DO NOT EDIT.

package api

type Raw = string

func escByte(out []byte, c byte) []byte {
	const hex = "0123456789abcdef"
	switch c {
	case '"':
		return append(out, '\\', '"')
	case '\\':
		return append(out, '\\', '\\')
	case 0x08:
		return append(out, '\\', 'b')
	case 0x0c:
		return append(out, '\\', 'f')
	case '\n':
		return append(out, '\\', 'n')
	case '\r':
		return append(out, '\\', 'r')
	case '\t':
		return append(out, '\\', 't')
	}
	if c < 0x20 {
		return append(out, '\\', 'u', '0', '0', hex[c>>4], hex[c&0xF])
	}
	return append(out, c)
}

func num(out []byte, n int64) []byte {
	if n == 0 {
		return append(out, '0')
	}
	var d [24]byte
	p := len(d)
	u := uint64(n)
	if n < 0 {
		u = -uint64(n)
	}
	for u > 0 {
		p--
		d[p] = byte('0' + u%10)
		u /= 10
	}
	if n < 0 {
		out = append(out, '-')
	}
	return append(out, d[p:]...)
}

func pad(out []byte, depth int) []byte {
	for i := 0; i < depth*2; i++ {
		out = append(out, ' ')
	}
	return out
}

func strs(out []byte, v []string, depth int) []byte {
	if len(v) == 0 {
		return append(out, '[', ']')
	}
	out = append(out, '[', '\n')
	for i, s := range v {
		out = pad(out, depth+1)
		out = esc(out, s)
		if i+1 < len(v) {
			out = append(out, ',')
		}
		out = append(out, '\n')
	}
	out = pad(out, depth)
	return append(out, ']')
}

func raw(out []byte, s string, depth int) []byte {
	ws := func(c byte) bool { return c == ' ' || c == '\t' || c == '\n' || c == '\r' }
	for i := 0; i < len(s); {
		c := s[i]
		if ws(c) {
			i++
			continue
		}
		switch c {
		case '"':
			j := i + 1
			for j < len(s) {
				if s[j] == '\\' {
					j += 2
					continue
				}
				if s[j] == '"' {
					j++
					break
				}
				j++
			}
			out = append(out, s[i:j]...)
			i = j
		case '{', '[':
			out = append(out, c)
			i++
			j := i
			for j < len(s) && ws(s[j]) {
				j++
			}
			if j < len(s) && (s[j] == '}' || s[j] == ']') {
				out = append(out, s[j])
				i = j + 1
			} else {
				depth++
				out = append(out, '\n')
				out = pad(out, depth)
			}
		case '}', ']':
			depth--
			out = append(out, '\n')
			out = pad(out, depth)
			out = append(out, c)
			i++
		case ',':
			out = append(out, ',', '\n')
			out = pad(out, depth)
			i++
		case ':':
			out = append(out, ':', ' ')
			i++
		default:
			out = append(out, c)
			i++
		}
	}
	return out
}

func byteLess(a, b string) bool {
	n := len(a)
	if len(b) < n {
		n = len(b)
	}
	for i := 0; i < n; i++ {
		if a[i] != b[i] {
			return a[i] < b[i]
		}
	}
	return len(a) < len(b)
}

func sortedKeys(m map[string]Raw) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	for i := 1; i < len(keys); i++ {
		for j := i; j > 0 && byteLess(keys[j], keys[j-1]); j-- {
			keys[j], keys[j-1] = keys[j-1], keys[j]
		}
	}
	return keys
}

func rawmap(out []byte, m map[string]Raw, depth int) []byte {
	keys := sortedKeys(m)
	if len(keys) == 0 {
		return append(out, '{', '}')
	}
	out = append(out, '{', '\n')
	for i, k := range keys {
		out = pad(out, depth+1)
		out = esc(out, k)
		out = append(out, ':', ' ')
		out = raw(out, m[k], depth+1)
		if i+1 < len(keys) {
			out = append(out, ',')
		}
		out = append(out, '\n')
	}
	out = pad(out, depth)
	return append(out, '}')
}

func esc(out []byte, s string) []byte {
	out = append(out, '"')
	for i := 0; i < len(s); i++ {
		out = escByte(out, s[i])
	}
	return append(out, '"')
}

func strmap(out []byte, m map[string]string, depth int) []byte {
	keys := sortedKeys(m)
	if len(keys) == 0 {
		return append(out, '{', '}')
	}
	out = append(out, '{', '\n')
	for i, k := range keys {
		out = pad(out, depth+1)
		out = esc(out, k)
		out = append(out, ':', ' ')
		out = esc(out, m[k])
		if i+1 < len(keys) {
			out = append(out, ',')
		}
		out = append(out, '\n')
	}
	out = pad(out, depth)
	return append(out, '}')
}

func encList[T any](out []byte, v []T, depth int, enc func([]byte, *T, int) []byte) []byte {
	if len(v) == 0 {
		return append(out, '[', ']')
	}
	out = append(out, '[', '\n')
	for i := range v {
		out = pad(out, depth+1)
		out = enc(out, &v[i], depth+1)
		if i+1 < len(v) {
			out = append(out, ',')
		}
		out = append(out, '\n')
	}
	out = pad(out, depth)
	return append(out, ']')
}

var ObservationOutcomeNames = []string{"pending", "answered", "unknown", "gone", "invalid", "conflict", "forbidden", "unavailable"}

const ObservationOutcomePending = "pending"

const ObservationOutcomeAnswered = "answered"

const ObservationOutcomeUnknown = "unknown"

const ObservationOutcomeGone = "gone"

const ObservationOutcomeInvalid = "invalid"

const ObservationOutcomeConflict = "conflict"

const ObservationOutcomeForbidden = "forbidden"

const ObservationOutcomeUnavailable = "unavailable"

const ObservationOutcomeUnknownPolicy = "refuse"

var OperatorPageOutcomeNames = []string{"page", "gap", "invalid", "forbidden", "unavailable"}

const OperatorPageOutcomePage = "page"

const OperatorPageOutcomeGap = "gap"

const OperatorPageOutcomeInvalid = "invalid"

const OperatorPageOutcomeForbidden = "forbidden"

const OperatorPageOutcomeUnavailable = "unavailable"

const OperatorPageOutcomeUnknown = "refuse"

var OperatorDecisionOutcomeNames = []string{"answered", "conflict", "unknown", "invalid", "forbidden", "unavailable"}

const OperatorDecisionOutcomeAnswered = "answered"

const OperatorDecisionOutcomeConflict = "conflict"

const OperatorDecisionOutcomeUnknown = "unknown"

const OperatorDecisionOutcomeInvalid = "invalid"

const OperatorDecisionOutcomeForbidden = "forbidden"

const OperatorDecisionOutcomeUnavailable = "unavailable"

const OperatorDecisionOutcomeUnknownPolicy = "refuse"

var Operations = []string{"ask", "pending", "answered", "answer", "forget"}

var RefusalCodes = []string{"internal", "invalid_request", "caller_refused", "unknown_operation", "not_administrator", "withdrawn", "unknown_question", "unknown_option", "bad_slot", "nothing_pending", "no_record"}

type Question struct {
	Asker string
	Key   string
	Slots map[string]string
}

type Request struct {
	Op     string
	Ask    *Question
	Wait   bool
	Id     string
	Option string
	Admin  string
}

type Answer struct {
	Id      string
	Pending bool
	Option  string
	Yes     bool
	Kept    bool
}

type RecordMetadata struct {
	Id       string
	Asker    string
	Key      string
	About    string
	Text     string
	Options  []string
	Asked    string
	Option   string
	Answered string
	Kept     bool
	Yes      bool
}

type ResponseMetadata struct {
	Code    string
	Error   string
	Answer  *Answer
	Records []RecordMetadata
}

type ApplicationQuestion struct {
	RequestKey string
	Key        string
	Slots      map[string]string
}

type QuestionObservation struct {
	Outcome string
	Answer  *Answer
}

type OperatorPage struct {
	Outcome  string
	Records  []RecordMetadata
	Next     string
	Complete bool
}

type OperatorDecision struct {
	Outcome string
	Record  *RecordMetadata
}

type OAQuestionApplicationAskArguments struct {
	Question ApplicationQuestion
}

type OAQuestionApplicationObserveArguments struct {
	RequestKey string
	WaitMs     int64
}

type OAQuestionOperatorListQuestionsArguments struct {
	Cursor string
	Limit  int64
}

type OAQuestionOperatorAnswerQuestionArguments struct {
	Id     string
	Option string
}

type OAServiceFrame struct {
	Version   int32
	Service   string
	Method    string
	Arguments Raw
}

type OAServiceReply struct {
	Version int32
	Service string
	Method  string
	Ok      bool
	Payload Raw
}

type OAServiceError struct {
	Code    string
	Message string
}

type OAQuestionApplicationAskResult struct {
	Value QuestionObservation
}

type OAQuestionApplicationObserveResult struct {
	Value QuestionObservation
}

type OAQuestionOperatorListQuestionsResult struct {
	Value OperatorPage
}

type OAQuestionOperatorAnswerQuestionResult struct {
	Value OperatorDecision
}

func encQuestion(out []byte, v *Question, depth int) []byte {
	out = append(out, '{')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "asker")
	out = append(out, ':', ' ')
	out = esc(out, v.Asker)
	out = append(out, ',')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "key")
	out = append(out, ':', ' ')
	out = esc(out, v.Key)
	if len(v.Slots) != 0 {
		out = append(out, ',')
		out = append(out, '\n')
		out = pad(out, depth+1)
		out = esc(out, "slots")
		out = append(out, ':', ' ')
		out = strmap(out, v.Slots, depth+1)
	}
	out = append(out, '\n')
	out = pad(out, depth)
	return append(out, '}')
}

func encRequest(out []byte, v *Request, depth int) []byte {
	out = append(out, '{')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "op")
	out = append(out, ':', ' ')
	out = esc(out, v.Op)
	if v.Ask != nil {
		out = append(out, ',')
		out = append(out, '\n')
		out = pad(out, depth+1)
		out = esc(out, "ask")
		out = append(out, ':', ' ')
		out = encQuestion(out, v.Ask, depth+1)
	}
	if v.Wait {
		out = append(out, ',')
		out = append(out, '\n')
		out = pad(out, depth+1)
		out = esc(out, "wait")
		out = append(out, ':', ' ')
		if v.Wait {
			out = append(out, 't', 'r', 'u', 'e')
		} else {
			out = append(out, 'f', 'a', 'l', 's', 'e')
		}
	}
	if v.Id != "" {
		out = append(out, ',')
		out = append(out, '\n')
		out = pad(out, depth+1)
		out = esc(out, "id")
		out = append(out, ':', ' ')
		out = esc(out, v.Id)
	}
	if v.Option != "" {
		out = append(out, ',')
		out = append(out, '\n')
		out = pad(out, depth+1)
		out = esc(out, "option")
		out = append(out, ':', ' ')
		out = esc(out, v.Option)
	}
	if v.Admin != "" {
		out = append(out, ',')
		out = append(out, '\n')
		out = pad(out, depth+1)
		out = esc(out, "admin")
		out = append(out, ':', ' ')
		out = esc(out, v.Admin)
	}
	out = append(out, '\n')
	out = pad(out, depth)
	return append(out, '}')
}

func encAnswer(out []byte, v *Answer, depth int) []byte {
	out = append(out, '{')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "id")
	out = append(out, ':', ' ')
	out = esc(out, v.Id)
	if v.Pending {
		out = append(out, ',')
		out = append(out, '\n')
		out = pad(out, depth+1)
		out = esc(out, "pending")
		out = append(out, ':', ' ')
		if v.Pending {
			out = append(out, 't', 'r', 'u', 'e')
		} else {
			out = append(out, 'f', 'a', 'l', 's', 'e')
		}
	}
	if v.Option != "" {
		out = append(out, ',')
		out = append(out, '\n')
		out = pad(out, depth+1)
		out = esc(out, "option")
		out = append(out, ':', ' ')
		out = esc(out, v.Option)
	}
	if v.Yes {
		out = append(out, ',')
		out = append(out, '\n')
		out = pad(out, depth+1)
		out = esc(out, "yes")
		out = append(out, ':', ' ')
		if v.Yes {
			out = append(out, 't', 'r', 'u', 'e')
		} else {
			out = append(out, 'f', 'a', 'l', 's', 'e')
		}
	}
	if v.Kept {
		out = append(out, ',')
		out = append(out, '\n')
		out = pad(out, depth+1)
		out = esc(out, "kept")
		out = append(out, ':', ' ')
		if v.Kept {
			out = append(out, 't', 'r', 'u', 'e')
		} else {
			out = append(out, 'f', 'a', 'l', 's', 'e')
		}
	}
	out = append(out, '\n')
	out = pad(out, depth)
	return append(out, '}')
}

func encRecordMetadata(out []byte, v *RecordMetadata, depth int) []byte {
	out = append(out, '{')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "id")
	out = append(out, ':', ' ')
	out = esc(out, v.Id)
	out = append(out, ',')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "asker")
	out = append(out, ':', ' ')
	out = esc(out, v.Asker)
	out = append(out, ',')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "key")
	out = append(out, ':', ' ')
	out = esc(out, v.Key)
	if v.About != "" {
		out = append(out, ',')
		out = append(out, '\n')
		out = pad(out, depth+1)
		out = esc(out, "about")
		out = append(out, ':', ' ')
		out = esc(out, v.About)
	}
	out = append(out, ',')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "text")
	out = append(out, ':', ' ')
	out = esc(out, v.Text)
	out = append(out, ',')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "options")
	out = append(out, ':', ' ')
	out = strs(out, v.Options, depth+1)
	out = append(out, ',')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "asked")
	out = append(out, ':', ' ')
	out = esc(out, v.Asked)
	if v.Option != "" {
		out = append(out, ',')
		out = append(out, '\n')
		out = pad(out, depth+1)
		out = esc(out, "option")
		out = append(out, ':', ' ')
		out = esc(out, v.Option)
	}
	if v.Answered != "" {
		out = append(out, ',')
		out = append(out, '\n')
		out = pad(out, depth+1)
		out = esc(out, "answered")
		out = append(out, ':', ' ')
		out = esc(out, v.Answered)
	}
	if v.Kept {
		out = append(out, ',')
		out = append(out, '\n')
		out = pad(out, depth+1)
		out = esc(out, "kept")
		out = append(out, ':', ' ')
		if v.Kept {
			out = append(out, 't', 'r', 'u', 'e')
		} else {
			out = append(out, 'f', 'a', 'l', 's', 'e')
		}
	}
	if v.Yes {
		out = append(out, ',')
		out = append(out, '\n')
		out = pad(out, depth+1)
		out = esc(out, "yes")
		out = append(out, ':', ' ')
		if v.Yes {
			out = append(out, 't', 'r', 'u', 'e')
		} else {
			out = append(out, 'f', 'a', 'l', 's', 'e')
		}
	}
	out = append(out, '\n')
	out = pad(out, depth)
	return append(out, '}')
}

func encResponseMetadata(out []byte, v *ResponseMetadata, depth int) []byte {
	out = append(out, '{')
	first := true
	if v.Code != "" {
		first = false
		out = append(out, '\n')
		out = pad(out, depth+1)
		out = esc(out, "code")
		out = append(out, ':', ' ')
		out = esc(out, v.Code)
	}
	if v.Error != "" {
		if !first {
			out = append(out, ',')
		}
		first = false
		out = append(out, '\n')
		out = pad(out, depth+1)
		out = esc(out, "error")
		out = append(out, ':', ' ')
		out = esc(out, v.Error)
	}
	if v.Answer != nil {
		if !first {
			out = append(out, ',')
		}
		first = false
		out = append(out, '\n')
		out = pad(out, depth+1)
		out = esc(out, "answer")
		out = append(out, ':', ' ')
		out = encAnswer(out, v.Answer, depth+1)
	}
	if len(v.Records) != 0 {
		if !first {
			out = append(out, ',')
		}
		first = false
		out = append(out, '\n')
		out = pad(out, depth+1)
		out = esc(out, "records")
		out = append(out, ':', ' ')
		out = encList(out, v.Records, depth+1, encRecordMetadata)
	}
	if !first {
		out = append(out, '\n')
		out = pad(out, depth)
	}
	return append(out, '}')
}

func encApplicationQuestion(out []byte, v *ApplicationQuestion, depth int) []byte {
	out = append(out, '{')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "request_key")
	out = append(out, ':', ' ')
	out = esc(out, v.RequestKey)
	out = append(out, ',')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "key")
	out = append(out, ':', ' ')
	out = esc(out, v.Key)
	out = append(out, ',')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "slots")
	out = append(out, ':', ' ')
	out = strmap(out, v.Slots, depth+1)
	out = append(out, '\n')
	out = pad(out, depth)
	return append(out, '}')
}

func encQuestionObservation(out []byte, v *QuestionObservation, depth int) []byte {
	if v.Outcome != "pending" && v.Outcome != "answered" && v.Outcome != "unknown" && v.Outcome != "gone" && v.Outcome != "invalid" && v.Outcome != "conflict" && v.Outcome != "forbidden" && v.Outcome != "unavailable" {
		panic(&Refusal{Word: "bad_enum", Offset: 0})
	}
	out = append(out, '{')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "outcome")
	out = append(out, ':', ' ')
	out = esc(out, v.Outcome)
	if v.Answer != nil {
		out = append(out, ',')
		out = append(out, '\n')
		out = pad(out, depth+1)
		out = esc(out, "answer")
		out = append(out, ':', ' ')
		out = encAnswer(out, v.Answer, depth+1)
	}
	out = append(out, '\n')
	out = pad(out, depth)
	return append(out, '}')
}

func encOperatorPage(out []byte, v *OperatorPage, depth int) []byte {
	if v.Outcome != "page" && v.Outcome != "gap" && v.Outcome != "invalid" && v.Outcome != "forbidden" && v.Outcome != "unavailable" {
		panic(&Refusal{Word: "bad_enum", Offset: 0})
	}
	out = append(out, '{')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "outcome")
	out = append(out, ':', ' ')
	out = esc(out, v.Outcome)
	out = append(out, ',')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "records")
	out = append(out, ':', ' ')
	out = encList(out, v.Records, depth+1, encRecordMetadata)
	out = append(out, ',')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "next")
	out = append(out, ':', ' ')
	out = esc(out, v.Next)
	out = append(out, ',')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "complete")
	out = append(out, ':', ' ')
	if v.Complete {
		out = append(out, 't', 'r', 'u', 'e')
	} else {
		out = append(out, 'f', 'a', 'l', 's', 'e')
	}
	out = append(out, '\n')
	out = pad(out, depth)
	return append(out, '}')
}

func encOperatorDecision(out []byte, v *OperatorDecision, depth int) []byte {
	if v.Outcome != "answered" && v.Outcome != "conflict" && v.Outcome != "unknown" && v.Outcome != "invalid" && v.Outcome != "forbidden" && v.Outcome != "unavailable" {
		panic(&Refusal{Word: "bad_enum", Offset: 0})
	}
	out = append(out, '{')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "outcome")
	out = append(out, ':', ' ')
	out = esc(out, v.Outcome)
	if v.Record != nil {
		out = append(out, ',')
		out = append(out, '\n')
		out = pad(out, depth+1)
		out = esc(out, "record")
		out = append(out, ':', ' ')
		out = encRecordMetadata(out, v.Record, depth+1)
	}
	out = append(out, '\n')
	out = pad(out, depth)
	return append(out, '}')
}

func encOAQuestionApplicationAskArguments(out []byte, v *OAQuestionApplicationAskArguments, depth int) []byte {
	out = append(out, '{')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "question")
	out = append(out, ':', ' ')
	out = encApplicationQuestion(out, &v.Question, depth+1)
	out = append(out, '\n')
	out = pad(out, depth)
	return append(out, '}')
}

func encOAQuestionApplicationObserveArguments(out []byte, v *OAQuestionApplicationObserveArguments, depth int) []byte {
	out = append(out, '{')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "request_key")
	out = append(out, ':', ' ')
	out = esc(out, v.RequestKey)
	out = append(out, ',')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "wait_ms")
	out = append(out, ':', ' ')
	out = num(out, v.WaitMs)
	out = append(out, '\n')
	out = pad(out, depth)
	return append(out, '}')
}

func encOAQuestionOperatorListQuestionsArguments(out []byte, v *OAQuestionOperatorListQuestionsArguments, depth int) []byte {
	out = append(out, '{')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "cursor")
	out = append(out, ':', ' ')
	out = esc(out, v.Cursor)
	out = append(out, ',')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "limit")
	out = append(out, ':', ' ')
	out = num(out, v.Limit)
	out = append(out, '\n')
	out = pad(out, depth)
	return append(out, '}')
}

func encOAQuestionOperatorAnswerQuestionArguments(out []byte, v *OAQuestionOperatorAnswerQuestionArguments, depth int) []byte {
	out = append(out, '{')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "id")
	out = append(out, ':', ' ')
	out = esc(out, v.Id)
	out = append(out, ',')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "option")
	out = append(out, ':', ' ')
	out = esc(out, v.Option)
	out = append(out, '\n')
	out = pad(out, depth)
	return append(out, '}')
}

func encOAServiceFrame(out []byte, v *OAServiceFrame, depth int) []byte {
	out = append(out, '{')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "version")
	out = append(out, ':', ' ')
	out = num(out, int64(v.Version))
	out = append(out, ',')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "service")
	out = append(out, ':', ' ')
	out = esc(out, v.Service)
	out = append(out, ',')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "method")
	out = append(out, ':', ' ')
	out = esc(out, v.Method)
	out = append(out, ',')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "arguments")
	out = append(out, ':', ' ')
	out = append(out, v.Arguments...)
	out = append(out, '\n')
	out = pad(out, depth)
	return append(out, '}')
}

func encOAServiceReply(out []byte, v *OAServiceReply, depth int) []byte {
	out = append(out, '{')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "version")
	out = append(out, ':', ' ')
	out = num(out, int64(v.Version))
	out = append(out, ',')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "service")
	out = append(out, ':', ' ')
	out = esc(out, v.Service)
	out = append(out, ',')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "method")
	out = append(out, ':', ' ')
	out = esc(out, v.Method)
	out = append(out, ',')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "ok")
	out = append(out, ':', ' ')
	if v.Ok {
		out = append(out, 't', 'r', 'u', 'e')
	} else {
		out = append(out, 'f', 'a', 'l', 's', 'e')
	}
	out = append(out, ',')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "payload")
	out = append(out, ':', ' ')
	out = append(out, v.Payload...)
	out = append(out, '\n')
	out = pad(out, depth)
	return append(out, '}')
}

func encOAServiceError(out []byte, v *OAServiceError, depth int) []byte {
	out = append(out, '{')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "code")
	out = append(out, ':', ' ')
	out = esc(out, v.Code)
	out = append(out, ',')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "message")
	out = append(out, ':', ' ')
	out = esc(out, v.Message)
	out = append(out, '\n')
	out = pad(out, depth)
	return append(out, '}')
}

func encOAQuestionApplicationAskResult(out []byte, v *OAQuestionApplicationAskResult, depth int) []byte {
	out = append(out, '{')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "value")
	out = append(out, ':', ' ')
	out = encQuestionObservation(out, &v.Value, depth+1)
	out = append(out, '\n')
	out = pad(out, depth)
	return append(out, '}')
}

func encOAQuestionApplicationObserveResult(out []byte, v *OAQuestionApplicationObserveResult, depth int) []byte {
	out = append(out, '{')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "value")
	out = append(out, ':', ' ')
	out = encQuestionObservation(out, &v.Value, depth+1)
	out = append(out, '\n')
	out = pad(out, depth)
	return append(out, '}')
}

func encOAQuestionOperatorListQuestionsResult(out []byte, v *OAQuestionOperatorListQuestionsResult, depth int) []byte {
	out = append(out, '{')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "value")
	out = append(out, ':', ' ')
	out = encOperatorPage(out, &v.Value, depth+1)
	out = append(out, '\n')
	out = pad(out, depth)
	return append(out, '}')
}

func encOAQuestionOperatorAnswerQuestionResult(out []byte, v *OAQuestionOperatorAnswerQuestionResult, depth int) []byte {
	out = append(out, '{')
	out = append(out, '\n')
	out = pad(out, depth+1)
	out = esc(out, "value")
	out = append(out, ':', ' ')
	out = encOperatorDecision(out, &v.Value, depth+1)
	out = append(out, '\n')
	out = pad(out, depth)
	return append(out, '}')
}

func Encode(v *Request) []byte {
	return append(encRequest(nil, v, 0), '\n')
}

type Refusal struct {
	Word   string
	Offset int
}

func (r *Refusal) Error() string {
	return "refused: " + r.Word + " at byte " + decimal(int64(r.Offset))
}

func decimal(n int64) string { return string(num(nil, n)) }

const depthLimit = 64

type reader struct {
	buf   []byte
	pos   int
	depth int
}

func (r *reader) refuse(word string) error { return &Refusal{Word: word, Offset: r.pos} }

func (r *reader) at() byte {
	if r.pos < len(r.buf) {
		return r.buf[r.pos]
	}
	return 0
}

func (r *reader) ws() {
	for r.pos < len(r.buf) {
		switch r.buf[r.pos] {
		case ' ', '\t', '\n', '\r':
			r.pos++
		default:
			return
		}
	}
}

func (r *reader) enter() error {
	r.depth++
	if r.depth > depthLimit {
		return r.refuse("depth_exceeded")
	}
	return nil
}

func (r *reader) str() (string, error) {
	if r.at() != '"' {
		return "", r.refuse("wrong_type")
	}
	r.pos++
	var out []byte
	for {
		if r.pos >= len(r.buf) {
			return "", r.refuse("malformed")
		}
		c := r.buf[r.pos]
		switch {
		case c == '"':
			r.pos++
			if !validUTF8(out) {
				return "", r.refuse("bad_string")
			}
			return string(out), nil
		case c < 0x20:
			return "", r.refuse("bad_string")
		case c == '\\':
			var err error
			if out, err = r.escape(out); err != nil {
				return "", err
			}
		default:
			out = append(out, c)
			r.pos++
		}
	}
}

func (r *reader) escape(out []byte) ([]byte, error) {
	r.pos++
	if r.pos >= len(r.buf) {
		return nil, r.refuse("malformed")
	}
	c := r.buf[r.pos]
	r.pos++
	switch c {
	case '"', '\\', '/':
		return append(out, c), nil
	case 'b':
		return append(out, 0x08), nil
	case 'f':
		return append(out, 0x0c), nil
	case 'n':
		return append(out, '\n'), nil
	case 'r':
		return append(out, '\r'), nil
	case 't':
		return append(out, '\t'), nil
	case 'u':
		u, err := r.hex4()
		if err != nil {
			return nil, err
		}
		if u >= 0xDC00 && u <= 0xDFFF {
			return nil, r.refuse("bad_string")
		}
		if u >= 0xD800 && u <= 0xDBFF {
			if r.pos+1 >= len(r.buf) || r.buf[r.pos] != '\\' || r.buf[r.pos+1] != 'u' {
				return nil, r.refuse("bad_string")
			}
			r.pos += 2
			lo, err := r.hex4()
			if err != nil {
				return nil, err
			}
			if lo < 0xDC00 || lo > 0xDFFF {
				return nil, r.refuse("bad_string")
			}
			u = 0x10000 + (u-0xD800)<<10 + (lo - 0xDC00)
		}
		return appendRune(out, u), nil
	}
	return nil, r.refuse("bad_string")
}

func (r *reader) hex4() (int32, error) {
	if r.pos+4 > len(r.buf) {
		return 0, r.refuse("bad_string")
	}
	var u int32
	for i := 0; i < 4; i++ {
		c := r.buf[r.pos+i]
		switch {
		case c >= '0' && c <= '9':
			u = u<<4 | int32(c-'0')
		case c >= 'a' && c <= 'f':
			u = u<<4 | int32(c-'a'+10)
		case c >= 'A' && c <= 'F':
			u = u<<4 | int32(c-'A'+10)
		default:
			return 0, r.refuse("bad_string")
		}
	}
	r.pos += 4
	return u, nil
}

func appendRune(out []byte, cp int32) []byte {
	switch {
	case cp < 0x80:
		return append(out, byte(cp))
	case cp < 0x800:
		return append(out, byte(0xC0|cp>>6), byte(0x80|cp&0x3F))
	case cp < 0x10000:
		return append(out, byte(0xE0|cp>>12), byte(0x80|cp>>6&0x3F), byte(0x80|cp&0x3F))
	}
	return append(out, byte(0xF0|cp>>18), byte(0x80|cp>>12&0x3F), byte(0x80|cp>>6&0x3F), byte(0x80|cp&0x3F))
}

func validUTF8(b []byte) bool {
	for i := 0; i < len(b); {
		c := b[i]
		var n int
		var cp int32
		switch {
		case c < 0x80:
			i++
			continue
		case c>>5 == 0x6:
			n, cp = 2, int32(c&0x1F)
		case c>>4 == 0xE:
			n, cp = 3, int32(c&0x0F)
		case c>>3 == 0x1E:
			n, cp = 4, int32(c&0x07)
		default:
			return false
		}
		if i+n > len(b) {
			return false
		}
		for k := 1; k < n; k++ {
			if b[i+k]>>6 != 0x2 {
				return false
			}
			cp = cp<<6 | int32(b[i+k]&0x3F)
		}
		lowest := []int32{0, 0, 0x80, 0x800, 0x10000}[n]
		if cp < lowest || cp > 0x10FFFF || (cp >= 0xD800 && cp <= 0xDFFF) {
			return false
		}
		i += n
	}
	return true
}

func (r *reader) integer(min, max int64) (int64, error) {
	c := r.at()
	if c != '-' && (c < '0' || c > '9') {
		return 0, r.refuse("wrong_type")
	}
	neg := c == '-'
	if neg {
		r.pos++
	}
	d := r.at()
	if d < '0' || d > '9' {
		return 0, r.refuse("malformed")
	}
	var u uint64
	if d == '0' {
		r.pos++
	} else {
		for d = r.at(); d >= '0' && d <= '9'; d = r.at() {
			if u > 922337203685477580 {
				return 0, r.refuse("number_spelling")
			}
			u = u*10 + uint64(d-'0')
			r.pos++
		}
	}
	switch c := r.at(); {
	case c == '.' || c == 'e' || c == 'E' || (c >= '0' && c <= '9'):
		return 0, r.refuse("number_spelling")
	}
	if neg && u == 0 {
		return 0, r.refuse("number_spelling")
	}
	var n int64
	switch {
	case neg && u == 1<<63:
		n = -1 << 63
	case u > 1<<63-1:
		return 0, r.refuse("number_spelling")
	case neg:
		n = -int64(u)
	default:
		n = int64(u)
	}
	if n < min || n > max {
		return 0, r.refuse("number_spelling")
	}
	return n, nil
}

func (r *reader) boolean() (bool, error) {
	switch r.at() {
	case 't':
		return true, r.literal("true")
	case 'f':
		return false, r.literal("false")
	}
	return false, r.refuse("wrong_type")
}

func (r *reader) literal(word string) error {
	if r.pos+len(word) > len(r.buf) || string(r.buf[r.pos:r.pos+len(word)]) != word {
		return r.refuse("malformed")
	}
	r.pos += len(word)
	return nil
}

func (r *reader) strList() ([]string, error) {
	if r.at() != '[' {
		return nil, r.refuse("wrong_type")
	}
	if err := r.enter(); err != nil {
		return nil, err
	}
	r.pos++
	out := []string{}
	r.ws()
	if r.at() != ']' {
		for {
			r.ws()
			s, err := r.str()
			if err != nil {
				return nil, err
			}
			out = append(out, s)
			r.ws()
			if r.at() != ',' {
				break
			}
			r.pos++
		}
	}
	if r.at() != ']' {
		return nil, r.refuse("malformed")
	}
	r.pos++
	r.depth--
	return out, nil
}

func (r *reader) rawMap() (map[string]Raw, error) {
	if r.at() != '{' {
		return nil, r.refuse("wrong_type")
	}
	if err := r.enter(); err != nil {
		return nil, err
	}
	r.pos++
	out := map[string]Raw{}
	r.ws()
	if r.at() != '}' {
		for {
			r.ws()
			if r.at() != '"' {
				return nil, r.refuse("malformed")
			}
			k, err := r.str()
			if err != nil {
				return nil, err
			}
			if _, again := out[k]; again {
				return nil, r.refuse("duplicate_key")
			}
			r.ws()
			if r.at() != ':' {
				return nil, r.refuse("malformed")
			}
			r.pos++
			r.ws()
			v, err := r.rawValue()
			if err != nil {
				return nil, err
			}
			out[k] = v
			r.ws()
			if r.at() != ',' {
				break
			}
			r.pos++
		}
	}
	if r.at() != '}' {
		return nil, r.refuse("malformed")
	}
	r.pos++
	r.depth--
	return out, nil
}

func (r *reader) rawValue() (Raw, error) {
	start := r.pos
	if err := r.skipValue(); err != nil {
		return "", err
	}
	return Raw(r.buf[start:r.pos]), nil
}

func (r *reader) skipValue() error {
	c := r.at()
	switch {
	case c == '"':
		return r.skipString()
	case c == '{' || c == '[':
		return r.skipContainer()
	case c == 't':
		return r.literal("true")
	case c == 'f':
		return r.literal("false")
	case c == 'n':
		return r.literal("null")
	case c == '-' || (c >= '0' && c <= '9'):
		return r.skipNumber()
	}
	return r.refuse("malformed")
}

// An opaque value is validated and carried, never interpreted. Its syntax is
// the record's own — the same string reader, so an escape, a control byte or a
// lone surrogate is judged identically at any depth — and what it is free to
// spell, it keeps: the bytes between these two offsets are what a writer
// re-emits. A number is walked, never converted, so a value no host type holds
// survives the reader that carried it.
func (r *reader) skipString() error {
	_, err := r.str()
	return err
}

func (r *reader) skipNumber() error {
	if r.at() == '-' {
		r.pos++
	}
	switch c := r.at(); {
	case c == '0':
		r.pos++
	case c >= '1' && c <= '9':
		for c := r.at(); c >= '0' && c <= '9'; c = r.at() {
			r.pos++
		}
	default:
		return r.refuse("number_spelling")
	}
	if r.at() == '.' {
		r.pos++
		if err := r.someDigits(); err != nil {
			return err
		}
	}
	if c := r.at(); c == 'e' || c == 'E' {
		r.pos++
		if c := r.at(); c == '+' || c == '-' {
			r.pos++
		}
		if err := r.someDigits(); err != nil {
			return err
		}
	}
	return nil
}

func (r *reader) someDigits() error {
	n := 0
	for c := r.at(); c >= '0' && c <= '9'; c = r.at() {
		r.pos++
		n++
	}
	if n == 0 {
		return r.refuse("number_spelling")
	}
	return nil
}

func (r *reader) skipContainer() error {
	open := r.buf[r.pos]
	shut := byte('}')
	if open == '[' {
		shut = ']'
	}
	if err := r.enter(); err != nil {
		return err
	}
	r.pos++
	r.ws()
	seen := map[string]bool{}
	if r.at() != shut {
		for {
			r.ws()
			if open == '{' {
				if r.at() != '"' {
					return r.refuse("malformed")
				}
				k, err := r.str()
				if err != nil {
					return err
				}
				if seen[k] {
					return r.refuse("duplicate_key")
				}
				seen[k] = true
				r.ws()
				if r.at() != ':' {
					return r.refuse("malformed")
				}
				r.pos++
				r.ws()
			}
			if err := r.skipValue(); err != nil {
				return err
			}
			r.ws()
			if r.at() != ',' {
				break
			}
			r.pos++
		}
	}
	if r.at() != shut {
		return r.refuse("malformed")
	}
	r.pos++
	r.depth--
	return nil
}

func (r *reader) strMap() (map[string]string, error) {
	if r.at() != '{' {
		return nil, r.refuse("wrong_type")
	}
	if err := r.enter(); err != nil {
		return nil, err
	}
	r.pos++
	out := map[string]string{}
	r.ws()
	if r.at() != '}' {
		for {
			r.ws()
			if r.at() != '"' {
				return nil, r.refuse("malformed")
			}
			k, err := r.str()
			if err != nil {
				return nil, err
			}
			if _, again := out[k]; again {
				return nil, r.refuse("duplicate_key")
			}
			r.ws()
			if r.at() != ':' {
				return nil, r.refuse("malformed")
			}
			r.pos++
			r.ws()
			v, err := r.str()
			if err != nil {
				return nil, err
			}
			out[k] = v
			r.ws()
			if r.at() != ',' {
				break
			}
			r.pos++
		}
	}
	if r.at() != '}' {
		return nil, r.refuse("malformed")
	}
	r.pos++
	r.depth--
	return out, nil
}

func decodeList[T any](r *reader, elem func(*reader) (*T, error)) ([]T, error) {
	if r.at() != '[' {
		return nil, r.refuse("wrong_type")
	}
	if err := r.enter(); err != nil {
		return nil, err
	}
	r.pos++
	out := []T{}
	r.ws()
	if r.at() != ']' {
		for {
			r.ws()
			v, err := elem(r)
			if err != nil {
				return nil, err
			}
			out = append(out, *v)
			r.ws()
			if r.at() != ',' {
				break
			}
			r.pos++
		}
	}
	if r.at() != ']' {
		return nil, r.refuse("malformed")
	}
	r.pos++
	r.depth--
	return out, nil
}

func (r *reader) decodeQuestion() (*Question, error) {
	if r.at() != '{' {
		return nil, r.refuse("wrong_type")
	}
	if err := r.enter(); err != nil {
		return nil, err
	}
	r.pos++
	v := &Question{}
	var seen uint32
	r.ws()
	if r.at() != '}' {
		for {
			r.ws()
			if r.at() != '"' {
				return nil, r.refuse("malformed")
			}
			key, err := r.str()
			if err != nil {
				return nil, err
			}
			r.ws()
			if r.at() != ':' {
				return nil, r.refuse("malformed")
			}
			r.pos++
			r.ws()
			switch key {
			case "asker":
				if seen&1 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 1
				x, err := r.str()
				if err != nil {
					return nil, err
				}
				v.Asker = x
			case "key":
				if seen&2 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 2
				x, err := r.str()
				if err != nil {
					return nil, err
				}
				v.Key = x
			case "slots":
				if seen&4 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 4
				x, err := r.strMap()
				if err != nil {
					return nil, err
				}
				v.Slots = x
			default:
				return nil, r.refuse("unknown_field")
			}
			r.ws()
			if r.at() != ',' {
				break
			}
			r.pos++
		}
	}
	if r.at() != '}' {
		return nil, r.refuse("malformed")
	}
	r.pos++
	r.depth--
	if seen&3 != 3 {
		return nil, r.refuse("missing_field")
	}
	return v, nil
}

func (r *reader) decodeRequest() (*Request, error) {
	if r.at() != '{' {
		return nil, r.refuse("wrong_type")
	}
	if err := r.enter(); err != nil {
		return nil, err
	}
	r.pos++
	v := &Request{}
	var seen uint32
	r.ws()
	if r.at() != '}' {
		for {
			r.ws()
			if r.at() != '"' {
				return nil, r.refuse("malformed")
			}
			key, err := r.str()
			if err != nil {
				return nil, err
			}
			r.ws()
			if r.at() != ':' {
				return nil, r.refuse("malformed")
			}
			r.pos++
			r.ws()
			switch key {
			case "op":
				if seen&1 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 1
				x, err := r.str()
				if err != nil {
					return nil, err
				}
				v.Op = x
			case "ask":
				if seen&2 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 2
				x, err := r.decodeQuestion()
				if err != nil {
					return nil, err
				}
				v.Ask = x
			case "wait":
				if seen&4 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 4
				x, err := r.boolean()
				if err != nil {
					return nil, err
				}
				v.Wait = x
			case "id":
				if seen&8 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 8
				x, err := r.str()
				if err != nil {
					return nil, err
				}
				v.Id = x
			case "option":
				if seen&16 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 16
				x, err := r.str()
				if err != nil {
					return nil, err
				}
				v.Option = x
			case "admin":
				if seen&32 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 32
				x, err := r.str()
				if err != nil {
					return nil, err
				}
				v.Admin = x
			default:
				return nil, r.refuse("unknown_field")
			}
			r.ws()
			if r.at() != ',' {
				break
			}
			r.pos++
		}
	}
	if r.at() != '}' {
		return nil, r.refuse("malformed")
	}
	r.pos++
	r.depth--
	if seen&1 != 1 {
		return nil, r.refuse("missing_field")
	}
	return v, nil
}

func (r *reader) decodeAnswer() (*Answer, error) {
	if r.at() != '{' {
		return nil, r.refuse("wrong_type")
	}
	if err := r.enter(); err != nil {
		return nil, err
	}
	r.pos++
	v := &Answer{}
	var seen uint32
	r.ws()
	if r.at() != '}' {
		for {
			r.ws()
			if r.at() != '"' {
				return nil, r.refuse("malformed")
			}
			key, err := r.str()
			if err != nil {
				return nil, err
			}
			r.ws()
			if r.at() != ':' {
				return nil, r.refuse("malformed")
			}
			r.pos++
			r.ws()
			switch key {
			case "id":
				if seen&1 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 1
				x, err := r.str()
				if err != nil {
					return nil, err
				}
				v.Id = x
			case "pending":
				if seen&2 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 2
				x, err := r.boolean()
				if err != nil {
					return nil, err
				}
				v.Pending = x
			case "option":
				if seen&4 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 4
				x, err := r.str()
				if err != nil {
					return nil, err
				}
				v.Option = x
			case "yes":
				if seen&8 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 8
				x, err := r.boolean()
				if err != nil {
					return nil, err
				}
				v.Yes = x
			case "kept":
				if seen&16 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 16
				x, err := r.boolean()
				if err != nil {
					return nil, err
				}
				v.Kept = x
			default:
				return nil, r.refuse("unknown_field")
			}
			r.ws()
			if r.at() != ',' {
				break
			}
			r.pos++
		}
	}
	if r.at() != '}' {
		return nil, r.refuse("malformed")
	}
	r.pos++
	r.depth--
	if seen&1 != 1 {
		return nil, r.refuse("missing_field")
	}
	return v, nil
}

func (r *reader) decodeRecordMetadata() (*RecordMetadata, error) {
	if r.at() != '{' {
		return nil, r.refuse("wrong_type")
	}
	if err := r.enter(); err != nil {
		return nil, err
	}
	r.pos++
	v := &RecordMetadata{}
	var seen uint32
	r.ws()
	if r.at() != '}' {
		for {
			r.ws()
			if r.at() != '"' {
				return nil, r.refuse("malformed")
			}
			key, err := r.str()
			if err != nil {
				return nil, err
			}
			r.ws()
			if r.at() != ':' {
				return nil, r.refuse("malformed")
			}
			r.pos++
			r.ws()
			switch key {
			case "id":
				if seen&1 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 1
				x, err := r.str()
				if err != nil {
					return nil, err
				}
				v.Id = x
			case "asker":
				if seen&2 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 2
				x, err := r.str()
				if err != nil {
					return nil, err
				}
				v.Asker = x
			case "key":
				if seen&4 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 4
				x, err := r.str()
				if err != nil {
					return nil, err
				}
				v.Key = x
			case "about":
				if seen&8 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 8
				x, err := r.str()
				if err != nil {
					return nil, err
				}
				v.About = x
			case "text":
				if seen&16 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 16
				x, err := r.str()
				if err != nil {
					return nil, err
				}
				v.Text = x
			case "options":
				if seen&32 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 32
				x, err := r.strList()
				if err != nil {
					return nil, err
				}
				v.Options = x
			case "asked":
				if seen&64 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 64
				x, err := r.str()
				if err != nil {
					return nil, err
				}
				v.Asked = x
			case "option":
				if seen&128 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 128
				x, err := r.str()
				if err != nil {
					return nil, err
				}
				v.Option = x
			case "answered":
				if seen&256 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 256
				x, err := r.str()
				if err != nil {
					return nil, err
				}
				v.Answered = x
			case "kept":
				if seen&512 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 512
				x, err := r.boolean()
				if err != nil {
					return nil, err
				}
				v.Kept = x
			case "yes":
				if seen&1024 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 1024
				x, err := r.boolean()
				if err != nil {
					return nil, err
				}
				v.Yes = x
			default:
				return nil, r.refuse("unknown_field")
			}
			r.ws()
			if r.at() != ',' {
				break
			}
			r.pos++
		}
	}
	if r.at() != '}' {
		return nil, r.refuse("malformed")
	}
	r.pos++
	r.depth--
	if seen&119 != 119 {
		return nil, r.refuse("missing_field")
	}
	return v, nil
}

func (r *reader) decodeResponseMetadata() (*ResponseMetadata, error) {
	if r.at() != '{' {
		return nil, r.refuse("wrong_type")
	}
	if err := r.enter(); err != nil {
		return nil, err
	}
	r.pos++
	v := &ResponseMetadata{}
	var seen uint32
	r.ws()
	if r.at() != '}' {
		for {
			r.ws()
			if r.at() != '"' {
				return nil, r.refuse("malformed")
			}
			key, err := r.str()
			if err != nil {
				return nil, err
			}
			r.ws()
			if r.at() != ':' {
				return nil, r.refuse("malformed")
			}
			r.pos++
			r.ws()
			switch key {
			case "code":
				if seen&1 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 1
				x, err := r.str()
				if err != nil {
					return nil, err
				}
				v.Code = x
			case "error":
				if seen&2 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 2
				x, err := r.str()
				if err != nil {
					return nil, err
				}
				v.Error = x
			case "answer":
				if seen&4 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 4
				x, err := r.decodeAnswer()
				if err != nil {
					return nil, err
				}
				v.Answer = x
			case "records":
				if seen&8 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 8
				x, err := decodeList(r, (*reader).decodeRecordMetadata)
				if err != nil {
					return nil, err
				}
				v.Records = x
			default:
				return nil, r.refuse("unknown_field")
			}
			r.ws()
			if r.at() != ',' {
				break
			}
			r.pos++
		}
	}
	if r.at() != '}' {
		return nil, r.refuse("malformed")
	}
	r.pos++
	r.depth--
	return v, nil
}

func (r *reader) decodeApplicationQuestion() (*ApplicationQuestion, error) {
	if r.at() != '{' {
		return nil, r.refuse("wrong_type")
	}
	if err := r.enter(); err != nil {
		return nil, err
	}
	r.pos++
	v := &ApplicationQuestion{}
	var seen uint32
	r.ws()
	if r.at() != '}' {
		for {
			r.ws()
			if r.at() != '"' {
				return nil, r.refuse("malformed")
			}
			key, err := r.str()
			if err != nil {
				return nil, err
			}
			r.ws()
			if r.at() != ':' {
				return nil, r.refuse("malformed")
			}
			r.pos++
			r.ws()
			switch key {
			case "request_key":
				if seen&1 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 1
				x, err := r.str()
				if err != nil {
					return nil, err
				}
				v.RequestKey = x
			case "key":
				if seen&2 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 2
				x, err := r.str()
				if err != nil {
					return nil, err
				}
				v.Key = x
			case "slots":
				if seen&4 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 4
				x, err := r.strMap()
				if err != nil {
					return nil, err
				}
				v.Slots = x
			default:
				return nil, r.refuse("unknown_field")
			}
			r.ws()
			if r.at() != ',' {
				break
			}
			r.pos++
		}
	}
	if r.at() != '}' {
		return nil, r.refuse("malformed")
	}
	r.pos++
	r.depth--
	if seen&7 != 7 {
		return nil, r.refuse("missing_field")
	}
	return v, nil
}

func (r *reader) decodeQuestionObservation() (*QuestionObservation, error) {
	if r.at() != '{' {
		return nil, r.refuse("wrong_type")
	}
	if err := r.enter(); err != nil {
		return nil, err
	}
	r.pos++
	v := &QuestionObservation{}
	var seen uint32
	r.ws()
	if r.at() != '}' {
		for {
			r.ws()
			if r.at() != '"' {
				return nil, r.refuse("malformed")
			}
			key, err := r.str()
			if err != nil {
				return nil, err
			}
			r.ws()
			if r.at() != ':' {
				return nil, r.refuse("malformed")
			}
			r.pos++
			r.ws()
			switch key {
			case "outcome":
				if seen&1 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 1
				x, err := r.str()
				if err != nil {
					return nil, err
				}
				v.Outcome = x
			case "answer":
				if seen&2 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 2
				x, err := r.decodeAnswer()
				if err != nil {
					return nil, err
				}
				v.Answer = x
			default:
				return nil, r.refuse("unknown_field")
			}
			r.ws()
			if r.at() != ',' {
				break
			}
			r.pos++
		}
	}
	if r.at() != '}' {
		return nil, r.refuse("malformed")
	}
	r.pos++
	r.depth--
	if seen&1 != 1 {
		return nil, r.refuse("missing_field")
	}
	if v.Outcome != "pending" && v.Outcome != "answered" && v.Outcome != "unknown" && v.Outcome != "gone" && v.Outcome != "invalid" && v.Outcome != "conflict" && v.Outcome != "forbidden" && v.Outcome != "unavailable" {
		return nil, r.refuse("bad_enum")
	}
	return v, nil
}

func (r *reader) decodeOperatorPage() (*OperatorPage, error) {
	if r.at() != '{' {
		return nil, r.refuse("wrong_type")
	}
	if err := r.enter(); err != nil {
		return nil, err
	}
	r.pos++
	v := &OperatorPage{}
	var seen uint32
	r.ws()
	if r.at() != '}' {
		for {
			r.ws()
			if r.at() != '"' {
				return nil, r.refuse("malformed")
			}
			key, err := r.str()
			if err != nil {
				return nil, err
			}
			r.ws()
			if r.at() != ':' {
				return nil, r.refuse("malformed")
			}
			r.pos++
			r.ws()
			switch key {
			case "outcome":
				if seen&1 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 1
				x, err := r.str()
				if err != nil {
					return nil, err
				}
				v.Outcome = x
			case "records":
				if seen&2 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 2
				x, err := decodeList(r, (*reader).decodeRecordMetadata)
				if err != nil {
					return nil, err
				}
				v.Records = x
			case "next":
				if seen&4 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 4
				x, err := r.str()
				if err != nil {
					return nil, err
				}
				v.Next = x
			case "complete":
				if seen&8 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 8
				x, err := r.boolean()
				if err != nil {
					return nil, err
				}
				v.Complete = x
			default:
				return nil, r.refuse("unknown_field")
			}
			r.ws()
			if r.at() != ',' {
				break
			}
			r.pos++
		}
	}
	if r.at() != '}' {
		return nil, r.refuse("malformed")
	}
	r.pos++
	r.depth--
	if seen&15 != 15 {
		return nil, r.refuse("missing_field")
	}
	if v.Outcome != "page" && v.Outcome != "gap" && v.Outcome != "invalid" && v.Outcome != "forbidden" && v.Outcome != "unavailable" {
		return nil, r.refuse("bad_enum")
	}
	return v, nil
}

func (r *reader) decodeOperatorDecision() (*OperatorDecision, error) {
	if r.at() != '{' {
		return nil, r.refuse("wrong_type")
	}
	if err := r.enter(); err != nil {
		return nil, err
	}
	r.pos++
	v := &OperatorDecision{}
	var seen uint32
	r.ws()
	if r.at() != '}' {
		for {
			r.ws()
			if r.at() != '"' {
				return nil, r.refuse("malformed")
			}
			key, err := r.str()
			if err != nil {
				return nil, err
			}
			r.ws()
			if r.at() != ':' {
				return nil, r.refuse("malformed")
			}
			r.pos++
			r.ws()
			switch key {
			case "outcome":
				if seen&1 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 1
				x, err := r.str()
				if err != nil {
					return nil, err
				}
				v.Outcome = x
			case "record":
				if seen&2 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 2
				x, err := r.decodeRecordMetadata()
				if err != nil {
					return nil, err
				}
				v.Record = x
			default:
				return nil, r.refuse("unknown_field")
			}
			r.ws()
			if r.at() != ',' {
				break
			}
			r.pos++
		}
	}
	if r.at() != '}' {
		return nil, r.refuse("malformed")
	}
	r.pos++
	r.depth--
	if seen&1 != 1 {
		return nil, r.refuse("missing_field")
	}
	if v.Outcome != "answered" && v.Outcome != "conflict" && v.Outcome != "unknown" && v.Outcome != "invalid" && v.Outcome != "forbidden" && v.Outcome != "unavailable" {
		return nil, r.refuse("bad_enum")
	}
	return v, nil
}

func (r *reader) decodeOAQuestionApplicationAskArguments() (*OAQuestionApplicationAskArguments, error) {
	if r.at() != '{' {
		return nil, r.refuse("wrong_type")
	}
	if err := r.enter(); err != nil {
		return nil, err
	}
	r.pos++
	v := &OAQuestionApplicationAskArguments{}
	var seen uint32
	r.ws()
	if r.at() != '}' {
		for {
			r.ws()
			if r.at() != '"' {
				return nil, r.refuse("malformed")
			}
			key, err := r.str()
			if err != nil {
				return nil, err
			}
			r.ws()
			if r.at() != ':' {
				return nil, r.refuse("malformed")
			}
			r.pos++
			r.ws()
			switch key {
			case "question":
				if seen&1 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 1
				x, err := r.decodeApplicationQuestion()
				if err != nil {
					return nil, err
				}
				v.Question = *x
			default:
				return nil, r.refuse("unknown_field")
			}
			r.ws()
			if r.at() != ',' {
				break
			}
			r.pos++
		}
	}
	if r.at() != '}' {
		return nil, r.refuse("malformed")
	}
	r.pos++
	r.depth--
	if seen&1 != 1 {
		return nil, r.refuse("missing_field")
	}
	return v, nil
}

func (r *reader) decodeOAQuestionApplicationObserveArguments() (*OAQuestionApplicationObserveArguments, error) {
	if r.at() != '{' {
		return nil, r.refuse("wrong_type")
	}
	if err := r.enter(); err != nil {
		return nil, err
	}
	r.pos++
	v := &OAQuestionApplicationObserveArguments{}
	var seen uint32
	r.ws()
	if r.at() != '}' {
		for {
			r.ws()
			if r.at() != '"' {
				return nil, r.refuse("malformed")
			}
			key, err := r.str()
			if err != nil {
				return nil, err
			}
			r.ws()
			if r.at() != ':' {
				return nil, r.refuse("malformed")
			}
			r.pos++
			r.ws()
			switch key {
			case "request_key":
				if seen&1 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 1
				x, err := r.str()
				if err != nil {
					return nil, err
				}
				v.RequestKey = x
			case "wait_ms":
				if seen&2 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 2
				x, err := r.integer(-9223372036854775808, 9223372036854775807)
				if err != nil {
					return nil, err
				}
				v.WaitMs = x
			default:
				return nil, r.refuse("unknown_field")
			}
			r.ws()
			if r.at() != ',' {
				break
			}
			r.pos++
		}
	}
	if r.at() != '}' {
		return nil, r.refuse("malformed")
	}
	r.pos++
	r.depth--
	if seen&3 != 3 {
		return nil, r.refuse("missing_field")
	}
	return v, nil
}

func (r *reader) decodeOAQuestionOperatorListQuestionsArguments() (*OAQuestionOperatorListQuestionsArguments, error) {
	if r.at() != '{' {
		return nil, r.refuse("wrong_type")
	}
	if err := r.enter(); err != nil {
		return nil, err
	}
	r.pos++
	v := &OAQuestionOperatorListQuestionsArguments{}
	var seen uint32
	r.ws()
	if r.at() != '}' {
		for {
			r.ws()
			if r.at() != '"' {
				return nil, r.refuse("malformed")
			}
			key, err := r.str()
			if err != nil {
				return nil, err
			}
			r.ws()
			if r.at() != ':' {
				return nil, r.refuse("malformed")
			}
			r.pos++
			r.ws()
			switch key {
			case "cursor":
				if seen&1 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 1
				x, err := r.str()
				if err != nil {
					return nil, err
				}
				v.Cursor = x
			case "limit":
				if seen&2 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 2
				x, err := r.integer(-9223372036854775808, 9223372036854775807)
				if err != nil {
					return nil, err
				}
				v.Limit = x
			default:
				return nil, r.refuse("unknown_field")
			}
			r.ws()
			if r.at() != ',' {
				break
			}
			r.pos++
		}
	}
	if r.at() != '}' {
		return nil, r.refuse("malformed")
	}
	r.pos++
	r.depth--
	if seen&3 != 3 {
		return nil, r.refuse("missing_field")
	}
	return v, nil
}

func (r *reader) decodeOAQuestionOperatorAnswerQuestionArguments() (*OAQuestionOperatorAnswerQuestionArguments, error) {
	if r.at() != '{' {
		return nil, r.refuse("wrong_type")
	}
	if err := r.enter(); err != nil {
		return nil, err
	}
	r.pos++
	v := &OAQuestionOperatorAnswerQuestionArguments{}
	var seen uint32
	r.ws()
	if r.at() != '}' {
		for {
			r.ws()
			if r.at() != '"' {
				return nil, r.refuse("malformed")
			}
			key, err := r.str()
			if err != nil {
				return nil, err
			}
			r.ws()
			if r.at() != ':' {
				return nil, r.refuse("malformed")
			}
			r.pos++
			r.ws()
			switch key {
			case "id":
				if seen&1 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 1
				x, err := r.str()
				if err != nil {
					return nil, err
				}
				v.Id = x
			case "option":
				if seen&2 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 2
				x, err := r.str()
				if err != nil {
					return nil, err
				}
				v.Option = x
			default:
				return nil, r.refuse("unknown_field")
			}
			r.ws()
			if r.at() != ',' {
				break
			}
			r.pos++
		}
	}
	if r.at() != '}' {
		return nil, r.refuse("malformed")
	}
	r.pos++
	r.depth--
	if seen&3 != 3 {
		return nil, r.refuse("missing_field")
	}
	return v, nil
}

func (r *reader) decodeOAServiceFrame() (*OAServiceFrame, error) {
	if r.at() != '{' {
		return nil, r.refuse("wrong_type")
	}
	if err := r.enter(); err != nil {
		return nil, err
	}
	r.pos++
	v := &OAServiceFrame{}
	var seen uint32
	r.ws()
	if r.at() != '}' {
		for {
			r.ws()
			if r.at() != '"' {
				return nil, r.refuse("malformed")
			}
			key, err := r.str()
			if err != nil {
				return nil, err
			}
			r.ws()
			if r.at() != ':' {
				return nil, r.refuse("malformed")
			}
			r.pos++
			r.ws()
			switch key {
			case "version":
				if seen&1 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 1
				x, err := r.integer(-2147483648, 2147483647)
				if err != nil {
					return nil, err
				}
				v.Version = int32(x)
			case "service":
				if seen&2 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 2
				x, err := r.str()
				if err != nil {
					return nil, err
				}
				v.Service = x
			case "method":
				if seen&4 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 4
				x, err := r.str()
				if err != nil {
					return nil, err
				}
				v.Method = x
			case "arguments":
				if seen&8 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 8
				x, err := r.rawValue()
				if err != nil {
					return nil, err
				}
				v.Arguments = x
			default:
				return nil, r.refuse("unknown_field")
			}
			r.ws()
			if r.at() != ',' {
				break
			}
			r.pos++
		}
	}
	if r.at() != '}' {
		return nil, r.refuse("malformed")
	}
	r.pos++
	r.depth--
	if seen&15 != 15 {
		return nil, r.refuse("missing_field")
	}
	return v, nil
}

func (r *reader) decodeOAServiceReply() (*OAServiceReply, error) {
	if r.at() != '{' {
		return nil, r.refuse("wrong_type")
	}
	if err := r.enter(); err != nil {
		return nil, err
	}
	r.pos++
	v := &OAServiceReply{}
	var seen uint32
	r.ws()
	if r.at() != '}' {
		for {
			r.ws()
			if r.at() != '"' {
				return nil, r.refuse("malformed")
			}
			key, err := r.str()
			if err != nil {
				return nil, err
			}
			r.ws()
			if r.at() != ':' {
				return nil, r.refuse("malformed")
			}
			r.pos++
			r.ws()
			switch key {
			case "version":
				if seen&1 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 1
				x, err := r.integer(-2147483648, 2147483647)
				if err != nil {
					return nil, err
				}
				v.Version = int32(x)
			case "service":
				if seen&2 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 2
				x, err := r.str()
				if err != nil {
					return nil, err
				}
				v.Service = x
			case "method":
				if seen&4 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 4
				x, err := r.str()
				if err != nil {
					return nil, err
				}
				v.Method = x
			case "ok":
				if seen&8 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 8
				x, err := r.boolean()
				if err != nil {
					return nil, err
				}
				v.Ok = x
			case "payload":
				if seen&16 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 16
				x, err := r.rawValue()
				if err != nil {
					return nil, err
				}
				v.Payload = x
			default:
				return nil, r.refuse("unknown_field")
			}
			r.ws()
			if r.at() != ',' {
				break
			}
			r.pos++
		}
	}
	if r.at() != '}' {
		return nil, r.refuse("malformed")
	}
	r.pos++
	r.depth--
	if seen&31 != 31 {
		return nil, r.refuse("missing_field")
	}
	return v, nil
}

func (r *reader) decodeOAServiceError() (*OAServiceError, error) {
	if r.at() != '{' {
		return nil, r.refuse("wrong_type")
	}
	if err := r.enter(); err != nil {
		return nil, err
	}
	r.pos++
	v := &OAServiceError{}
	var seen uint32
	r.ws()
	if r.at() != '}' {
		for {
			r.ws()
			if r.at() != '"' {
				return nil, r.refuse("malformed")
			}
			key, err := r.str()
			if err != nil {
				return nil, err
			}
			r.ws()
			if r.at() != ':' {
				return nil, r.refuse("malformed")
			}
			r.pos++
			r.ws()
			switch key {
			case "code":
				if seen&1 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 1
				x, err := r.str()
				if err != nil {
					return nil, err
				}
				v.Code = x
			case "message":
				if seen&2 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 2
				x, err := r.str()
				if err != nil {
					return nil, err
				}
				v.Message = x
			default:
				return nil, r.refuse("unknown_field")
			}
			r.ws()
			if r.at() != ',' {
				break
			}
			r.pos++
		}
	}
	if r.at() != '}' {
		return nil, r.refuse("malformed")
	}
	r.pos++
	r.depth--
	if seen&3 != 3 {
		return nil, r.refuse("missing_field")
	}
	return v, nil
}

func (r *reader) decodeOAQuestionApplicationAskResult() (*OAQuestionApplicationAskResult, error) {
	if r.at() != '{' {
		return nil, r.refuse("wrong_type")
	}
	if err := r.enter(); err != nil {
		return nil, err
	}
	r.pos++
	v := &OAQuestionApplicationAskResult{}
	var seen uint32
	r.ws()
	if r.at() != '}' {
		for {
			r.ws()
			if r.at() != '"' {
				return nil, r.refuse("malformed")
			}
			key, err := r.str()
			if err != nil {
				return nil, err
			}
			r.ws()
			if r.at() != ':' {
				return nil, r.refuse("malformed")
			}
			r.pos++
			r.ws()
			switch key {
			case "value":
				if seen&1 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 1
				x, err := r.decodeQuestionObservation()
				if err != nil {
					return nil, err
				}
				v.Value = *x
			default:
				return nil, r.refuse("unknown_field")
			}
			r.ws()
			if r.at() != ',' {
				break
			}
			r.pos++
		}
	}
	if r.at() != '}' {
		return nil, r.refuse("malformed")
	}
	r.pos++
	r.depth--
	if seen&1 != 1 {
		return nil, r.refuse("missing_field")
	}
	return v, nil
}

func (r *reader) decodeOAQuestionApplicationObserveResult() (*OAQuestionApplicationObserveResult, error) {
	if r.at() != '{' {
		return nil, r.refuse("wrong_type")
	}
	if err := r.enter(); err != nil {
		return nil, err
	}
	r.pos++
	v := &OAQuestionApplicationObserveResult{}
	var seen uint32
	r.ws()
	if r.at() != '}' {
		for {
			r.ws()
			if r.at() != '"' {
				return nil, r.refuse("malformed")
			}
			key, err := r.str()
			if err != nil {
				return nil, err
			}
			r.ws()
			if r.at() != ':' {
				return nil, r.refuse("malformed")
			}
			r.pos++
			r.ws()
			switch key {
			case "value":
				if seen&1 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 1
				x, err := r.decodeQuestionObservation()
				if err != nil {
					return nil, err
				}
				v.Value = *x
			default:
				return nil, r.refuse("unknown_field")
			}
			r.ws()
			if r.at() != ',' {
				break
			}
			r.pos++
		}
	}
	if r.at() != '}' {
		return nil, r.refuse("malformed")
	}
	r.pos++
	r.depth--
	if seen&1 != 1 {
		return nil, r.refuse("missing_field")
	}
	return v, nil
}

func (r *reader) decodeOAQuestionOperatorListQuestionsResult() (*OAQuestionOperatorListQuestionsResult, error) {
	if r.at() != '{' {
		return nil, r.refuse("wrong_type")
	}
	if err := r.enter(); err != nil {
		return nil, err
	}
	r.pos++
	v := &OAQuestionOperatorListQuestionsResult{}
	var seen uint32
	r.ws()
	if r.at() != '}' {
		for {
			r.ws()
			if r.at() != '"' {
				return nil, r.refuse("malformed")
			}
			key, err := r.str()
			if err != nil {
				return nil, err
			}
			r.ws()
			if r.at() != ':' {
				return nil, r.refuse("malformed")
			}
			r.pos++
			r.ws()
			switch key {
			case "value":
				if seen&1 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 1
				x, err := r.decodeOperatorPage()
				if err != nil {
					return nil, err
				}
				v.Value = *x
			default:
				return nil, r.refuse("unknown_field")
			}
			r.ws()
			if r.at() != ',' {
				break
			}
			r.pos++
		}
	}
	if r.at() != '}' {
		return nil, r.refuse("malformed")
	}
	r.pos++
	r.depth--
	if seen&1 != 1 {
		return nil, r.refuse("missing_field")
	}
	return v, nil
}

func (r *reader) decodeOAQuestionOperatorAnswerQuestionResult() (*OAQuestionOperatorAnswerQuestionResult, error) {
	if r.at() != '{' {
		return nil, r.refuse("wrong_type")
	}
	if err := r.enter(); err != nil {
		return nil, err
	}
	r.pos++
	v := &OAQuestionOperatorAnswerQuestionResult{}
	var seen uint32
	r.ws()
	if r.at() != '}' {
		for {
			r.ws()
			if r.at() != '"' {
				return nil, r.refuse("malformed")
			}
			key, err := r.str()
			if err != nil {
				return nil, err
			}
			r.ws()
			if r.at() != ':' {
				return nil, r.refuse("malformed")
			}
			r.pos++
			r.ws()
			switch key {
			case "value":
				if seen&1 != 0 {
					return nil, r.refuse("duplicate_field")
				}
				seen |= 1
				x, err := r.decodeOperatorDecision()
				if err != nil {
					return nil, err
				}
				v.Value = *x
			default:
				return nil, r.refuse("unknown_field")
			}
			r.ws()
			if r.at() != ',' {
				break
			}
			r.pos++
		}
	}
	if r.at() != '}' {
		return nil, r.refuse("malformed")
	}
	r.pos++
	r.depth--
	if seen&1 != 1 {
		return nil, r.refuse("missing_field")
	}
	return v, nil
}

func Decode(in []byte) (*Request, error) {
	r := &reader{buf: in}
	r.ws()
	v, err := r.decodeRequest()
	if err != nil {
		return nil, err
	}
	r.ws()
	if r.pos < len(r.buf) {
		return nil, r.refuse("trailing_bytes")
	}
	return v, nil
}

// Refusals is in the order two of them are chosen between.

var Refusals = []string{"malformed", "bad_string", "number_spelling", "wrong_type", "depth_exceeded", "duplicate_key", "duplicate_field", "unknown_field", "missing_field", "bad_enum", "trailing_bytes"}

func RefusalRank(word string) int {
	for i, w := range Refusals {
		if w == word {
			return i
		}
	}
	return -1
}

// A transport consumes or copies frames before returning. WriteFrame is one-way.
type FrameWriter interface{ WriteFrame([]byte) error }
type DispatchError string

func (e DispatchError) Error() string { return string(e) }
func servicePayload(frame []byte) (*OAServiceFrame, error) {
	r := &reader{buf: frame}
	r.ws()
	v, err := r.decodeOAServiceFrame()
	if err != nil {
		return nil, err
	}
	r.ws()
	if r.pos != len(r.buf) {
		return nil, r.refuse("trailing_bytes")
	}
	if v.Version != 1 {
		return nil, DispatchError("unknown_version")
	}
	return v, nil
}

// ServiceName validates the request envelope and version for routing. The chosen
// generated dispatcher validates service, method and typed arguments before use.
func ServiceName(frame []byte) (string, error) {
	v, err := servicePayload(frame)
	if err != nil {
		return "", err
	}
	return v.Service, nil
}

// ExchangeFrame returns the response associated with this call. Correlation,
// serialization and deadlines belong to the transport, not this codec.
type FrameExchanger interface{ ExchangeFrame([]byte) ([]byte, error) }
type ServiceError struct {
	Code    string
	Message string
}

func (e *ServiceError) Error() string {
	if e.Message != "" {
		return e.Message
	}
	return e.Code
}
func serviceResponse(frame []byte, service, method string) (Raw, error) {
	r := &reader{buf: frame}
	r.ws()
	v, err := r.decodeOAServiceReply()
	if err != nil {
		return "", err
	}
	r.ws()
	if r.pos != len(r.buf) {
		return "", r.refuse("trailing_bytes")
	}
	if v.Version != 1 {
		return "", DispatchError("unknown_version")
	}
	if v.Service != service || v.Method != method {
		return "", DispatchError("mismatched_response")
	}
	if !v.Ok {
		r = &reader{buf: []byte(v.Payload), depth: 1}
		r.ws()
		e, err := r.decodeOAServiceError()
		if err != nil {
			return "", err
		}
		r.ws()
		if r.pos != len(r.buf) {
			return "", r.refuse("trailing_bytes")
		}
		if e.Code == "" {
			return "", DispatchError("invalid_error")
		}
		return "", &ServiceError{Code: e.Code, Message: e.Message}
	}
	return v.Payload, nil
}
func serviceReply(v *OAServiceFrame, payload Raw, err error) (frame []byte, outErr error) {
	defer func() {
		if p := recover(); p != nil {
			if e, ok := p.(*Refusal); ok {
				frame = nil
				outErr = e
			} else {
				panic(p)
			}
		}
	}()
	reply := OAServiceReply{Version: 1, Service: v.Service, Method: v.Method, Ok: err == nil, Payload: payload}
	if err != nil {
		e := OAServiceError{Code: "handler_error", Message: "handler failed"}
		switch x := err.(type) {
		case *ServiceError:
			if x.Code != "" {
				e.Code = x.Code
			}
			e.Message = x.Message
		case DispatchError:
			e.Code = string(x)
			e.Message = ""
		case *Refusal:
			e.Code = x.Word
			e.Message = ""
		}
		reply.Payload = Raw(encOAServiceError(nil, &e, 1))
	}
	frame = encOAServiceReply(nil, &reply, 0)
	// Validate even error diagnostics before making them visible on the wire.
	r := &reader{buf: frame}
	r.ws()
	if _, e := r.decodeOAServiceReply(); e != nil {
		return nil, e
	}
	return frame, nil
}

type QuestionApplication interface {
	Ask(ApplicationQuestion) (QuestionObservation, error)
	Observe(string, int64) (QuestionObservation, error)
}
type QuestionApplicationTransport interface {
	FrameExchanger
}
type QuestionApplicationClient struct{ transport QuestionApplicationTransport }

func NewQuestionApplicationClient(t QuestionApplicationTransport) *QuestionApplicationClient {
	return &QuestionApplicationClient{transport: t}
}

type QuestionApplicationDispatcher struct{ Handler QuestionApplication }

func (c *QuestionApplicationClient) Ask(arg0 ApplicationQuestion) (result QuestionObservation, err error) {
	defer func() {
		if p := recover(); p != nil {
			if e, ok := p.(*Refusal); ok {
				err = e
			} else {
				panic(p)
			}
		}
	}()
	args := OAQuestionApplicationAskArguments{Question: arg0}
	v := OAServiceFrame{Version: 1, Service: "abstraction.asks/application@1", Method: "Ask", Arguments: Raw(encOAQuestionApplicationAskArguments(nil, &args, 1))}
	frame := encOAServiceFrame(nil, &v, 0)
	if _, err = servicePayload(frame); err != nil {
		return
	}
	var response []byte
	response, err = c.transport.ExchangeFrame(frame)
	if err != nil {
		return
	}
	var payload Raw
	payload, err = serviceResponse(response, v.Service, v.Method)
	if err != nil {
		return
	}
	r := &reader{buf: []byte(payload), depth: 1}
	r.ws()
	var decoded *OAQuestionApplicationAskResult
	decoded, err = r.decodeOAQuestionApplicationAskResult()
	if err != nil {
		return
	}
	_ = decoded
	r.ws()
	if r.pos != len(r.buf) {
		err = r.refuse("trailing_bytes")
		return
	}
	result = decoded.Value
	return
}
func (c *QuestionApplicationClient) Observe(arg0 string, arg1 int64) (result QuestionObservation, err error) {
	defer func() {
		if p := recover(); p != nil {
			if e, ok := p.(*Refusal); ok {
				err = e
			} else {
				panic(p)
			}
		}
	}()
	args := OAQuestionApplicationObserveArguments{RequestKey: arg0, WaitMs: arg1}
	v := OAServiceFrame{Version: 1, Service: "abstraction.asks/application@1", Method: "Observe", Arguments: Raw(encOAQuestionApplicationObserveArguments(nil, &args, 1))}
	frame := encOAServiceFrame(nil, &v, 0)
	if _, err = servicePayload(frame); err != nil {
		return
	}
	var response []byte
	response, err = c.transport.ExchangeFrame(frame)
	if err != nil {
		return
	}
	var payload Raw
	payload, err = serviceResponse(response, v.Service, v.Method)
	if err != nil {
		return
	}
	r := &reader{buf: []byte(payload), depth: 1}
	r.ws()
	var decoded *OAQuestionApplicationObserveResult
	decoded, err = r.decodeOAQuestionApplicationObserveResult()
	if err != nil {
		return
	}
	_ = decoded
	r.ws()
	if r.pos != len(r.buf) {
		err = r.refuse("trailing_bytes")
		return
	}
	result = decoded.Value
	return
}
func (d *QuestionApplicationDispatcher) WriteFrame(frame []byte) error {
	v, err := servicePayload(frame)
	if err != nil {
		return err
	}
	if v.Service != "abstraction.asks/application@1" {
		return DispatchError("unknown_service")
	}
	switch v.Method {
	case "Ask":
		return DispatchError("wrong_mode")
	case "Observe":
		return DispatchError("wrong_mode")
	default:
		return DispatchError("unknown_method")
	}
}
func (d *QuestionApplicationDispatcher) ExchangeFrame(frame []byte) ([]byte, error) {
	v, err := servicePayload(frame)
	if err != nil {
		return nil, err
	}
	if v.Service != "abstraction.asks/application@1" {
		return serviceReply(v, "", DispatchError("unknown_service"))
	}
	switch v.Method {
	case "Ask":
		r := &reader{buf: []byte(v.Arguments), depth: 1}
		r.ws()
		args, err := r.decodeOAQuestionApplicationAskArguments()
		if err != nil {
			return serviceReply(v, "", err)
		}
		r.ws()
		if r.pos != len(r.buf) {
			return serviceReply(v, "", r.refuse("trailing_bytes"))
		}
		payload, err := d.invokeAsk(args)
		return serviceReply(v, payload, err)
	case "Observe":
		r := &reader{buf: []byte(v.Arguments), depth: 1}
		r.ws()
		args, err := r.decodeOAQuestionApplicationObserveArguments()
		if err != nil {
			return serviceReply(v, "", err)
		}
		r.ws()
		if r.pos != len(r.buf) {
			return serviceReply(v, "", r.refuse("trailing_bytes"))
		}
		payload, err := d.invokeObserve(args)
		return serviceReply(v, payload, err)
	default:
		return serviceReply(v, "", DispatchError("unknown_method"))
	}
}
func (d *QuestionApplicationDispatcher) invokeAsk(args *OAQuestionApplicationAskArguments) (payload Raw, err error) {
	defer func() {
		if p := recover(); p != nil {
			payload = ""
			if _, ok := p.(*Refusal); ok {
				err = &ServiceError{Code: "invalid_result"}
			} else {
				err = &ServiceError{Code: "handler_error", Message: "handler failed"}
			}
		}
	}()
	var result QuestionObservation
	result, err = d.Handler.Ask(args.Question)
	if err != nil {
		return
	}
	value := OAQuestionApplicationAskResult{Value: result}
	payload = Raw(encOAQuestionApplicationAskResult(nil, &value, 1))
	r := &reader{buf: []byte(payload), depth: 1}
	r.ws()
	if _, e := r.decodeOAQuestionApplicationAskResult(); e != nil {
		payload = ""
		err = &ServiceError{Code: "invalid_result"}
		return
	}
	r.ws()
	if r.pos != len(r.buf) {
		payload = ""
		err = &ServiceError{Code: "invalid_result"}
	}
	return
}
func (d *QuestionApplicationDispatcher) invokeObserve(args *OAQuestionApplicationObserveArguments) (payload Raw, err error) {
	defer func() {
		if p := recover(); p != nil {
			payload = ""
			if _, ok := p.(*Refusal); ok {
				err = &ServiceError{Code: "invalid_result"}
			} else {
				err = &ServiceError{Code: "handler_error", Message: "handler failed"}
			}
		}
	}()
	var result QuestionObservation
	result, err = d.Handler.Observe(args.RequestKey, args.WaitMs)
	if err != nil {
		return
	}
	value := OAQuestionApplicationObserveResult{Value: result}
	payload = Raw(encOAQuestionApplicationObserveResult(nil, &value, 1))
	r := &reader{buf: []byte(payload), depth: 1}
	r.ws()
	if _, e := r.decodeOAQuestionApplicationObserveResult(); e != nil {
		payload = ""
		err = &ServiceError{Code: "invalid_result"}
		return
	}
	r.ws()
	if r.pos != len(r.buf) {
		payload = ""
		err = &ServiceError{Code: "invalid_result"}
	}
	return
}

type QuestionOperator interface {
	ListQuestions(string, int64) (OperatorPage, error)
	AnswerQuestion(string, string) (OperatorDecision, error)
}
type QuestionOperatorTransport interface {
	FrameExchanger
}
type QuestionOperatorClient struct{ transport QuestionOperatorTransport }

func NewQuestionOperatorClient(t QuestionOperatorTransport) *QuestionOperatorClient {
	return &QuestionOperatorClient{transport: t}
}

type QuestionOperatorDispatcher struct{ Handler QuestionOperator }

func (c *QuestionOperatorClient) ListQuestions(arg0 string, arg1 int64) (result OperatorPage, err error) {
	defer func() {
		if p := recover(); p != nil {
			if e, ok := p.(*Refusal); ok {
				err = e
			} else {
				panic(p)
			}
		}
	}()
	args := OAQuestionOperatorListQuestionsArguments{Cursor: arg0, Limit: arg1}
	v := OAServiceFrame{Version: 1, Service: "abstraction.asks/operator@1", Method: "ListQuestions", Arguments: Raw(encOAQuestionOperatorListQuestionsArguments(nil, &args, 1))}
	frame := encOAServiceFrame(nil, &v, 0)
	if _, err = servicePayload(frame); err != nil {
		return
	}
	var response []byte
	response, err = c.transport.ExchangeFrame(frame)
	if err != nil {
		return
	}
	var payload Raw
	payload, err = serviceResponse(response, v.Service, v.Method)
	if err != nil {
		return
	}
	r := &reader{buf: []byte(payload), depth: 1}
	r.ws()
	var decoded *OAQuestionOperatorListQuestionsResult
	decoded, err = r.decodeOAQuestionOperatorListQuestionsResult()
	if err != nil {
		return
	}
	_ = decoded
	r.ws()
	if r.pos != len(r.buf) {
		err = r.refuse("trailing_bytes")
		return
	}
	result = decoded.Value
	return
}
func (c *QuestionOperatorClient) AnswerQuestion(arg0 string, arg1 string) (result OperatorDecision, err error) {
	defer func() {
		if p := recover(); p != nil {
			if e, ok := p.(*Refusal); ok {
				err = e
			} else {
				panic(p)
			}
		}
	}()
	args := OAQuestionOperatorAnswerQuestionArguments{Id: arg0, Option: arg1}
	v := OAServiceFrame{Version: 1, Service: "abstraction.asks/operator@1", Method: "AnswerQuestion", Arguments: Raw(encOAQuestionOperatorAnswerQuestionArguments(nil, &args, 1))}
	frame := encOAServiceFrame(nil, &v, 0)
	if _, err = servicePayload(frame); err != nil {
		return
	}
	var response []byte
	response, err = c.transport.ExchangeFrame(frame)
	if err != nil {
		return
	}
	var payload Raw
	payload, err = serviceResponse(response, v.Service, v.Method)
	if err != nil {
		return
	}
	r := &reader{buf: []byte(payload), depth: 1}
	r.ws()
	var decoded *OAQuestionOperatorAnswerQuestionResult
	decoded, err = r.decodeOAQuestionOperatorAnswerQuestionResult()
	if err != nil {
		return
	}
	_ = decoded
	r.ws()
	if r.pos != len(r.buf) {
		err = r.refuse("trailing_bytes")
		return
	}
	result = decoded.Value
	return
}
func (d *QuestionOperatorDispatcher) WriteFrame(frame []byte) error {
	v, err := servicePayload(frame)
	if err != nil {
		return err
	}
	if v.Service != "abstraction.asks/operator@1" {
		return DispatchError("unknown_service")
	}
	switch v.Method {
	case "ListQuestions":
		return DispatchError("wrong_mode")
	case "AnswerQuestion":
		return DispatchError("wrong_mode")
	default:
		return DispatchError("unknown_method")
	}
}
func (d *QuestionOperatorDispatcher) ExchangeFrame(frame []byte) ([]byte, error) {
	v, err := servicePayload(frame)
	if err != nil {
		return nil, err
	}
	if v.Service != "abstraction.asks/operator@1" {
		return serviceReply(v, "", DispatchError("unknown_service"))
	}
	switch v.Method {
	case "ListQuestions":
		r := &reader{buf: []byte(v.Arguments), depth: 1}
		r.ws()
		args, err := r.decodeOAQuestionOperatorListQuestionsArguments()
		if err != nil {
			return serviceReply(v, "", err)
		}
		r.ws()
		if r.pos != len(r.buf) {
			return serviceReply(v, "", r.refuse("trailing_bytes"))
		}
		payload, err := d.invokeListQuestions(args)
		return serviceReply(v, payload, err)
	case "AnswerQuestion":
		r := &reader{buf: []byte(v.Arguments), depth: 1}
		r.ws()
		args, err := r.decodeOAQuestionOperatorAnswerQuestionArguments()
		if err != nil {
			return serviceReply(v, "", err)
		}
		r.ws()
		if r.pos != len(r.buf) {
			return serviceReply(v, "", r.refuse("trailing_bytes"))
		}
		payload, err := d.invokeAnswerQuestion(args)
		return serviceReply(v, payload, err)
	default:
		return serviceReply(v, "", DispatchError("unknown_method"))
	}
}
func (d *QuestionOperatorDispatcher) invokeListQuestions(args *OAQuestionOperatorListQuestionsArguments) (payload Raw, err error) {
	defer func() {
		if p := recover(); p != nil {
			payload = ""
			if _, ok := p.(*Refusal); ok {
				err = &ServiceError{Code: "invalid_result"}
			} else {
				err = &ServiceError{Code: "handler_error", Message: "handler failed"}
			}
		}
	}()
	var result OperatorPage
	result, err = d.Handler.ListQuestions(args.Cursor, args.Limit)
	if err != nil {
		return
	}
	value := OAQuestionOperatorListQuestionsResult{Value: result}
	payload = Raw(encOAQuestionOperatorListQuestionsResult(nil, &value, 1))
	r := &reader{buf: []byte(payload), depth: 1}
	r.ws()
	if _, e := r.decodeOAQuestionOperatorListQuestionsResult(); e != nil {
		payload = ""
		err = &ServiceError{Code: "invalid_result"}
		return
	}
	r.ws()
	if r.pos != len(r.buf) {
		payload = ""
		err = &ServiceError{Code: "invalid_result"}
	}
	return
}
func (d *QuestionOperatorDispatcher) invokeAnswerQuestion(args *OAQuestionOperatorAnswerQuestionArguments) (payload Raw, err error) {
	defer func() {
		if p := recover(); p != nil {
			payload = ""
			if _, ok := p.(*Refusal); ok {
				err = &ServiceError{Code: "invalid_result"}
			} else {
				err = &ServiceError{Code: "handler_error", Message: "handler failed"}
			}
		}
	}()
	var result OperatorDecision
	result, err = d.Handler.AnswerQuestion(args.Id, args.Option)
	if err != nil {
		return
	}
	value := OAQuestionOperatorAnswerQuestionResult{Value: result}
	payload = Raw(encOAQuestionOperatorAnswerQuestionResult(nil, &value, 1))
	r := &reader{buf: []byte(payload), depth: 1}
	r.ws()
	if _, e := r.decodeOAQuestionOperatorAnswerQuestionResult(); e != nil {
		payload = ""
		err = &ServiceError{Code: "invalid_result"}
		return
	}
	r.ws()
	if r.pos != len(r.buf) {
		payload = ""
		err = &ServiceError{Code: "invalid_result"}
	}
	return
}
