// Code generated by abstraction-idl from abstraction-asks/asks.thrift. DO NOT EDIT.

const HEX = "0123456789abcdef";
const ENC = new TextEncoder();
const SHORT = { 0x22: '\\"', 0x5c: "\\\\", 0x08: "\\b", 0x0c: "\\f", 0x0a: "\\n", 0x0d: "\\r", 0x09: "\\t" };

class Out {
  constructor() { this.b = []; }
  byte(c) { this.b.push(c); }
  ascii(s) { for (let i = 0; i < s.length; i++) this.b.push(s.charCodeAt(i)); }
  bytes() { return Uint8Array.from(this.b); }
}

function escByte(out, c) {
  const short = SHORT[c];
  if (short !== undefined) out.ascii(short);
  else if (c < 0x20) out.ascii("\\u00" + HEX[c >> 4] + HEX[c & 0xf]);
  else out.byte(c);
}

// Every integer the definition calls i64 is a BigInt here, because Number
// rounds above 2^53 and two values in the conformance record are i64 extremes.
function num(out, n) { out.ascii(BigInt(n).toString()); }

function pad(out, depth) { for (let i = 0; i < depth * 2; i++) out.byte(0x20); }

function strs(out, v, depth) {
  if (v.length === 0) { out.ascii("[]"); return; }
  out.ascii("[\n");
  for (let i = 0; i < v.length; i++) {
    pad(out, depth + 1);
    esc(out, v[i]);
    if (i + 1 < v.length) out.byte(0x2c);
    out.byte(0x0a);
  }
  pad(out, depth);
  out.byte(0x5d);
}

const isWs = (c) => c === 0x20 || c === 0x09 || c === 0x0a || c === 0x0d;

function raw(out, s, depth) {
  const b = typeof s === "string" ? ENC.encode(s) : s;
  let i = 0;
  while (i < b.length) {
    const c = b[i];
    if (isWs(c)) { i++; continue; }
    if (c === 0x22) {
      let j = i + 1;
      while (j < b.length) {
        if (b[j] === 0x5c) { j += 2; continue; }
        if (b[j] === 0x22) { j++; break; }
        j++;
      }
      for (let k = i; k < j; k++) out.byte(b[k]);
      i = j;
    } else if (c === 0x7b || c === 0x5b) {
      out.byte(c);
      i++;
      let j = i;
      while (j < b.length && isWs(b[j])) j++;
      if (j < b.length && (b[j] === 0x7d || b[j] === 0x5d)) { out.byte(b[j]); i = j + 1; }
      else { depth++; out.byte(0x0a); pad(out, depth); }
    } else if (c === 0x7d || c === 0x5d) {
      depth--;
      out.byte(0x0a);
      pad(out, depth);
      out.byte(c);
      i++;
    } else if (c === 0x2c) {
      out.ascii(",\n");
      pad(out, depth);
      i++;
    } else if (c === 0x3a) {
      out.ascii(": ");
      i++;
    } else {
      out.byte(c);
      i++;
    }
  }
}

// A JavaScript string sorts by UTF-16 code unit, which puts U+1D11E before
// U+FFFD where every other target puts it after. The definition declares UTF-8
// byte order, so the comparison is done on the encoded bytes.
function byteLess(a, b) {
  const x = ENC.encode(a), y = ENC.encode(b);
  const n = Math.min(x.length, y.length);
  for (let i = 0; i < n; i++) if (x[i] !== y[i]) return x[i] - y[i];
  return x.length - y.length;
}

function rawmap(out, m, depth) {
  const keys = Object.keys(m).sort(byteLess);
  if (keys.length === 0) { out.ascii("{}"); return; }
  out.ascii("{\n");
  for (let i = 0; i < keys.length; i++) {
    pad(out, depth + 1);
    esc(out, keys[i]);
    out.ascii(": ");
    raw(out, m[keys[i]], depth + 1);
    if (i + 1 < keys.length) out.byte(0x2c);
    out.byte(0x0a);
  }
  pad(out, depth);
  out.byte(0x7d);
}

function esc(out, s) {
  out.byte(0x22);
  for (const c of ENC.encode(s)) escByte(out, c);
  out.byte(0x22);
}

function strmap(out, m, depth) {
  const keys = Object.keys(m).sort(byteLess);
  if (keys.length === 0) { out.ascii("{}"); return; }
  out.ascii("{\n");
  for (let i = 0; i < keys.length; i++) {
    pad(out, depth + 1);
    esc(out, keys[i]);
    out.ascii(": ");
    esc(out, m[keys[i]]);
    if (i + 1 < keys.length) out.byte(0x2c);
    out.byte(0x0a);
  }
  pad(out, depth);
  out.byte(0x7d);
}

function writeList(out, v, depth, enc) {
  if (v.length === 0) { out.ascii("[]"); return; }
  out.ascii("[\n");
  for (let i = 0; i < v.length; i++) {
    pad(out, depth + 1);
    enc(out, v[i], depth + 1);
    if (i + 1 < v.length) out.byte(0x2c);
    out.byte(0x0a);
  }
  pad(out, depth);
  out.byte(0x5d);
}

export const ObservationOutcome = Object.freeze({
  Pending: "pending",
  Answered: "answered",
  Unknown: "unknown",
  Gone: "gone",
  Invalid: "invalid",
  Conflict: "conflict",
  Forbidden: "forbidden",
  Unavailable: "unavailable",
});

export const OperatorPageOutcome = Object.freeze({
  Page: "page",
  Gap: "gap",
  Invalid: "invalid",
  Forbidden: "forbidden",
  Unavailable: "unavailable",
});

export const OperatorDecisionOutcome = Object.freeze({
  Answered: "answered",
  Conflict: "conflict",
  Unknown: "unknown",
  Invalid: "invalid",
  Forbidden: "forbidden",
  Unavailable: "unavailable",
});

export const OperatorRetirementOutcome = Object.freeze({
  Retired: "retired",
  Unknown: "unknown",
  Invalid: "invalid",
  Forbidden: "forbidden",
  Unavailable: "unavailable",
});

export const ServiceErrorCode = Object.freeze({
  HandlerError: "handler_error",
  InvalidResult: "invalid_result",
  UnknownVersion: "unknown_version",
  UnknownService: "unknown_service",
  UnknownMethod: "unknown_method",
  WrongMode: "wrong_mode",
});

export const operations = ["ask", "pending", "answered", "answer", "forget"];

export const refusalCodes = ["internal", "invalid_request", "caller_refused", "unknown_operation", "not_administrator", "withdrawn", "unknown_question", "unknown_option", "bad_slot", "nothing_pending", "no_record"];

export const resourceActions = ["abstraction.asks/question.ask"];

function writeQuestion(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "asker");
  out.ascii(": ");
  esc(out, v.asker);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "key");
  out.ascii(": ");
  esc(out, v.key);
  if (Object.keys(v.slots).length !== 0) {
    out.byte(0x2c);
    out.byte(0x0a);
    pad(out, depth + 1);
    esc(out, "slots");
    out.ascii(": ");
    strmap(out, v.slots, depth + 1);
  }
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

function writeRequest(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "op");
  out.ascii(": ");
  esc(out, v.op);
  if (v.ask !== undefined && v.ask !== null) {
    out.byte(0x2c);
    out.byte(0x0a);
    pad(out, depth + 1);
    esc(out, "ask");
    out.ascii(": ");
    writeQuestion(out, v.ask, depth + 1);
  }
  if (v.wait) {
    out.byte(0x2c);
    out.byte(0x0a);
    pad(out, depth + 1);
    esc(out, "wait");
    out.ascii(": ");
    out.ascii(v.wait ? "true" : "false");
  }
  if (v.id !== "") {
    out.byte(0x2c);
    out.byte(0x0a);
    pad(out, depth + 1);
    esc(out, "id");
    out.ascii(": ");
    esc(out, v.id);
  }
  if (v.option !== "") {
    out.byte(0x2c);
    out.byte(0x0a);
    pad(out, depth + 1);
    esc(out, "option");
    out.ascii(": ");
    esc(out, v.option);
  }
  if (v.admin !== "") {
    out.byte(0x2c);
    out.byte(0x0a);
    pad(out, depth + 1);
    esc(out, "admin");
    out.ascii(": ");
    esc(out, v.admin);
  }
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

function writeAnswer(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "id");
  out.ascii(": ");
  esc(out, v.id);
  if (v.pending) {
    out.byte(0x2c);
    out.byte(0x0a);
    pad(out, depth + 1);
    esc(out, "pending");
    out.ascii(": ");
    out.ascii(v.pending ? "true" : "false");
  }
  if (v.option !== "") {
    out.byte(0x2c);
    out.byte(0x0a);
    pad(out, depth + 1);
    esc(out, "option");
    out.ascii(": ");
    esc(out, v.option);
  }
  if (v.yes) {
    out.byte(0x2c);
    out.byte(0x0a);
    pad(out, depth + 1);
    esc(out, "yes");
    out.ascii(": ");
    out.ascii(v.yes ? "true" : "false");
  }
  if (v.kept) {
    out.byte(0x2c);
    out.byte(0x0a);
    pad(out, depth + 1);
    esc(out, "kept");
    out.ascii(": ");
    out.ascii(v.kept ? "true" : "false");
  }
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

function writeRecordMetadata(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "id");
  out.ascii(": ");
  esc(out, v.id);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "asker");
  out.ascii(": ");
  esc(out, v.asker);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "key");
  out.ascii(": ");
  esc(out, v.key);
  if (v.about !== "") {
    out.byte(0x2c);
    out.byte(0x0a);
    pad(out, depth + 1);
    esc(out, "about");
    out.ascii(": ");
    esc(out, v.about);
  }
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "text");
  out.ascii(": ");
  esc(out, v.text);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "options");
  out.ascii(": ");
  strs(out, v.options, depth + 1);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "asked");
  out.ascii(": ");
  esc(out, v.asked);
  if (v.option !== "") {
    out.byte(0x2c);
    out.byte(0x0a);
    pad(out, depth + 1);
    esc(out, "option");
    out.ascii(": ");
    esc(out, v.option);
  }
  if (v.answered !== "") {
    out.byte(0x2c);
    out.byte(0x0a);
    pad(out, depth + 1);
    esc(out, "answered");
    out.ascii(": ");
    esc(out, v.answered);
  }
  if (v.kept) {
    out.byte(0x2c);
    out.byte(0x0a);
    pad(out, depth + 1);
    esc(out, "kept");
    out.ascii(": ");
    out.ascii(v.kept ? "true" : "false");
  }
  if (v.yes) {
    out.byte(0x2c);
    out.byte(0x0a);
    pad(out, depth + 1);
    esc(out, "yes");
    out.ascii(": ");
    out.ascii(v.yes ? "true" : "false");
  }
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

function writeResponseMetadata(out, v, depth) {
  out.byte(0x7b);
  let first = true;
  if (v.code !== "") {
    first = false;
    out.byte(0x0a);
    pad(out, depth + 1);
    esc(out, "code");
    out.ascii(": ");
    esc(out, v.code);
  }
  if (v.error !== "") {
    if (!first) out.byte(0x2c);
    first = false;
    out.byte(0x0a);
    pad(out, depth + 1);
    esc(out, "error");
    out.ascii(": ");
    esc(out, v.error);
  }
  if (v.answer !== undefined && v.answer !== null) {
    if (!first) out.byte(0x2c);
    first = false;
    out.byte(0x0a);
    pad(out, depth + 1);
    esc(out, "answer");
    out.ascii(": ");
    writeAnswer(out, v.answer, depth + 1);
  }
  if (v.records.length !== 0) {
    if (!first) out.byte(0x2c);
    first = false;
    out.byte(0x0a);
    pad(out, depth + 1);
    esc(out, "records");
    out.ascii(": ");
    writeList(out, v.records, depth + 1, writeRecordMetadata);
  }
  if (!first) { out.byte(0x0a); pad(out, depth); }
  out.byte(0x7d);
}

function writeApplicationQuestion(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "request_key");
  out.ascii(": ");
  esc(out, v.requestKey);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "key");
  out.ascii(": ");
  esc(out, v.key);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "slots");
  out.ascii(": ");
  strmap(out, v.slots, depth + 1);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

function writeQuestionObservation(out, v, depth) {
    if (typeof v.outcome !== "string") throw new Refusal("wrong_type",0);
    if (v.outcome !== "pending" && v.outcome !== "answered" && v.outcome !== "unknown" && v.outcome !== "gone" && v.outcome !== "invalid" && v.outcome !== "conflict" && v.outcome !== "forbidden" && v.outcome !== "unavailable") { throw new Refusal("bad_enum",0); }
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "outcome");
  out.ascii(": ");
  esc(out, v.outcome);
  if (v.answer !== undefined && v.answer !== null) {
    out.byte(0x2c);
    out.byte(0x0a);
    pad(out, depth + 1);
    esc(out, "answer");
    out.ascii(": ");
    writeAnswer(out, v.answer, depth + 1);
  }
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

function writeOperatorPage(out, v, depth) {
    if (typeof v.outcome !== "string") throw new Refusal("wrong_type",0);
    if (v.outcome !== "page" && v.outcome !== "gap" && v.outcome !== "invalid" && v.outcome !== "forbidden" && v.outcome !== "unavailable") { throw new Refusal("bad_enum",0); }
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "outcome");
  out.ascii(": ");
  esc(out, v.outcome);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "records");
  out.ascii(": ");
  writeList(out, v.records, depth + 1, writeRecordMetadata);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "next");
  out.ascii(": ");
  esc(out, v.next);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "complete");
  out.ascii(": ");
  out.ascii(v.complete ? "true" : "false");
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

function writeOperatorDecision(out, v, depth) {
    if (typeof v.outcome !== "string") throw new Refusal("wrong_type",0);
    if (v.outcome !== "answered" && v.outcome !== "conflict" && v.outcome !== "unknown" && v.outcome !== "invalid" && v.outcome !== "forbidden" && v.outcome !== "unavailable") { throw new Refusal("bad_enum",0); }
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "outcome");
  out.ascii(": ");
  esc(out, v.outcome);
  if (v.record !== undefined && v.record !== null) {
    out.byte(0x2c);
    out.byte(0x0a);
    pad(out, depth + 1);
    esc(out, "record");
    out.ascii(": ");
    writeRecordMetadata(out, v.record, depth + 1);
  }
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

function writeOperatorRetirement(out, v, depth) {
    if (typeof v.outcome !== "string") throw new Refusal("wrong_type",0);
    if (v.outcome !== "retired" && v.outcome !== "unknown" && v.outcome !== "invalid" && v.outcome !== "forbidden" && v.outcome !== "unavailable") { throw new Refusal("bad_enum",0); }
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "outcome");
  out.ascii(": ");
  esc(out, v.outcome);
  if (v.record !== undefined && v.record !== null) {
    out.byte(0x2c);
    out.byte(0x0a);
    pad(out, depth + 1);
    esc(out, "record");
    out.ascii(": ");
    writeRecordMetadata(out, v.record, depth + 1);
  }
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

function writeOAQuestionApplicationAskArguments(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "question");
  out.ascii(": ");
  writeApplicationQuestion(out, v.question, depth + 1);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

function writeOAQuestionApplicationObserveArguments(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "request_key");
  out.ascii(": ");
  esc(out, v.requestKey);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "wait_ms");
  out.ascii(": ");
  num(out, v.waitMs);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

function writeOAQuestionOperatorListQuestionsArguments(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "cursor");
  out.ascii(": ");
  esc(out, v.cursor);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "limit");
  out.ascii(": ");
  num(out, v.limit);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

function writeOAQuestionOperatorAnswerQuestionArguments(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "id");
  out.ascii(": ");
  esc(out, v.id);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "option");
  out.ascii(": ");
  esc(out, v.option);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

function writeOAQuestionOperatorRetireQuestionArguments(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "id");
  out.ascii(": ");
  esc(out, v.id);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

function writeOAServiceFrame(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "version");
  out.ascii(": ");
  num(out, v.version);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "service");
  out.ascii(": ");
  esc(out, v.service);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "method");
  out.ascii(": ");
  esc(out, v.method);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "arguments");
  out.ascii(": ");
  for (const byte of (typeof v.arguments === "string" ? ENC.encode(v.arguments) : v.arguments)) out.byte(byte);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

function writeOAServiceReply(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "version");
  out.ascii(": ");
  num(out, v.version);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "service");
  out.ascii(": ");
  esc(out, v.service);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "method");
  out.ascii(": ");
  esc(out, v.method);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "ok");
  out.ascii(": ");
  out.ascii(v.ok ? "true" : "false");
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "payload");
  out.ascii(": ");
  for (const byte of (typeof v.payload === "string" ? ENC.encode(v.payload) : v.payload)) out.byte(byte);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

function writeOAServiceError(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "code");
  out.ascii(": ");
  esc(out, v.code);
  out.byte(0x2c);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "message");
  out.ascii(": ");
  esc(out, v.message);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

function writeOAQuestionApplicationAskResult(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "value");
  out.ascii(": ");
  writeQuestionObservation(out, v.value, depth + 1);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

function writeOAQuestionApplicationObserveResult(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "value");
  out.ascii(": ");
  writeQuestionObservation(out, v.value, depth + 1);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

function writeOAQuestionOperatorListQuestionsResult(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "value");
  out.ascii(": ");
  writeOperatorPage(out, v.value, depth + 1);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

function writeOAQuestionOperatorAnswerQuestionResult(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "value");
  out.ascii(": ");
  writeOperatorDecision(out, v.value, depth + 1);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

function writeOAQuestionOperatorRetireQuestionResult(out, v, depth) {
  out.byte(0x7b);
  out.byte(0x0a);
  pad(out, depth + 1);
  esc(out, "value");
  out.ascii(": ");
  writeOperatorRetirement(out, v.value, depth + 1);
  out.byte(0x0a);
  pad(out, depth);
  out.byte(0x7d);
}

export function encode(v) {
  const out = new Out();
  writeRequest(out, v, 0);
  out.byte(0x0a);
  return out.bytes();
}

// A BOM inside a JSON string is data, not a stream signature.
const DEC = new TextDecoder("utf-8", {ignoreBOM: true});
const DEPTH_LIMIT = 64;
const I64_DIGITS = 19;
const UNESCAPE = { 0x22: 0x22, 0x5c: 0x5c, 0x2f: 0x2f, 0x62: 0x08, 0x66: 0x0c, 0x6e: 0x0a, 0x72: 0x0d, 0x74: 0x09 };

export class Refusal extends Error {
  constructor(word, offset) {
    super("refused: " + word + " at byte " + offset);
    this.name = "Refusal";
    this.word = word;
    this.offset = offset;
  }
}

function appendRune(out, cp) {
  if (cp < 0x80) out.push(cp);
  else if (cp < 0x800) out.push(0xc0 | (cp >> 6), 0x80 | (cp & 0x3f));
  else if (cp < 0x10000) out.push(0xe0 | (cp >> 12), 0x80 | ((cp >> 6) & 0x3f), 0x80 | (cp & 0x3f));
  else out.push(0xf0 | (cp >> 18), 0x80 | ((cp >> 12) & 0x3f), 0x80 | ((cp >> 6) & 0x3f), 0x80 | (cp & 0x3f));
}

// TextDecoder substitutes U+FFFD for a bad sequence rather than reporting it, so
// the bytes are checked before they are decoded and the refusal says so.
function validUtf8(b) {
  for (let i = 0; i < b.length; ) {
    const c = b[i];
    if (c < 0x80) { i++; continue; }
    let n, cp;
    if (c >> 5 === 0x6) { n = 2; cp = c & 0x1f; }
    else if (c >> 4 === 0xe) { n = 3; cp = c & 0x0f; }
    else if (c >> 3 === 0x1e) { n = 4; cp = c & 0x07; }
    else return false;
    if (i + n > b.length) return false;
    for (let k = 1; k < n; k++) {
      if (b[i + k] >> 6 !== 0x2) return false;
      cp = (cp << 6) | (b[i + k] & 0x3f);
    }
    const lowest = [0, 0, 0x80, 0x800, 0x10000][n];
    if (cp < lowest || cp > 0x10ffff || (cp >= 0xd800 && cp <= 0xdfff)) return false;
    i += n;
  }
  return true;
}

class Reader {
  constructor(buf) { this.buf = buf; this.pos = 0; this.depth = 0; }

  refuse(word) { return new Refusal(word, this.pos); }

  at() { return this.pos < this.buf.length ? this.buf[this.pos] : 0; }

  digit() { const c = this.at(); return c >= 0x30 && c <= 0x39; }

  ws() { while (this.pos < this.buf.length && isWs(this.buf[this.pos])) this.pos++; }

  enter() {
    this.depth++;
    if (this.depth > DEPTH_LIMIT) throw this.refuse("depth_exceeded");
  }

  string() {
    if (this.at() !== 0x22) throw this.refuse("wrong_type");
    this.pos++;
    const out = [];
    for (;;) {
      if (this.pos >= this.buf.length) throw this.refuse("malformed");
      const c = this.buf[this.pos];
      if (c === 0x22) {
        this.pos++;
        const bytes = Uint8Array.from(out);
        if (!validUtf8(bytes)) throw this.refuse("bad_string");
        return DEC.decode(bytes);
      }
      if (c < 0x20) throw this.refuse("bad_string");
      if (c === 0x5c) this.escape(out);
      else { out.push(c); this.pos++; }
    }
  }

  escape(out) {
    this.pos++;
    if (this.pos >= this.buf.length) throw this.refuse("malformed");
    const c = this.buf[this.pos];
    this.pos++;
    const plain = UNESCAPE[c];
    if (plain !== undefined) { out.push(plain); return; }
    if (c !== 0x75) throw this.refuse("bad_string");
    let u = this.hex4();
    if (u >= 0xdc00 && u <= 0xdfff) throw this.refuse("bad_string");
    if (u >= 0xd800 && u <= 0xdbff) {
      if (this.pos + 1 >= this.buf.length || this.buf[this.pos] !== 0x5c || this.buf[this.pos + 1] !== 0x75)
        throw this.refuse("bad_string");
      this.pos += 2;
      const low = this.hex4();
      if (low < 0xdc00 || low > 0xdfff) throw this.refuse("bad_string");
      u = 0x10000 + ((u - 0xd800) << 10) + (low - 0xdc00);
    }
    appendRune(out, u);
  }

  hex4() {
    if (this.pos + 4 > this.buf.length) throw this.refuse("bad_string");
    let u = 0;
    for (let i = 0; i < 4; i++) {
      const c = this.buf[this.pos + i];
      if (c >= 0x30 && c <= 0x39) u = (u << 4) | (c - 0x30);
      else if (c >= 0x61 && c <= 0x66) u = (u << 4) | (c - 0x61 + 10);
      else if (c >= 0x41 && c <= 0x46) u = (u << 4) | (c - 0x41 + 10);
      else throw this.refuse("bad_string");
    }
    this.pos += 4;
    return u;
  }

  integer(low, high) {
    const c = this.at();
    if (c !== 0x2d && (c < 0x30 || c > 0x39)) throw this.refuse("wrong_type");
    const negative = c === 0x2d;
    if (negative) this.pos++;
    if (!this.digit()) throw this.refuse("malformed");
    const start = this.pos;
    if (this.at() === 0x30) this.pos++;
    else while (this.digit()) this.pos++;
    const after = this.at();
    if (after === 0x2e || after === 0x65 || after === 0x45 || this.digit()) throw this.refuse("number_spelling");
    if (this.pos - start > I64_DIGITS) throw this.refuse("number_spelling");
    let n = BigInt(String.fromCharCode(...this.buf.subarray(start, this.pos)));
    if (negative) {
      if (n === 0n) throw this.refuse("number_spelling");
      n = -n;
    }
    if (n < low || n > high) throw this.refuse("number_spelling");
    return n;
  }

  boolean() {
    if (this.at() === 0x74) { this.literal("true"); return true; }
    if (this.at() === 0x66) { this.literal("false"); return false; }
    throw this.refuse("wrong_type");
  }

  literal(word) {
    for (let i = 0; i < word.length; i++)
      if (this.buf[this.pos + i] !== word.charCodeAt(i)) throw this.refuse("malformed");
    this.pos += word.length;
  }

  strList() {
    if (this.at() !== 0x5b) throw this.refuse("wrong_type");
    this.enter();
    this.pos++;
    const out = [];
    this.ws();
    if (this.at() !== 0x5d) {
      for (;;) {
        this.ws();
        out.push(this.string());
        this.ws();
        if (this.at() !== 0x2c) break;
        this.pos++;
      }
    }
    if (this.at() !== 0x5d) throw this.refuse("malformed");
    this.pos++;
    this.depth--;
    return out;
  }

  rawMap() {
    if (this.at() !== 0x7b) throw this.refuse("wrong_type");
    this.enter();
    this.pos++;
    const out = Object.create(null);
    this.ws();
    if (this.at() !== 0x7d) {
      for (;;) {
        this.ws();
        if (this.at() !== 0x22) throw this.refuse("malformed");
        const k = this.string();
        if (k in out) throw this.refuse("duplicate_key");
        this.ws();
        if (this.at() !== 0x3a) throw this.refuse("malformed");
        this.pos++;
        this.ws();
        out[k] = this.rawValue();
        this.ws();
        if (this.at() !== 0x2c) break;
        this.pos++;
      }
    }
    if (this.at() !== 0x7d) throw this.refuse("malformed");
    this.pos++;
    this.depth--;
    return out;
  }

  rawValue() {
    const start = this.pos;
    this.skipValue();
    return this.buf.subarray(start, this.pos);
  }

  skipValue() {
    const c = this.at();
    if (c === 0x22) this.skipString();
    else if (c === 0x7b || c === 0x5b) this.skipContainer();
    else if (c === 0x74) this.literal("true");
    else if (c === 0x66) this.literal("false");
    else if (c === 0x6e) this.literal("null");
    else if (c === 0x2d || (c >= 0x30 && c <= 0x39)) this.skipNumber();
    else throw this.refuse("malformed");
  }

  // An opaque value is validated and carried, never interpreted. Its syntax is
  // the record's own — the same string reader, so an escape, a control byte or a
  // lone surrogate is judged identically at any depth — and what it is free to
  // spell, it keeps: the bytes between these two offsets are what a writer
  // re-emits. A number is walked, never converted, so a value no host type holds
  // survives the reader that carried it.
  skipString() {
    this.string();
  }

  someDigits() {
    let n = 0;
    while (this.at() >= 0x30 && this.at() <= 0x39) { this.pos++; n++; }
    if (n === 0) throw this.refuse("number_spelling");
  }

  skipNumber() {
    if (this.at() === 0x2d) this.pos++;
    const c = this.at();
    if (c === 0x30) this.pos++;
    else if (c > 0x30 && c <= 0x39) { while (this.at() >= 0x30 && this.at() <= 0x39) this.pos++; }
    else throw this.refuse("number_spelling");
    if (this.at() === 0x2e) { this.pos++; this.someDigits(); }
    if (this.at() === 0x65 || this.at() === 0x45) {
      this.pos++;
      if (this.at() === 0x2b || this.at() === 0x2d) this.pos++;
      this.someDigits();
    }
  }

  skipContainer() {
    const opener = this.at();
    const shut = opener === 0x7b ? 0x7d : 0x5d;
    this.enter();
    this.pos++;
    this.ws();
    const seen = new Set();
    if (this.at() !== shut) {
      for (;;) {
        this.ws();
        if (opener === 0x7b) {
          if (this.at() !== 0x22) throw this.refuse("malformed");
          const k = this.string();
          if (seen.has(k)) throw this.refuse("duplicate_key");
          seen.add(k);
          this.ws();
          if (this.at() !== 0x3a) throw this.refuse("malformed");
          this.pos++;
          this.ws();
        }
        this.skipValue();
        this.ws();
        if (this.at() !== 0x2c) break;
        this.pos++;
      }
    }
    if (this.at() !== shut) throw this.refuse("malformed");
    this.pos++;
    this.depth--;
  }
}

function strMap(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const out = Object.create(null);
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const k = r.string();
      if (k in out) throw r.refuse("duplicate_key");
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      out[k] = r.string();
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  return out;
}

function readList(r, elem) {
  if (r.at() !== 0x5b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const out = [];
  r.ws();
  if (r.at() !== 0x5d) {
    for (;;) {
      r.ws();
      out.push(elem(r));
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x5d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  return out;
}

// Own Ask fields. The service owns question text/options; callers supply a
// known key and slots. Native Ask.For carries optional peer observation
// evidence and remains a transport supplement, never caller authority.
export function newQuestion() {
  return { asker: "", key: "", slots: {} };
}

// Existing question operation concepts. Wait cancellation belongs to the native
// client context. This metadata descriptor does not replace the existing
// handwritten line transport.
export function newRequest() {
  return { op: "", ask: null, wait: false, id: "", option: "", admin: "" };
}

export function newAnswer() {
  return { id: "", pending: false, option: "", yes: false, kept: false };
}

// Own question-history fields; timestamps retain existing RFC3339
// representation. Native Record includes Via/For Seen evidence from shared
// identity. Empty option means pending.
export function newRecordMetadata() {
  return { id: "", asker: "", key: "", about: "", text: "", options: [], asked: "", option: "", answered: "", kept: false, yes: false };
}

// Own response projection. Any nonempty code/error refuses, including unknown
// future codes. Evidence supplement and existing wire handling remain native;
// no generated complete service interface is claimed.
export function newResponseMetadata() {
  return { code: "", error: "", answer: null, records: [] };
}

// Stable caller-owned request key (1..128 UTF-8 bytes, no control characters),
// known question key and exactly its declared slots. Each slot is one line of
// at most 200 Unicode characters. No asker or authority fields are accepted.
// The receiving account and executable-path proof scope the request. Retry
// uncertain submission with this same key and unchanged content; a fresh key
// requests a new admission.
export function newApplicationQuestion() {
  return { requestKey: "", key: "", slots: {} };
}

// Answer is present exactly for pending/answered. Pending has no
// option/yes/kept decision. Unknown is an unobserved key in this caller's
// scope. Gone retains a forgotten admission's key and never admits it again.
// Conflict means the key was previously used with different content.
// Unavailable includes storage/capacity refusal and establishes no human
// decision. Answered reports the recorded human choice; it grants no resource
// authority by itself.
export function newQuestionObservation() {
  return { outcome: "", answer: null };
}

// Latest-book enumeration for an explicitly authorized operator, including
// pending and answered questions. Page has at most the requested 1..64 records
// and 256 KiB per encoded reply, with conservative record, indentation and
// envelope accounting. Complete means this snapshot was exhausted; otherwise
// next is nonempty. Refusals contain no records, next or complete flag. Opaque
// cursors (at most 256 UTF-8 bytes) bind receiving caller scope, host epoch and
// exact book revision. Change, restart or scope mismatch returns gap: restart
// from empty cursor. No historical change replay or stable snapshot across
// edits is promised. Native Via/For evidence stays server-side; display fields
// confer no authority.
export function newOperatorPage() {
  return { outcome: "", records: [], next: "", complete: false };
}

// Record is present exactly for answered. Same ID and option replays the
// original decision including its timestamp and kept/once meaning; another
// option conflicts. Unknown means no retained question. Invalid includes an
// unknown option or invalid ID. Unavailable establishes no decision or
// noncommit claim: retry the same ID/option or inspect fresh history. Answering
// records a human choice, never a resource grant.
export function newOperatorDecision() {
  return { outcome: "", record: null };
}

// Retired removes a retained pending or answered question from the Book. Record
// carries its last metadata on the retiring call and is absent when replaying
// an already retired ID. A pending question retired without an answer carries
// no decision. Admission tombstones remain: application replay and observation
// of its key report gone, and that key never admits again. Unknown means no
// retained or retired question. Invalid means a malformed ID. Unavailable
// establishes no retirement claim: retry the same ID or inspect fresh history.
export function newOperatorRetirement() {
  return { outcome: "", record: null };
}

function newOAQuestionApplicationAskArguments() {
  return { question: newApplicationQuestion() };
}

function newOAQuestionApplicationObserveArguments() {
  return { requestKey: "", waitMs: 0n };
}

function newOAQuestionOperatorListQuestionsArguments() {
  return { cursor: "", limit: 0n };
}

function newOAQuestionOperatorAnswerQuestionArguments() {
  return { id: "", option: "" };
}

function newOAQuestionOperatorRetireQuestionArguments() {
  return { id: "" };
}

function newOAServiceFrame() {
  return { version: 0, service: "", method: "", arguments: "" };
}

function newOAServiceReply() {
  return { version: 0, service: "", method: "", ok: false, payload: "" };
}

function newOAServiceError() {
  return { code: "", message: "" };
}

function newOAQuestionApplicationAskResult() {
  return { value: newQuestionObservation() };
}

function newOAQuestionApplicationObserveResult() {
  return { value: newQuestionObservation() };
}

function newOAQuestionOperatorListQuestionsResult() {
  return { value: newOperatorPage() };
}

function newOAQuestionOperatorAnswerQuestionResult() {
  return { value: newOperatorDecision() };
}

function newOAQuestionOperatorRetireQuestionResult() {
  return { value: newOperatorRetirement() };
}

function readQuestion(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newQuestion();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "asker") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.asker = r.string();
      } else if (key === "key") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.key = r.string();
      } else if (key === "slots") {
        if (seen & 4) throw r.refuse("duplicate_field");
        seen |= 4;
        v.slots = strMap(r);
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 3) >>> 0) !== 3) throw r.refuse("missing_field");
  return v;
}

function readRequest(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newRequest();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "op") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.op = r.string();
      } else if (key === "ask") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.ask = readQuestion(r);
      } else if (key === "wait") {
        if (seen & 4) throw r.refuse("duplicate_field");
        seen |= 4;
        v.wait = r.boolean();
      } else if (key === "id") {
        if (seen & 8) throw r.refuse("duplicate_field");
        seen |= 8;
        v.id = r.string();
      } else if (key === "option") {
        if (seen & 16) throw r.refuse("duplicate_field");
        seen |= 16;
        v.option = r.string();
      } else if (key === "admin") {
        if (seen & 32) throw r.refuse("duplicate_field");
        seen |= 32;
        v.admin = r.string();
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 1) >>> 0) !== 1) throw r.refuse("missing_field");
  return v;
}

function readAnswer(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newAnswer();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "id") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.id = r.string();
      } else if (key === "pending") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.pending = r.boolean();
      } else if (key === "option") {
        if (seen & 4) throw r.refuse("duplicate_field");
        seen |= 4;
        v.option = r.string();
      } else if (key === "yes") {
        if (seen & 8) throw r.refuse("duplicate_field");
        seen |= 8;
        v.yes = r.boolean();
      } else if (key === "kept") {
        if (seen & 16) throw r.refuse("duplicate_field");
        seen |= 16;
        v.kept = r.boolean();
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 1) >>> 0) !== 1) throw r.refuse("missing_field");
  return v;
}

function readRecordMetadata(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newRecordMetadata();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "id") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.id = r.string();
      } else if (key === "asker") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.asker = r.string();
      } else if (key === "key") {
        if (seen & 4) throw r.refuse("duplicate_field");
        seen |= 4;
        v.key = r.string();
      } else if (key === "about") {
        if (seen & 8) throw r.refuse("duplicate_field");
        seen |= 8;
        v.about = r.string();
      } else if (key === "text") {
        if (seen & 16) throw r.refuse("duplicate_field");
        seen |= 16;
        v.text = r.string();
      } else if (key === "options") {
        if (seen & 32) throw r.refuse("duplicate_field");
        seen |= 32;
        v.options = r.strList();
      } else if (key === "asked") {
        if (seen & 64) throw r.refuse("duplicate_field");
        seen |= 64;
        v.asked = r.string();
      } else if (key === "option") {
        if (seen & 128) throw r.refuse("duplicate_field");
        seen |= 128;
        v.option = r.string();
      } else if (key === "answered") {
        if (seen & 256) throw r.refuse("duplicate_field");
        seen |= 256;
        v.answered = r.string();
      } else if (key === "kept") {
        if (seen & 512) throw r.refuse("duplicate_field");
        seen |= 512;
        v.kept = r.boolean();
      } else if (key === "yes") {
        if (seen & 1024) throw r.refuse("duplicate_field");
        seen |= 1024;
        v.yes = r.boolean();
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 119) >>> 0) !== 119) throw r.refuse("missing_field");
  return v;
}

function readResponseMetadata(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newResponseMetadata();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "code") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.code = r.string();
      } else if (key === "error") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.error = r.string();
      } else if (key === "answer") {
        if (seen & 4) throw r.refuse("duplicate_field");
        seen |= 4;
        v.answer = readAnswer(r);
      } else if (key === "records") {
        if (seen & 8) throw r.refuse("duplicate_field");
        seen |= 8;
        v.records = readList(r, readRecordMetadata);
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  return v;
}

function readApplicationQuestion(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newApplicationQuestion();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "request_key") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.requestKey = r.string();
      } else if (key === "key") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.key = r.string();
      } else if (key === "slots") {
        if (seen & 4) throw r.refuse("duplicate_field");
        seen |= 4;
        v.slots = strMap(r);
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 7) >>> 0) !== 7) throw r.refuse("missing_field");
  return v;
}

function readQuestionObservation(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newQuestionObservation();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "outcome") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.outcome = r.string();
      } else if (key === "answer") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.answer = readAnswer(r);
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 1) >>> 0) !== 1) throw r.refuse("missing_field");
    if (v.outcome !== "pending" && v.outcome !== "answered" && v.outcome !== "unknown" && v.outcome !== "gone" && v.outcome !== "invalid" && v.outcome !== "conflict" && v.outcome !== "forbidden" && v.outcome !== "unavailable") { throw r.refuse("bad_enum"); }
  return v;
}

function readOperatorPage(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOperatorPage();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "outcome") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.outcome = r.string();
      } else if (key === "records") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.records = readList(r, readRecordMetadata);
      } else if (key === "next") {
        if (seen & 4) throw r.refuse("duplicate_field");
        seen |= 4;
        v.next = r.string();
      } else if (key === "complete") {
        if (seen & 8) throw r.refuse("duplicate_field");
        seen |= 8;
        v.complete = r.boolean();
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 15) >>> 0) !== 15) throw r.refuse("missing_field");
    if (v.outcome !== "page" && v.outcome !== "gap" && v.outcome !== "invalid" && v.outcome !== "forbidden" && v.outcome !== "unavailable") { throw r.refuse("bad_enum"); }
  return v;
}

function readOperatorDecision(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOperatorDecision();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "outcome") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.outcome = r.string();
      } else if (key === "record") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.record = readRecordMetadata(r);
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 1) >>> 0) !== 1) throw r.refuse("missing_field");
    if (v.outcome !== "answered" && v.outcome !== "conflict" && v.outcome !== "unknown" && v.outcome !== "invalid" && v.outcome !== "forbidden" && v.outcome !== "unavailable") { throw r.refuse("bad_enum"); }
  return v;
}

function readOperatorRetirement(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOperatorRetirement();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "outcome") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.outcome = r.string();
      } else if (key === "record") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.record = readRecordMetadata(r);
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 1) >>> 0) !== 1) throw r.refuse("missing_field");
    if (v.outcome !== "retired" && v.outcome !== "unknown" && v.outcome !== "invalid" && v.outcome !== "forbidden" && v.outcome !== "unavailable") { throw r.refuse("bad_enum"); }
  return v;
}

function readOAQuestionApplicationAskArguments(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOAQuestionApplicationAskArguments();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "question") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.question = readApplicationQuestion(r);
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 1) >>> 0) !== 1) throw r.refuse("missing_field");
  return v;
}

function readOAQuestionApplicationObserveArguments(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOAQuestionApplicationObserveArguments();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "request_key") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.requestKey = r.string();
      } else if (key === "wait_ms") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.waitMs = r.integer(-9223372036854775808n, 9223372036854775807n);
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 3) >>> 0) !== 3) throw r.refuse("missing_field");
  return v;
}

function readOAQuestionOperatorListQuestionsArguments(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOAQuestionOperatorListQuestionsArguments();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "cursor") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.cursor = r.string();
      } else if (key === "limit") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.limit = r.integer(-9223372036854775808n, 9223372036854775807n);
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 3) >>> 0) !== 3) throw r.refuse("missing_field");
  return v;
}

function readOAQuestionOperatorAnswerQuestionArguments(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOAQuestionOperatorAnswerQuestionArguments();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "id") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.id = r.string();
      } else if (key === "option") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.option = r.string();
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 3) >>> 0) !== 3) throw r.refuse("missing_field");
  return v;
}

function readOAQuestionOperatorRetireQuestionArguments(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOAQuestionOperatorRetireQuestionArguments();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "id") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.id = r.string();
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 1) >>> 0) !== 1) throw r.refuse("missing_field");
  return v;
}

function readOAServiceFrame(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOAServiceFrame();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "version") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.version = Number(r.integer(-2147483648n, 2147483647n));
      } else if (key === "service") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.service = r.string();
      } else if (key === "method") {
        if (seen & 4) throw r.refuse("duplicate_field");
        seen |= 4;
        v.method = r.string();
      } else if (key === "arguments") {
        if (seen & 8) throw r.refuse("duplicate_field");
        seen |= 8;
        v.arguments = r.rawValue();
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 15) >>> 0) !== 15) throw r.refuse("missing_field");
  return v;
}

function readOAServiceReply(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOAServiceReply();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "version") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.version = Number(r.integer(-2147483648n, 2147483647n));
      } else if (key === "service") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.service = r.string();
      } else if (key === "method") {
        if (seen & 4) throw r.refuse("duplicate_field");
        seen |= 4;
        v.method = r.string();
      } else if (key === "ok") {
        if (seen & 8) throw r.refuse("duplicate_field");
        seen |= 8;
        v.ok = r.boolean();
      } else if (key === "payload") {
        if (seen & 16) throw r.refuse("duplicate_field");
        seen |= 16;
        v.payload = r.rawValue();
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 31) >>> 0) !== 31) throw r.refuse("missing_field");
  return v;
}

function readOAServiceError(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOAServiceError();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "code") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.code = r.string();
      } else if (key === "message") {
        if (seen & 2) throw r.refuse("duplicate_field");
        seen |= 2;
        v.message = r.string();
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 3) >>> 0) !== 3) throw r.refuse("missing_field");
  return v;
}

function readOAQuestionApplicationAskResult(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOAQuestionApplicationAskResult();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "value") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.value = readQuestionObservation(r);
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 1) >>> 0) !== 1) throw r.refuse("missing_field");
  return v;
}

function readOAQuestionApplicationObserveResult(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOAQuestionApplicationObserveResult();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "value") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.value = readQuestionObservation(r);
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 1) >>> 0) !== 1) throw r.refuse("missing_field");
  return v;
}

function readOAQuestionOperatorListQuestionsResult(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOAQuestionOperatorListQuestionsResult();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "value") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.value = readOperatorPage(r);
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 1) >>> 0) !== 1) throw r.refuse("missing_field");
  return v;
}

function readOAQuestionOperatorAnswerQuestionResult(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOAQuestionOperatorAnswerQuestionResult();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "value") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.value = readOperatorDecision(r);
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 1) >>> 0) !== 1) throw r.refuse("missing_field");
  return v;
}

function readOAQuestionOperatorRetireQuestionResult(r) {
  if (r.at() !== 0x7b) throw r.refuse("wrong_type");
  r.enter();
  r.pos++;
  const v = newOAQuestionOperatorRetireQuestionResult();
  let seen = 0;
  r.ws();
  if (r.at() !== 0x7d) {
    for (;;) {
      r.ws();
      if (r.at() !== 0x22) throw r.refuse("malformed");
      const key = r.string();
      r.ws();
      if (r.at() !== 0x3a) throw r.refuse("malformed");
      r.pos++;
      r.ws();
      if (key === "value") {
        if (seen & 1) throw r.refuse("duplicate_field");
        seen |= 1;
        v.value = readOperatorRetirement(r);
      } else {
        throw r.refuse("unknown_field");
      }
      r.ws();
      if (r.at() !== 0x2c) break;
      r.pos++;
    }
  }
  if (r.at() !== 0x7d) throw r.refuse("malformed");
  r.pos++;
  r.depth--;
  if (((seen & 1) >>> 0) !== 1) throw r.refuse("missing_field");
  return v;
}

export function decode(data) {
  const r = new Reader(data);
  r.ws();
  const v = readRequest(r);
  r.ws();
  if (r.pos < r.buf.length) throw r.refuse("trailing_bytes");
  return v;
}

// refusals is in the order two of them are chosen between.
const refusals = ["malformed", "bad_string", "number_spelling", "wrong_type", "depth_exceeded", "duplicate_key", "duplicate_field", "unknown_field", "missing_field", "bad_enum", "trailing_bytes"];

function refusalRank(word) {
  return refusals.indexOf(word);
}

export class DispatchError extends Error {
  constructor(code) { super(code); this.name = "DispatchError"; this.code = code; }
}
export class ServiceError extends Error {
  constructor(code, message = "") { super(message || code); this.name = "ServiceError"; this.code = code; }
}
function _serviceDecode(decoder, frame, depth) {
  const reader = new Reader(typeof frame === "string" ? ENC.encode(frame) : frame);
  reader.depth = depth; reader.ws();
  const value = decoder(reader); reader.ws();
  if (reader.pos !== reader.buf.length) throw reader.refuse("trailing_bytes");
  return value;
}
function _serviceEncode(encoder, value, depth) {
  const out = new Out(); encoder(out, value, depth); return out.bytes();
}
function _serviceCheck(kind, value, depth = 0) {
  if (depth > DEPTH_LIMIT) throw new Refusal("depth_exceeded", 0);
  let valid = false;
  if (kind === "string") {
    valid = typeof value === "string";
    if (valid) for (const ch of value) {
      const cp = ch.codePointAt(0);
      if (cp >= 0xd800 && cp <= 0xdfff) throw new Refusal("bad_string", 0);
    }
  } else if (kind === "i32") {
    valid = typeof value === "number" && Number.isInteger(value) && value >= -2147483648 && value <= 2147483647;
  } else if (kind === "i64") {
    valid = typeof value === "bigint" && value >= -9223372036854775808n && value <= 9223372036854775807n;
  } else if (kind === "bool") valid = typeof value === "boolean";
  else if (kind === "json") {
    valid = typeof value === "string" || value instanceof Uint8Array;
    if (valid) { const r = new Reader(typeof value === "string" ? ENC.encode(value) : value); r.depth = depth; r.ws(); r.rawValue(); r.ws(); if (r.pos !== r.buf.length) throw r.refuse("trailing_bytes"); }
  } else if (kind.startsWith("list<")) {
    valid = Array.isArray(value);
    if (valid) for (const item of value) _serviceCheck(kind.slice(5,-1), item, depth + 1);
  } else if (kind.startsWith("map<string,")) {
    valid = value !== null && typeof value === "object" && !Array.isArray(value);
    if (valid) for (const [key,item] of Object.entries(value)) { _serviceCheck("string",key,depth+1); _serviceCheck(kind.slice(11,-1),item,depth+1); }
  } else {
    const fields = _serviceRecords[kind];
    valid = fields !== undefined && value !== null && typeof value === "object" && !Array.isArray(value);
    if (valid) for (const [name,type,omit] of fields) {
      if (!Object.hasOwn(value,name)) throw new Refusal("missing_field",0);
      const item = value[name];
      if (omit === "absent" && item === null) continue;
      _serviceCheck(type,item,depth+1);
    }
  }
  if (!valid) throw new Refusal("wrong_type", 0);
}

const _serviceRecords = Object.create(null);
_serviceRecords["Question"] = [["asker","string","never"],["key","string","never"],["slots","map<string,string>","zero"],];
_serviceRecords["Request"] = [["op","string","never"],["ask","Question","absent"],["wait","bool","zero"],["id","string","absent"],["option","string","absent"],["admin","string","absent"],];
_serviceRecords["Answer"] = [["id","string","never"],["pending","bool","zero"],["option","string","absent"],["yes","bool","zero"],["kept","bool","zero"],];
_serviceRecords["RecordMetadata"] = [["id","string","never"],["asker","string","never"],["key","string","never"],["about","string","absent"],["text","string","never"],["options","list<string>","never"],["asked","string","never"],["option","string","absent"],["answered","string","absent"],["kept","bool","zero"],["yes","bool","zero"],];
_serviceRecords["ResponseMetadata"] = [["code","string","absent"],["error","string","absent"],["answer","Answer","absent"],["records","list<RecordMetadata>","zero"],];
_serviceRecords["ApplicationQuestion"] = [["requestKey","string","never"],["key","string","never"],["slots","map<string,string>","never"],];
_serviceRecords["QuestionObservation"] = [["outcome","string","never"],["answer","Answer","absent"],];
_serviceRecords["OperatorPage"] = [["outcome","string","never"],["records","list<RecordMetadata>","never"],["next","string","never"],["complete","bool","never"],];
_serviceRecords["OperatorDecision"] = [["outcome","string","never"],["record","RecordMetadata","absent"],];
_serviceRecords["OperatorRetirement"] = [["outcome","string","never"],["record","RecordMetadata","absent"],];
_serviceRecords["OAQuestionApplicationAskArguments"] = [["question","ApplicationQuestion","never"],];
_serviceRecords["OAQuestionApplicationObserveArguments"] = [["requestKey","string","never"],["waitMs","i64","never"],];
_serviceRecords["OAQuestionOperatorListQuestionsArguments"] = [["cursor","string","never"],["limit","i64","never"],];
_serviceRecords["OAQuestionOperatorAnswerQuestionArguments"] = [["id","string","never"],["option","string","never"],];
_serviceRecords["OAQuestionOperatorRetireQuestionArguments"] = [["id","string","never"],];
_serviceRecords["OAServiceFrame"] = [["version","i32","never"],["service","string","never"],["method","string","never"],["arguments","json","never"],];
_serviceRecords["OAServiceReply"] = [["version","i32","never"],["service","string","never"],["method","string","never"],["ok","bool","never"],["payload","json","never"],];
_serviceRecords["OAServiceError"] = [["code","string","never"],["message","string","never"],];
_serviceRecords["OAQuestionApplicationAskResult"] = [["value","QuestionObservation","never"],];
_serviceRecords["OAQuestionApplicationObserveResult"] = [["value","QuestionObservation","never"],];
_serviceRecords["OAQuestionOperatorListQuestionsResult"] = [["value","OperatorPage","never"],];
_serviceRecords["OAQuestionOperatorAnswerQuestionResult"] = [["value","OperatorDecision","never"],];
_serviceRecords["OAQuestionOperatorRetireQuestionResult"] = [["value","OperatorRetirement","never"],];

function _serviceRequest(service, method, argumentsBytes) {
  return _serviceEncode(writeOAServiceFrame, {
    version:1, service, method, arguments:new TextDecoder("utf-8",{fatal:true}).decode(argumentsBytes)
  },0);
}

function _serviceResponse(frame, service, method) {
  if (!(frame instanceof Uint8Array)) throw new TypeError("transport frame must be Uint8Array");
  const reply = _serviceDecode(readOAServiceReply, frame, 0);
  if (reply.version !== 1) throw new DispatchError("unknown_version");
  if (reply.service !== service || reply.method !== method) throw new DispatchError("mismatched_response");
  if (!reply.ok) {
    const error = _serviceDecode(readOAServiceError, reply.payload, 1);
    if (!error.code) throw new DispatchError("invalid_error");
    throw new ServiceError(error.code, error.message);
  }
  return reply.payload;
}

export class QuestionApplicationClient {
  constructor(transport) { this._transport = transport; }

  async ask(question) {
    const _args = newOAQuestionApplicationAskArguments();
    _args.question = question;
    _serviceCheck("OAQuestionApplicationAskArguments", _args);
    const _payload = _serviceEncode(writeOAQuestionApplicationAskArguments, _args, 1);
    _serviceDecode(readOAQuestionApplicationAskArguments, _payload, 1);
    const _request = _serviceRequest("abstraction.asks/application@1", "Ask", _payload);
    const _reply = _serviceResponse(await this._transport.exchangeFrame(_request), "abstraction.asks/application@1", "Ask");
    const _result = _serviceDecode(readOAQuestionApplicationAskResult, _reply, 1);
    return _result.value;
  }

  async observe(requestKey, waitMs) {
    const _args = newOAQuestionApplicationObserveArguments();
    _args.requestKey = requestKey;
    _args.waitMs = waitMs;
    _serviceCheck("OAQuestionApplicationObserveArguments", _args);
    const _payload = _serviceEncode(writeOAQuestionApplicationObserveArguments, _args, 1);
    _serviceDecode(readOAQuestionApplicationObserveArguments, _payload, 1);
    const _request = _serviceRequest("abstraction.asks/application@1", "Observe", _payload);
    const _reply = _serviceResponse(await this._transport.exchangeFrame(_request), "abstraction.asks/application@1", "Observe");
    const _result = _serviceDecode(readOAQuestionApplicationObserveResult, _reply, 1);
    return _result.value;
  }
}
export const QuestionApplicationService = Object.freeze({wireName:"abstraction.asks/application@1",Client:QuestionApplicationClient});

export class QuestionOperatorClient {
  constructor(transport) { this._transport = transport; }

  async listQuestions(cursor, limit) {
    const _args = newOAQuestionOperatorListQuestionsArguments();
    _args.cursor = cursor;
    _args.limit = limit;
    _serviceCheck("OAQuestionOperatorListQuestionsArguments", _args);
    const _payload = _serviceEncode(writeOAQuestionOperatorListQuestionsArguments, _args, 1);
    _serviceDecode(readOAQuestionOperatorListQuestionsArguments, _payload, 1);
    const _request = _serviceRequest("abstraction.asks/operator@1", "ListQuestions", _payload);
    const _reply = _serviceResponse(await this._transport.exchangeFrame(_request), "abstraction.asks/operator@1", "ListQuestions");
    const _result = _serviceDecode(readOAQuestionOperatorListQuestionsResult, _reply, 1);
    return _result.value;
  }

  async answerQuestion(id, option) {
    const _args = newOAQuestionOperatorAnswerQuestionArguments();
    _args.id = id;
    _args.option = option;
    _serviceCheck("OAQuestionOperatorAnswerQuestionArguments", _args);
    const _payload = _serviceEncode(writeOAQuestionOperatorAnswerQuestionArguments, _args, 1);
    _serviceDecode(readOAQuestionOperatorAnswerQuestionArguments, _payload, 1);
    const _request = _serviceRequest("abstraction.asks/operator@1", "AnswerQuestion", _payload);
    const _reply = _serviceResponse(await this._transport.exchangeFrame(_request), "abstraction.asks/operator@1", "AnswerQuestion");
    const _result = _serviceDecode(readOAQuestionOperatorAnswerQuestionResult, _reply, 1);
    return _result.value;
  }

  async retireQuestion(id) {
    const _args = newOAQuestionOperatorRetireQuestionArguments();
    _args.id = id;
    _serviceCheck("OAQuestionOperatorRetireQuestionArguments", _args);
    const _payload = _serviceEncode(writeOAQuestionOperatorRetireQuestionArguments, _args, 1);
    _serviceDecode(readOAQuestionOperatorRetireQuestionArguments, _payload, 1);
    const _request = _serviceRequest("abstraction.asks/operator@1", "RetireQuestion", _payload);
    const _reply = _serviceResponse(await this._transport.exchangeFrame(_request), "abstraction.asks/operator@1", "RetireQuestion");
    const _result = _serviceDecode(readOAQuestionOperatorRetireQuestionResult, _reply, 1);
    return _result.value;
  }
}
export const QuestionOperatorService = Object.freeze({wireName:"abstraction.asks/operator@1",Client:QuestionOperatorClient});
