# Code generated by abstraction-idl from abstraction-asks/asks.thrift. DO NOT EDIT.

from __future__ import annotations

import dataclasses
import enum

_HEX = b"0123456789abcdef"
_WS = (0x20, 0x09, 0x0A, 0x0D)
_SHORT = {0x22: b'\\"', 0x5C: b"\\\\", 0x08: b"\\b", 0x0C: b"\\f",
          0x0A: b"\\n", 0x0D: b"\\r", 0x09: b"\\t"}


def _esc_byte(out, c):
    short = _SHORT.get(c)
    if short is not None:
        out += short
    elif c < 0x20:
        out += b"\\u00" + bytes([_HEX[c >> 4], _HEX[c & 0xF]])
    else:
        out.append(c)


def _num(out, n):
    out += str(int(n)).encode("ascii")


def _pad(out, depth):
    out += b" " * (depth * 2)


def _strs(out, v, depth):
    if not v:
        out += b"[]"
        return
    out += b"[\n"
    for i, s in enumerate(v):
        _pad(out, depth + 1)
        _esc(out, s)
        if i + 1 < len(v):
            out += b","
        out += b"\n"
    _pad(out, depth)
    out += b"]"


def _raw(out, s, depth):
    b = s.encode("utf-8") if isinstance(s, str) else s
    i, n = 0, len(b)
    while i < n:
        c = b[i]
        if c in _WS:
            i += 1
        elif c == 0x22:
            j = i + 1
            while j < n:
                if b[j] == 0x5C:
                    j += 2
                    continue
                if b[j] == 0x22:
                    j += 1
                    break
                j += 1
            out += b[i:j]
            i = j
        elif c in (0x7B, 0x5B):
            out.append(c)
            i += 1
            j = i
            while j < n and b[j] in _WS:
                j += 1
            if j < n and b[j] in (0x7D, 0x5D):
                out.append(b[j])
                i = j + 1
            else:
                depth += 1
                out += b"\n"
                _pad(out, depth)
        elif c in (0x7D, 0x5D):
            depth -= 1
            out += b"\n"
            _pad(out, depth)
            out.append(c)
            i += 1
        elif c == 0x2C:
            out += b",\n"
            _pad(out, depth)
            i += 1
        elif c == 0x3A:
            out += b": "
            i += 1
        else:
            out.append(c)
            i += 1


def _rawmap(out, m, depth):
    keys = sorted(m, key=lambda k: k.encode("utf-8"))
    if not keys:
        out += b"{}"
        return
    out += b"{\n"
    for i, k in enumerate(keys):
        _pad(out, depth + 1)
        _esc(out, k)
        out += b": "
        _raw(out, m[k], depth + 1)
        if i + 1 < len(keys):
            out += b","
        out += b"\n"
    _pad(out, depth)
    out += b"}"

def _esc(out, s):
    out += b'"'
    for c in s.encode("utf-8"):
        _esc_byte(out, c)
    out += b'"'


def _strmap(out, m, depth):
    keys = sorted(m, key=lambda k: k.encode("utf-8"))
    if not keys:
        out += b"{}"
        return
    out += b"{\n"
    for i, k in enumerate(keys):
        _pad(out, depth + 1)
        _esc(out, k)
        out += b": "
        _esc(out, m[k])
        if i + 1 < len(keys):
            out += b","
        out += b"\n"
    _pad(out, depth)
    out += b"}"


def _write_list(out, v, depth, enc):
    if not v:
        out += b"[]"
        return
    out += b"[\n"
    for i, x in enumerate(v):
        _pad(out, depth + 1)
        enc(out, x, depth + 1)
        if i + 1 < len(v):
            out += b","
        out += b"\n"
    _pad(out, depth)
    out += b"]"


try:
    from enum import StrEnum as _StrEnum
except ImportError:  # Python 3.10
    class _StrEnum(str, enum.Enum):
        def __str__(self):
            return self.value


def _closed_enum(cls, value):
    if value is not None and not isinstance(value, str):
        raise Refusal("wrong_type", 0)
    try:
        cls(value)
    except ValueError:
        raise Refusal("bad_enum", 0) from None


def _open_enum(cls, value):
    try:
        return cls(value)
    except ValueError:
        return value


class ObservationOutcome(_StrEnum):
    PENDING = "pending"
    ANSWERED = "answered"
    UNKNOWN = "unknown"
    GONE = "gone"
    INVALID = "invalid"
    CONFLICT = "conflict"
    FORBIDDEN = "forbidden"
    UNAVAILABLE = "unavailable"


class OperatorPageOutcome(_StrEnum):
    PAGE = "page"
    GAP = "gap"
    INVALID = "invalid"
    FORBIDDEN = "forbidden"
    UNAVAILABLE = "unavailable"


class OperatorDecisionOutcome(_StrEnum):
    ANSWERED = "answered"
    CONFLICT = "conflict"
    UNKNOWN = "unknown"
    INVALID = "invalid"
    FORBIDDEN = "forbidden"
    UNAVAILABLE = "unavailable"


class OperatorRetirementOutcome(_StrEnum):
    RETIRED = "retired"
    UNKNOWN = "unknown"
    INVALID = "invalid"
    FORBIDDEN = "forbidden"
    UNAVAILABLE = "unavailable"


class ServiceErrorCode(_StrEnum):
    HANDLER_ERROR = "handler_error"
    INVALID_RESULT = "invalid_result"
    UNKNOWN_VERSION = "unknown_version"
    UNKNOWN_SERVICE = "unknown_service"
    UNKNOWN_METHOD = "unknown_method"
    WRONG_MODE = "wrong_mode"


OPERATIONS = ["ask", "pending", "answered", "answer", "forget"]


REFUSAL_CODES = ["internal", "invalid_request", "caller_refused", "unknown_operation", "not_administrator", "withdrawn", "unknown_question", "unknown_option", "bad_slot", "nothing_pending", "no_record"]


RESOURCE_ACTIONS = ["abstraction.asks/question.ask"]


@dataclasses.dataclass(kw_only=True)
class Question:
    """Own Ask fields. The service owns question text/options; callers supply a
    known key and slots. Native Ask.For carries optional peer observation
    evidence and remains a transport supplement, never caller authority."""

    asker: str = ""
    key: str = ""
    slots: dict[str, str] = dataclasses.field(default_factory=dict)


@dataclasses.dataclass(kw_only=True)
class Request:
    """Existing question operation concepts. Wait cancellation belongs to the
    native client context. This metadata descriptor does not replace the
    existing handwritten line transport."""

    op: str = ""
    ask: Question | None = None
    wait: bool = False
    id: str = ""
    option: str = ""
    admin: str = ""


@dataclasses.dataclass(kw_only=True)
class Answer:
    id: str = ""
    pending: bool = False
    option: str = ""
    yes: bool = False
    kept: bool = False


@dataclasses.dataclass(kw_only=True)
class RecordMetadata:
    """Own question-history fields; timestamps retain existing RFC3339
    representation. Native Record includes Via/For Seen evidence from shared
    identity. Empty option means pending."""

    id: str = ""
    asker: str = ""
    key: str = ""
    about: str = ""
    text: str = ""
    options: list[str] = dataclasses.field(default_factory=list)
    asked: str = ""
    option: str = ""
    answered: str = ""
    kept: bool = False
    yes: bool = False


@dataclasses.dataclass(kw_only=True)
class ResponseMetadata:
    """Own response projection. Any nonempty code/error refuses, including unknown
    future codes. Evidence supplement and existing wire handling remain native;
    no generated complete service interface is claimed."""

    code: str = ""
    error: str = ""
    answer: Answer | None = None
    records: list[RecordMetadata] = dataclasses.field(default_factory=list)


@dataclasses.dataclass(kw_only=True)
class ApplicationQuestion:
    """Stable caller-owned request key (1..128 UTF-8 bytes, no control characters),
    known question key and exactly its declared slots. Each slot is one line of
    at most 200 Unicode characters. No asker or authority fields are accepted.
    The receiving account and executable-path proof scope the request. Retry
    uncertain submission with this same key and unchanged content; a fresh key
    requests a new admission."""

    request_key: str = ""
    key: str = ""
    slots: dict[str, str] = dataclasses.field(default_factory=dict)


@dataclasses.dataclass(kw_only=True)
class QuestionObservation:
    """Answer is present exactly for pending/answered. Pending has no
    option/yes/kept decision. Unknown is an unobserved key in this caller's
    scope. Gone retains a forgotten admission's key and never admits it again.
    Conflict means the key was previously used with different content.
    Unavailable includes storage/capacity refusal and establishes no human
    decision. Answered reports the recorded human choice; it grants no resource
    authority by itself."""

    outcome: ObservationOutcome | None = None
    answer: Answer | None = None


@dataclasses.dataclass(kw_only=True)
class OperatorPage:
    """Latest-book enumeration for an explicitly authorized operator, including
    pending and answered questions. Page has at most the requested 1..64 records
    and 256 KiB per encoded reply, with conservative record, indentation and
    envelope accounting. Complete means this snapshot was exhausted; otherwise
    next is nonempty. Refusals contain no records, next or complete flag. Opaque
    cursors (at most 256 UTF-8 bytes) bind receiving caller scope, host epoch
    and exact book revision. Change, restart or scope mismatch returns gap:
    restart from empty cursor. No historical change replay or stable snapshot
    across edits is promised. Native Via/For evidence stays server-side; display
    fields confer no authority."""

    outcome: OperatorPageOutcome | None = None
    records: list[RecordMetadata] = dataclasses.field(default_factory=list)
    next: str = ""
    complete: bool = False


@dataclasses.dataclass(kw_only=True)
class OperatorDecision:
    """Record is present exactly for answered. Same ID and option replays the
    original decision including its timestamp and kept/once meaning; another
    option conflicts. Unknown means no retained question. Invalid includes an
    unknown option or invalid ID. Unavailable establishes no decision or
    noncommit claim: retry the same ID/option or inspect fresh history.
    Answering records a human choice, never a resource grant."""

    outcome: OperatorDecisionOutcome | None = None
    record: RecordMetadata | None = None


@dataclasses.dataclass(kw_only=True)
class OperatorRetirement:
    """Retired removes a retained pending or answered question from the Book.
    Record carries its last metadata on the retiring call and is absent when
    replaying an already retired ID. A pending question retired without an
    answer carries no decision. Admission tombstones remain: application replay
    and observation of its key report gone, and that key never admits again.
    Unknown means no retained or retired question. Invalid means a malformed ID.
    Unavailable establishes no retirement claim: retry the same ID or inspect
    fresh history."""

    outcome: OperatorRetirementOutcome | None = None
    record: RecordMetadata | None = None


@dataclasses.dataclass(kw_only=True)
class _QuestionApplicationAskArguments:
    question: ApplicationQuestion = dataclasses.field(default_factory=ApplicationQuestion)


@dataclasses.dataclass(kw_only=True)
class _QuestionApplicationObserveArguments:
    request_key: str = ""
    wait_ms: int = 0


@dataclasses.dataclass(kw_only=True)
class _QuestionOperatorListQuestionsArguments:
    cursor: str = ""
    limit: int = 0


@dataclasses.dataclass(kw_only=True)
class _QuestionOperatorAnswerQuestionArguments:
    id: str = ""
    option: str = ""


@dataclasses.dataclass(kw_only=True)
class _QuestionOperatorRetireQuestionArguments:
    id: str = ""


@dataclasses.dataclass(kw_only=True)
class _ServiceFrame:
    version: int = 0
    service: str = ""
    method: str = ""
    arguments: bytes | str = ""


@dataclasses.dataclass(kw_only=True)
class _ServiceReply:
    version: int = 0
    service: str = ""
    method: str = ""
    ok: bool = False
    payload: bytes | str = ""


@dataclasses.dataclass(kw_only=True)
class _ServiceError:
    code: str = ""
    message: str = ""


@dataclasses.dataclass(kw_only=True)
class _QuestionApplicationAskResult:
    value: QuestionObservation = dataclasses.field(default_factory=QuestionObservation)


@dataclasses.dataclass(kw_only=True)
class _QuestionApplicationObserveResult:
    value: QuestionObservation = dataclasses.field(default_factory=QuestionObservation)


@dataclasses.dataclass(kw_only=True)
class _QuestionOperatorListQuestionsResult:
    value: OperatorPage = dataclasses.field(default_factory=OperatorPage)


@dataclasses.dataclass(kw_only=True)
class _QuestionOperatorAnswerQuestionResult:
    value: OperatorDecision = dataclasses.field(default_factory=OperatorDecision)


@dataclasses.dataclass(kw_only=True)
class _QuestionOperatorRetireQuestionResult:
    value: OperatorRetirement = dataclasses.field(default_factory=OperatorRetirement)


def _write_question(out, v, depth):
    out += b"{"
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "asker")
    out += b": "
    _esc(out, v.asker)
    out += b","
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "key")
    out += b": "
    _esc(out, v.key)
    if v.slots:
        out += b","
        out += b"\n"
        _pad(out, depth + 1)
        _esc(out, "slots")
        out += b": "
        _strmap(out, v.slots, depth + 1)
    out += b"\n"
    _pad(out, depth)
    out += b"}"


def _write_request(out, v, depth):
    out += b"{"
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "op")
    out += b": "
    _esc(out, v.op)
    if v.ask is not None:
        out += b","
        out += b"\n"
        _pad(out, depth + 1)
        _esc(out, "ask")
        out += b": "
        _write_question(out, v.ask, depth + 1)
    if v.wait:
        out += b","
        out += b"\n"
        _pad(out, depth + 1)
        _esc(out, "wait")
        out += b": "
        out += b"true" if v.wait else b"false"
    if v.id:
        out += b","
        out += b"\n"
        _pad(out, depth + 1)
        _esc(out, "id")
        out += b": "
        _esc(out, v.id)
    if v.option:
        out += b","
        out += b"\n"
        _pad(out, depth + 1)
        _esc(out, "option")
        out += b": "
        _esc(out, v.option)
    if v.admin:
        out += b","
        out += b"\n"
        _pad(out, depth + 1)
        _esc(out, "admin")
        out += b": "
        _esc(out, v.admin)
    out += b"\n"
    _pad(out, depth)
    out += b"}"


def _write_answer(out, v, depth):
    out += b"{"
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "id")
    out += b": "
    _esc(out, v.id)
    if v.pending:
        out += b","
        out += b"\n"
        _pad(out, depth + 1)
        _esc(out, "pending")
        out += b": "
        out += b"true" if v.pending else b"false"
    if v.option:
        out += b","
        out += b"\n"
        _pad(out, depth + 1)
        _esc(out, "option")
        out += b": "
        _esc(out, v.option)
    if v.yes:
        out += b","
        out += b"\n"
        _pad(out, depth + 1)
        _esc(out, "yes")
        out += b": "
        out += b"true" if v.yes else b"false"
    if v.kept:
        out += b","
        out += b"\n"
        _pad(out, depth + 1)
        _esc(out, "kept")
        out += b": "
        out += b"true" if v.kept else b"false"
    out += b"\n"
    _pad(out, depth)
    out += b"}"


def _write_record_metadata(out, v, depth):
    out += b"{"
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "id")
    out += b": "
    _esc(out, v.id)
    out += b","
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "asker")
    out += b": "
    _esc(out, v.asker)
    out += b","
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "key")
    out += b": "
    _esc(out, v.key)
    if v.about:
        out += b","
        out += b"\n"
        _pad(out, depth + 1)
        _esc(out, "about")
        out += b": "
        _esc(out, v.about)
    out += b","
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "text")
    out += b": "
    _esc(out, v.text)
    out += b","
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "options")
    out += b": "
    _strs(out, v.options, depth + 1)
    out += b","
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "asked")
    out += b": "
    _esc(out, v.asked)
    if v.option:
        out += b","
        out += b"\n"
        _pad(out, depth + 1)
        _esc(out, "option")
        out += b": "
        _esc(out, v.option)
    if v.answered:
        out += b","
        out += b"\n"
        _pad(out, depth + 1)
        _esc(out, "answered")
        out += b": "
        _esc(out, v.answered)
    if v.kept:
        out += b","
        out += b"\n"
        _pad(out, depth + 1)
        _esc(out, "kept")
        out += b": "
        out += b"true" if v.kept else b"false"
    if v.yes:
        out += b","
        out += b"\n"
        _pad(out, depth + 1)
        _esc(out, "yes")
        out += b": "
        out += b"true" if v.yes else b"false"
    out += b"\n"
    _pad(out, depth)
    out += b"}"


def _write_response_metadata(out, v, depth):
    out += b"{"
    first = True
    if v.code:
        first = False
        out += b"\n"
        _pad(out, depth + 1)
        _esc(out, "code")
        out += b": "
        _esc(out, v.code)
    if v.error:
        if not first:
            out += b","
        first = False
        out += b"\n"
        _pad(out, depth + 1)
        _esc(out, "error")
        out += b": "
        _esc(out, v.error)
    if v.answer is not None:
        if not first:
            out += b","
        first = False
        out += b"\n"
        _pad(out, depth + 1)
        _esc(out, "answer")
        out += b": "
        _write_answer(out, v.answer, depth + 1)
    if v.records:
        if not first:
            out += b","
        first = False
        out += b"\n"
        _pad(out, depth + 1)
        _esc(out, "records")
        out += b": "
        _write_list(out, v.records, depth + 1, _write_record_metadata)
    if not first:
        out += b"\n"
        _pad(out, depth)
    out += b"}"


def _write_application_question(out, v, depth):
    out += b"{"
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "request_key")
    out += b": "
    _esc(out, v.request_key)
    out += b","
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "key")
    out += b": "
    _esc(out, v.key)
    out += b","
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "slots")
    out += b": "
    _strmap(out, v.slots, depth + 1)
    out += b"\n"
    _pad(out, depth)
    out += b"}"


def _write_question_observation(out, v, depth):
    _closed_enum(ObservationOutcome, v.outcome)
    out += b"{"
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "outcome")
    out += b": "
    _esc(out, v.outcome)
    if v.answer is not None:
        out += b","
        out += b"\n"
        _pad(out, depth + 1)
        _esc(out, "answer")
        out += b": "
        _write_answer(out, v.answer, depth + 1)
    out += b"\n"
    _pad(out, depth)
    out += b"}"


def _write_operator_page(out, v, depth):
    _closed_enum(OperatorPageOutcome, v.outcome)
    out += b"{"
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "outcome")
    out += b": "
    _esc(out, v.outcome)
    out += b","
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "records")
    out += b": "
    _write_list(out, v.records, depth + 1, _write_record_metadata)
    out += b","
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "next")
    out += b": "
    _esc(out, v.next)
    out += b","
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "complete")
    out += b": "
    out += b"true" if v.complete else b"false"
    out += b"\n"
    _pad(out, depth)
    out += b"}"


def _write_operator_decision(out, v, depth):
    _closed_enum(OperatorDecisionOutcome, v.outcome)
    out += b"{"
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "outcome")
    out += b": "
    _esc(out, v.outcome)
    if v.record is not None:
        out += b","
        out += b"\n"
        _pad(out, depth + 1)
        _esc(out, "record")
        out += b": "
        _write_record_metadata(out, v.record, depth + 1)
    out += b"\n"
    _pad(out, depth)
    out += b"}"


def _write_operator_retirement(out, v, depth):
    _closed_enum(OperatorRetirementOutcome, v.outcome)
    out += b"{"
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "outcome")
    out += b": "
    _esc(out, v.outcome)
    if v.record is not None:
        out += b","
        out += b"\n"
        _pad(out, depth + 1)
        _esc(out, "record")
        out += b": "
        _write_record_metadata(out, v.record, depth + 1)
    out += b"\n"
    _pad(out, depth)
    out += b"}"


def _write_oa_question_application_ask_arguments(out, v, depth):
    out += b"{"
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "question")
    out += b": "
    _write_application_question(out, v.question, depth + 1)
    out += b"\n"
    _pad(out, depth)
    out += b"}"


def _write_oa_question_application_observe_arguments(out, v, depth):
    out += b"{"
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "request_key")
    out += b": "
    _esc(out, v.request_key)
    out += b","
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "wait_ms")
    out += b": "
    _num(out, v.wait_ms)
    out += b"\n"
    _pad(out, depth)
    out += b"}"


def _write_oa_question_operator_list_questions_arguments(out, v, depth):
    out += b"{"
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "cursor")
    out += b": "
    _esc(out, v.cursor)
    out += b","
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "limit")
    out += b": "
    _num(out, v.limit)
    out += b"\n"
    _pad(out, depth)
    out += b"}"


def _write_oa_question_operator_answer_question_arguments(out, v, depth):
    out += b"{"
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "id")
    out += b": "
    _esc(out, v.id)
    out += b","
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "option")
    out += b": "
    _esc(out, v.option)
    out += b"\n"
    _pad(out, depth)
    out += b"}"


def _write_oa_question_operator_retire_question_arguments(out, v, depth):
    out += b"{"
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "id")
    out += b": "
    _esc(out, v.id)
    out += b"\n"
    _pad(out, depth)
    out += b"}"


def _write_oa_service_frame(out, v, depth):
    out += b"{"
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "version")
    out += b": "
    _num(out, v.version)
    out += b","
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "service")
    out += b": "
    _esc(out, v.service)
    out += b","
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "method")
    out += b": "
    _esc(out, v.method)
    out += b","
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "arguments")
    out += b": "
    out += v.arguments.encode("utf-8") if isinstance(v.arguments, str) else v.arguments
    out += b"\n"
    _pad(out, depth)
    out += b"}"


def _write_oa_service_reply(out, v, depth):
    out += b"{"
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "version")
    out += b": "
    _num(out, v.version)
    out += b","
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "service")
    out += b": "
    _esc(out, v.service)
    out += b","
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "method")
    out += b": "
    _esc(out, v.method)
    out += b","
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "ok")
    out += b": "
    out += b"true" if v.ok else b"false"
    out += b","
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "payload")
    out += b": "
    out += v.payload.encode("utf-8") if isinstance(v.payload, str) else v.payload
    out += b"\n"
    _pad(out, depth)
    out += b"}"


def _write_oa_service_error(out, v, depth):
    out += b"{"
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "code")
    out += b": "
    _esc(out, v.code)
    out += b","
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "message")
    out += b": "
    _esc(out, v.message)
    out += b"\n"
    _pad(out, depth)
    out += b"}"


def _write_oa_question_application_ask_result(out, v, depth):
    out += b"{"
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "value")
    out += b": "
    _write_question_observation(out, v.value, depth + 1)
    out += b"\n"
    _pad(out, depth)
    out += b"}"


def _write_oa_question_application_observe_result(out, v, depth):
    out += b"{"
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "value")
    out += b": "
    _write_question_observation(out, v.value, depth + 1)
    out += b"\n"
    _pad(out, depth)
    out += b"}"


def _write_oa_question_operator_list_questions_result(out, v, depth):
    out += b"{"
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "value")
    out += b": "
    _write_operator_page(out, v.value, depth + 1)
    out += b"\n"
    _pad(out, depth)
    out += b"}"


def _write_oa_question_operator_answer_question_result(out, v, depth):
    out += b"{"
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "value")
    out += b": "
    _write_operator_decision(out, v.value, depth + 1)
    out += b"\n"
    _pad(out, depth)
    out += b"}"


def _write_oa_question_operator_retire_question_result(out, v, depth):
    out += b"{"
    out += b"\n"
    _pad(out, depth + 1)
    _esc(out, "value")
    out += b": "
    _write_operator_retirement(out, v.value, depth + 1)
    out += b"\n"
    _pad(out, depth)
    out += b"}"


def encode(v):
    out = bytearray()
    _write_request(out, v, 0)
    out += b"\n"
    return bytes(out)


_QUOTE, _BACKSLASH, _COLON, _COMMA = 0x22, 0x5C, 0x3A, 0x2C
_LBRACE, _RBRACE, _LBRACK, _RBRACK = 0x7B, 0x7D, 0x5B, 0x5D
_MINUS, _ZERO, _NINE, _DOT, _LOWER_U, _LOWER_N = 0x2D, 0x30, 0x39, 0x2E, 0x75, 0x6E
_UNESCAPE = {0x22: 0x22, 0x5C: 0x5C, 0x2F: 0x2F, 0x62: 0x08,
             0x66: 0x0C, 0x6E: 0x0A, 0x72: 0x0D, 0x74: 0x09}
_DEPTH_LIMIT = 64
_I64_DIGITS = 19


class Refusal(ValueError):
    """Bytes the contract refuses: word names the rule, offset the byte."""

    def __init__(self, word, offset):
        super().__init__("refused: %s at byte %d" % (word, offset))
        self.word = word
        self.offset = offset


class _Reader:
    __slots__ = ("buf", "pos", "depth")

    def __init__(self, buf):
        self.buf = buf
        self.pos = 0
        self.depth = 0

    def refuse(self, word):
        return Refusal(word, self.pos)

    def at(self):
        return self.buf[self.pos] if self.pos < len(self.buf) else 0

    def ws(self):
        while self.pos < len(self.buf) and self.buf[self.pos] in _WS:
            self.pos += 1

    def enter(self):
        self.depth += 1
        if self.depth > _DEPTH_LIMIT:
            raise self.refuse("depth_exceeded")

    def digit(self):
        return _ZERO <= self.at() <= _NINE

    def string(self):
        if self.at() != _QUOTE:
            raise self.refuse("wrong_type")
        self.pos += 1
        out = bytearray()
        while True:
            if self.pos >= len(self.buf):
                raise self.refuse("malformed")
            c = self.buf[self.pos]
            if c == _QUOTE:
                self.pos += 1
                try:
                    return out.decode("utf-8")
                except UnicodeDecodeError:
                    raise self.refuse("bad_string") from None
            if c < 0x20:
                raise self.refuse("bad_string")
            if c == _BACKSLASH:
                self.escape(out)
            else:
                out.append(c)
                self.pos += 1

    def escape(self, out):
        self.pos += 1
        if self.pos >= len(self.buf):
            raise self.refuse("malformed")
        c = self.buf[self.pos]
        self.pos += 1
        plain = _UNESCAPE.get(c)
        if plain is not None:
            out.append(plain)
            return
        if c != _LOWER_U:
            raise self.refuse("bad_string")
        u = self.hex4()
        if 0xDC00 <= u <= 0xDFFF:
            raise self.refuse("bad_string")
        if 0xD800 <= u <= 0xDBFF:
            if (self.pos + 1 >= len(self.buf) or self.buf[self.pos] != _BACKSLASH
                    or self.buf[self.pos + 1] != _LOWER_U):
                raise self.refuse("bad_string")
            self.pos += 2
            low = self.hex4()
            if not 0xDC00 <= low <= 0xDFFF:
                raise self.refuse("bad_string")
            u = 0x10000 + ((u - 0xD800) << 10) + (low - 0xDC00)
        out += chr(u).encode("utf-8")

    def hex4(self):
        if self.pos + 4 > len(self.buf):
            raise self.refuse("bad_string")
        u = 0
        for i in range(4):
            c = self.buf[self.pos + i]
            if _ZERO <= c <= _NINE:
                u = u << 4 | (c - _ZERO)
            elif 0x61 <= c <= 0x66:
                u = u << 4 | (c - 0x61 + 10)
            elif 0x41 <= c <= 0x46:
                u = u << 4 | (c - 0x41 + 10)
            else:
                raise self.refuse("bad_string")
        self.pos += 4
        return u

    def integer(self, low, high):
        c = self.at()
        if c != _MINUS and not _ZERO <= c <= _NINE:
            raise self.refuse("wrong_type")
        negative = c == _MINUS
        if negative:
            self.pos += 1
        if not self.digit():
            raise self.refuse("malformed")
        start = self.pos
        if self.at() == _ZERO:
            self.pos += 1
        else:
            while self.digit():
                self.pos += 1
        if self.at() in (_DOT, 0x65, 0x45) or self.digit():
            raise self.refuse("number_spelling")
        if self.pos - start > _I64_DIGITS:
            raise self.refuse("number_spelling")
        n = int(self.buf[start:self.pos])
        if negative:
            if n == 0:
                raise self.refuse("number_spelling")
            n = -n
        if n < low or n > high:
            raise self.refuse("number_spelling")
        return n

    def boolean(self):
        if self.at() == 0x74:
            self.literal(b"true")
            return True
        if self.at() == 0x66:
            self.literal(b"false")
            return False
        raise self.refuse("wrong_type")

    def literal(self, word):
        if self.buf[self.pos:self.pos + len(word)] != word:
            raise self.refuse("malformed")
        self.pos += len(word)

    def str_list(self):
        if self.at() != _LBRACK:
            raise self.refuse("wrong_type")
        self.enter()
        self.pos += 1
        out = []
        self.ws()
        if self.at() != _RBRACK:
            while True:
                self.ws()
                out.append(self.string())
                self.ws()
                if self.at() != _COMMA:
                    break
                self.pos += 1
        if self.at() != _RBRACK:
            raise self.refuse("malformed")
        self.pos += 1
        self.depth -= 1
        return out

    def raw_map(self):
        if self.at() != _LBRACE:
            raise self.refuse("wrong_type")
        self.enter()
        self.pos += 1
        out = {}
        self.ws()
        if self.at() != _RBRACE:
            while True:
                self.ws()
                if self.at() != _QUOTE:
                    raise self.refuse("malformed")
                k = self.string()
                if k in out:
                    raise self.refuse("duplicate_key")
                self.ws()
                if self.at() != _COLON:
                    raise self.refuse("malformed")
                self.pos += 1
                self.ws()
                out[k] = self.raw_value()
                self.ws()
                if self.at() != _COMMA:
                    break
                self.pos += 1
        if self.at() != _RBRACE:
            raise self.refuse("malformed")
        self.pos += 1
        self.depth -= 1
        return out

    def raw_value(self):
        start = self.pos
        self.skip_value()
        return self.buf[start:self.pos]

    def skip_value(self):
        c = self.at()
        if c == _QUOTE:
            self.skip_string()
        elif c in (_LBRACE, _LBRACK):
            self.skip_container()
        elif c == 0x74:
            self.literal(b"true")
        elif c == 0x66:
            self.literal(b"false")
        elif c == 0x6E:
            self.literal(b"null")
        elif c == _MINUS or _ZERO <= c <= _NINE:
            self.skip_number()
        else:
            raise self.refuse("malformed")

    # An opaque value is validated and carried, never interpreted. Its syntax is
    # the record's own — the same string reader, so an escape, a control byte or
    # a lone surrogate is judged identically at any depth — and what it is free
    # to spell, it keeps: the bytes between these two offsets are what a writer
    # re-emits. A number is walked, never converted, so a value no host type
    # holds survives the reader that carried it.
    def skip_string(self):
        self.string()

    def some_digits(self):
        n = 0
        while _ZERO <= self.at() <= _NINE:
            self.pos += 1
            n += 1
        if n == 0:
            raise self.refuse("number_spelling")

    def skip_number(self):
        if self.at() == _MINUS:
            self.pos += 1
        c = self.at()
        if c == _ZERO:
            self.pos += 1
        elif _ZERO < c <= _NINE:
            while _ZERO <= self.at() <= _NINE:
                self.pos += 1
        else:
            raise self.refuse("number_spelling")
        if self.at() == _DOT:
            self.pos += 1
            self.some_digits()
        if self.at() in (0x65, 0x45):
            self.pos += 1
            if self.at() in (0x2B, _MINUS):
                self.pos += 1
            self.some_digits()

    def skip_container(self):
        opener = self.at()
        shut = _RBRACE if opener == _LBRACE else _RBRACK
        self.enter()
        self.pos += 1
        self.ws()
        seen = set()
        if self.at() != shut:
            while True:
                self.ws()
                if opener == _LBRACE:
                    if self.at() != _QUOTE:
                        raise self.refuse("malformed")
                    k = self.string()
                    if k in seen:
                        raise self.refuse("duplicate_key")
                    seen.add(k)
                    self.ws()
                    if self.at() != _COLON:
                        raise self.refuse("malformed")
                    self.pos += 1
                    self.ws()
                self.skip_value()
                self.ws()
                if self.at() != _COMMA:
                    break
                self.pos += 1
        if self.at() != shut:
            raise self.refuse("malformed")
        self.pos += 1
        self.depth -= 1

    def str_map(self):
        if self.at() != _LBRACE:
            raise self.refuse("wrong_type")
        self.enter()
        self.pos += 1
        out = {}
        self.ws()
        if self.at() != _RBRACE:
            while True:
                self.ws()
                if self.at() != _QUOTE:
                    raise self.refuse("malformed")
                k = self.string()
                if k in out:
                    raise self.refuse("duplicate_key")
                self.ws()
                if self.at() != _COLON:
                    raise self.refuse("malformed")
                self.pos += 1
                self.ws()
                out[k] = self.string()
                self.ws()
                if self.at() != _COMMA:
                    break
                self.pos += 1
        if self.at() != _RBRACE:
            raise self.refuse("malformed")
        self.pos += 1
        self.depth -= 1
        return out


def _read_list(r, elem):
    if r.at() != _LBRACK:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    out = []
    r.ws()
    if r.at() != _RBRACK:
        while True:
            r.ws()
            out.append(elem(r))
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACK:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    return out


def _read_question(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = Question()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "asker":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.asker = r.string()
            elif key == "key":
                if seen & 2:
                    raise r.refuse("duplicate_field")
                seen |= 2
                v.key = r.string()
            elif key == "slots":
                if seen & 4:
                    raise r.refuse("duplicate_field")
                seen |= 4
                v.slots = r.str_map()
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 3 != 3:
        raise r.refuse("missing_field")
    return v


def _read_request(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = Request()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "op":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.op = r.string()
            elif key == "ask":
                if seen & 2:
                    raise r.refuse("duplicate_field")
                seen |= 2
                v.ask = _read_question(r)
            elif key == "wait":
                if seen & 4:
                    raise r.refuse("duplicate_field")
                seen |= 4
                v.wait = r.boolean()
            elif key == "id":
                if seen & 8:
                    raise r.refuse("duplicate_field")
                seen |= 8
                v.id = r.string()
            elif key == "option":
                if seen & 16:
                    raise r.refuse("duplicate_field")
                seen |= 16
                v.option = r.string()
            elif key == "admin":
                if seen & 32:
                    raise r.refuse("duplicate_field")
                seen |= 32
                v.admin = r.string()
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 1 != 1:
        raise r.refuse("missing_field")
    return v


def _read_answer(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = Answer()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "id":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.id = r.string()
            elif key == "pending":
                if seen & 2:
                    raise r.refuse("duplicate_field")
                seen |= 2
                v.pending = r.boolean()
            elif key == "option":
                if seen & 4:
                    raise r.refuse("duplicate_field")
                seen |= 4
                v.option = r.string()
            elif key == "yes":
                if seen & 8:
                    raise r.refuse("duplicate_field")
                seen |= 8
                v.yes = r.boolean()
            elif key == "kept":
                if seen & 16:
                    raise r.refuse("duplicate_field")
                seen |= 16
                v.kept = r.boolean()
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 1 != 1:
        raise r.refuse("missing_field")
    return v


def _read_record_metadata(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = RecordMetadata()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "id":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.id = r.string()
            elif key == "asker":
                if seen & 2:
                    raise r.refuse("duplicate_field")
                seen |= 2
                v.asker = r.string()
            elif key == "key":
                if seen & 4:
                    raise r.refuse("duplicate_field")
                seen |= 4
                v.key = r.string()
            elif key == "about":
                if seen & 8:
                    raise r.refuse("duplicate_field")
                seen |= 8
                v.about = r.string()
            elif key == "text":
                if seen & 16:
                    raise r.refuse("duplicate_field")
                seen |= 16
                v.text = r.string()
            elif key == "options":
                if seen & 32:
                    raise r.refuse("duplicate_field")
                seen |= 32
                v.options = r.str_list()
            elif key == "asked":
                if seen & 64:
                    raise r.refuse("duplicate_field")
                seen |= 64
                v.asked = r.string()
            elif key == "option":
                if seen & 128:
                    raise r.refuse("duplicate_field")
                seen |= 128
                v.option = r.string()
            elif key == "answered":
                if seen & 256:
                    raise r.refuse("duplicate_field")
                seen |= 256
                v.answered = r.string()
            elif key == "kept":
                if seen & 512:
                    raise r.refuse("duplicate_field")
                seen |= 512
                v.kept = r.boolean()
            elif key == "yes":
                if seen & 1024:
                    raise r.refuse("duplicate_field")
                seen |= 1024
                v.yes = r.boolean()
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 119 != 119:
        raise r.refuse("missing_field")
    return v


def _read_response_metadata(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = ResponseMetadata()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "code":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.code = r.string()
            elif key == "error":
                if seen & 2:
                    raise r.refuse("duplicate_field")
                seen |= 2
                v.error = r.string()
            elif key == "answer":
                if seen & 4:
                    raise r.refuse("duplicate_field")
                seen |= 4
                v.answer = _read_answer(r)
            elif key == "records":
                if seen & 8:
                    raise r.refuse("duplicate_field")
                seen |= 8
                v.records = _read_list(r, _read_record_metadata)
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    return v


def _read_application_question(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = ApplicationQuestion()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "request_key":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.request_key = r.string()
            elif key == "key":
                if seen & 2:
                    raise r.refuse("duplicate_field")
                seen |= 2
                v.key = r.string()
            elif key == "slots":
                if seen & 4:
                    raise r.refuse("duplicate_field")
                seen |= 4
                v.slots = r.str_map()
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 7 != 7:
        raise r.refuse("missing_field")
    return v


def _read_question_observation(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = QuestionObservation()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "outcome":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.outcome = r.string()
            elif key == "answer":
                if seen & 2:
                    raise r.refuse("duplicate_field")
                seen |= 2
                v.answer = _read_answer(r)
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 1 != 1:
        raise r.refuse("missing_field")
    try:
        v.outcome = ObservationOutcome(v.outcome)
    except ValueError:
        raise r.refuse("bad_enum") from None
    return v


def _read_operator_page(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = OperatorPage()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "outcome":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.outcome = r.string()
            elif key == "records":
                if seen & 2:
                    raise r.refuse("duplicate_field")
                seen |= 2
                v.records = _read_list(r, _read_record_metadata)
            elif key == "next":
                if seen & 4:
                    raise r.refuse("duplicate_field")
                seen |= 4
                v.next = r.string()
            elif key == "complete":
                if seen & 8:
                    raise r.refuse("duplicate_field")
                seen |= 8
                v.complete = r.boolean()
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 15 != 15:
        raise r.refuse("missing_field")
    try:
        v.outcome = OperatorPageOutcome(v.outcome)
    except ValueError:
        raise r.refuse("bad_enum") from None
    return v


def _read_operator_decision(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = OperatorDecision()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "outcome":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.outcome = r.string()
            elif key == "record":
                if seen & 2:
                    raise r.refuse("duplicate_field")
                seen |= 2
                v.record = _read_record_metadata(r)
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 1 != 1:
        raise r.refuse("missing_field")
    try:
        v.outcome = OperatorDecisionOutcome(v.outcome)
    except ValueError:
        raise r.refuse("bad_enum") from None
    return v


def _read_operator_retirement(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = OperatorRetirement()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "outcome":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.outcome = r.string()
            elif key == "record":
                if seen & 2:
                    raise r.refuse("duplicate_field")
                seen |= 2
                v.record = _read_record_metadata(r)
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 1 != 1:
        raise r.refuse("missing_field")
    try:
        v.outcome = OperatorRetirementOutcome(v.outcome)
    except ValueError:
        raise r.refuse("bad_enum") from None
    return v


def _read_oa_question_application_ask_arguments(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = _QuestionApplicationAskArguments()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "question":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.question = _read_application_question(r)
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 1 != 1:
        raise r.refuse("missing_field")
    return v


def _read_oa_question_application_observe_arguments(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = _QuestionApplicationObserveArguments()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "request_key":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.request_key = r.string()
            elif key == "wait_ms":
                if seen & 2:
                    raise r.refuse("duplicate_field")
                seen |= 2
                v.wait_ms = r.integer(-9223372036854775808, 9223372036854775807)
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 3 != 3:
        raise r.refuse("missing_field")
    return v


def _read_oa_question_operator_list_questions_arguments(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = _QuestionOperatorListQuestionsArguments()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "cursor":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.cursor = r.string()
            elif key == "limit":
                if seen & 2:
                    raise r.refuse("duplicate_field")
                seen |= 2
                v.limit = r.integer(-9223372036854775808, 9223372036854775807)
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 3 != 3:
        raise r.refuse("missing_field")
    return v


def _read_oa_question_operator_answer_question_arguments(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = _QuestionOperatorAnswerQuestionArguments()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "id":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.id = r.string()
            elif key == "option":
                if seen & 2:
                    raise r.refuse("duplicate_field")
                seen |= 2
                v.option = r.string()
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 3 != 3:
        raise r.refuse("missing_field")
    return v


def _read_oa_question_operator_retire_question_arguments(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = _QuestionOperatorRetireQuestionArguments()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "id":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.id = r.string()
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 1 != 1:
        raise r.refuse("missing_field")
    return v


def _read_oa_service_frame(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = _ServiceFrame()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "version":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.version = r.integer(-2147483648, 2147483647)
            elif key == "service":
                if seen & 2:
                    raise r.refuse("duplicate_field")
                seen |= 2
                v.service = r.string()
            elif key == "method":
                if seen & 4:
                    raise r.refuse("duplicate_field")
                seen |= 4
                v.method = r.string()
            elif key == "arguments":
                if seen & 8:
                    raise r.refuse("duplicate_field")
                seen |= 8
                v.arguments = r.raw_value()
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 15 != 15:
        raise r.refuse("missing_field")
    return v


def _read_oa_service_reply(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = _ServiceReply()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "version":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.version = r.integer(-2147483648, 2147483647)
            elif key == "service":
                if seen & 2:
                    raise r.refuse("duplicate_field")
                seen |= 2
                v.service = r.string()
            elif key == "method":
                if seen & 4:
                    raise r.refuse("duplicate_field")
                seen |= 4
                v.method = r.string()
            elif key == "ok":
                if seen & 8:
                    raise r.refuse("duplicate_field")
                seen |= 8
                v.ok = r.boolean()
            elif key == "payload":
                if seen & 16:
                    raise r.refuse("duplicate_field")
                seen |= 16
                v.payload = r.raw_value()
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 31 != 31:
        raise r.refuse("missing_field")
    return v


def _read_oa_service_error(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = _ServiceError()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "code":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.code = r.string()
            elif key == "message":
                if seen & 2:
                    raise r.refuse("duplicate_field")
                seen |= 2
                v.message = r.string()
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 3 != 3:
        raise r.refuse("missing_field")
    return v


def _read_oa_question_application_ask_result(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = _QuestionApplicationAskResult()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "value":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.value = _read_question_observation(r)
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 1 != 1:
        raise r.refuse("missing_field")
    return v


def _read_oa_question_application_observe_result(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = _QuestionApplicationObserveResult()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "value":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.value = _read_question_observation(r)
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 1 != 1:
        raise r.refuse("missing_field")
    return v


def _read_oa_question_operator_list_questions_result(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = _QuestionOperatorListQuestionsResult()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "value":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.value = _read_operator_page(r)
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 1 != 1:
        raise r.refuse("missing_field")
    return v


def _read_oa_question_operator_answer_question_result(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = _QuestionOperatorAnswerQuestionResult()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "value":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.value = _read_operator_decision(r)
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 1 != 1:
        raise r.refuse("missing_field")
    return v


def _read_oa_question_operator_retire_question_result(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = _QuestionOperatorRetireQuestionResult()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "value":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.value = _read_operator_retirement(r)
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 1 != 1:
        raise r.refuse("missing_field")
    return v


def decode(data):
    r = _Reader(bytes(data))
    r.ws()
    v = _read_request(r)
    r.ws()
    if r.pos < len(r.buf):
        raise r.refuse("trailing_bytes")
    return v


# _REFUSALS is in the order two of them are chosen between.

_REFUSALS = ["malformed", "bad_string", "number_spelling", "wrong_type", "depth_exceeded", "duplicate_key", "duplicate_field", "unknown_field", "missing_field", "bad_enum", "trailing_bytes"]


def _refusal_rank(word):
    return _REFUSALS.index(word) if word in _REFUSALS else -1


class DispatchError(ValueError):
    """A frame that names no version, service or method this module speaks."""

    def __init__(self, code):
        super().__init__(code)
        self.code = code


def _service_decode(decoder, frame, depth=0):
    if not isinstance(frame, (bytes, bytearray, memoryview)):
        raise TypeError("transport frame must be bytes")
    r = _Reader(bytes(frame))
    r.depth = depth
    r.ws()
    value = decoder(r)
    r.ws()
    if r.pos != len(r.buf):
        raise r.refuse("trailing_bytes")
    return value


def _service_encode(encoder, value, depth):
    out = bytearray()
    try:
        encoder(out, value, depth)
    except UnicodeError:
        raise Refusal("bad_string", 0) from None
    return bytes(out)


def _service_request(service, method, arguments):
    v = _ServiceFrame(version=1, service=service, method=method, arguments=arguments)
    frame = _service_encode(_write_oa_service_frame, v, 0)
    _service_decode(_read_oa_service_frame, frame)
    return frame


def _service_check(kind, value, depth=0):
    # Python coercions must not silently change typed service arguments.
    if depth >= _DEPTH_LIMIT and (kind.startswith(("list<", "map<")) or kind in _SERVICE_RECORDS):
        raise Refusal("depth_exceeded", 0)
    if kind == "string":
        valid = type(value) is str
    elif kind == "enum":
        valid = value is None or isinstance(value, str)
    elif kind in ("i32", "i64"):
        valid = type(value) is int
        if valid:
            limit = 1 << (31 if kind == "i32" else 63)
            if not -limit <= value < limit:
                raise Refusal("number_spelling", 0)
    elif kind == "bool":
        valid = type(value) is bool
    elif kind == "json":
        valid = isinstance(value, (str, bytes, bytearray, memoryview))
    elif kind.startswith("list<"):
        valid = type(value) is list
        if valid:
            for item in value:
                _service_check(kind[5:-1], item, depth + 1)
    elif kind.startswith("map<string,"):
        valid = type(value) is dict
        if valid:
            for key, item in value.items():
                _service_check("string", key, depth + 1)
                _service_check(kind[11:-1], item, depth + 1)
    else:
        cls, fields = _SERVICE_RECORDS[kind]
        valid = isinstance(value, cls)
        if valid:
            for name, field_kind, omit in fields:
                if not hasattr(value, name):
                    raise Refusal("missing_field", 0)
                item = getattr(value, name)
                if omit == "absent" and item is None:
                    continue
                _service_check(field_kind, item, depth + 1)
    if not valid:
        raise Refusal("wrong_type", 0)

def service_name(frame):
    """Validate envelope/version for routing; dispatchers validate typed arguments."""
    value = _service_decode(_read_oa_service_frame, frame)
    if value.version != 1:
        raise DispatchError("unknown_version")
    return value.service



class ServiceError(Exception):
    """The service answered the call with an error code and message."""

    def __init__(self, code, message=""):
        super().__init__(message if message else code)
        self.code = code
        self.message = message


def _service_response(frame, service, method):
    reply = _service_decode(_read_oa_service_reply, frame)
    if reply.version != 1:
        raise DispatchError("unknown_version")
    if reply.service != service or reply.method != method:
        raise DispatchError("mismatched_response")
    if not reply.ok:
        error = _service_decode(_read_oa_service_error, reply.payload, 1)
        if not error.code:
            raise DispatchError("invalid_error")
        raise ServiceError(error.code, error.message)
    return reply.payload

_SERVICE_RECORDS = {
    "Question": (Question, [("asker", "string", "never"), ("key", "string", "never"), ("slots", "map<string,string>", "zero"), ]),
    "Request": (Request, [("op", "string", "never"), ("ask", "Question", "absent"), ("wait", "bool", "zero"), ("id", "string", "absent"), ("option", "string", "absent"), ("admin", "string", "absent"), ]),
    "Answer": (Answer, [("id", "string", "never"), ("pending", "bool", "zero"), ("option", "string", "absent"), ("yes", "bool", "zero"), ("kept", "bool", "zero"), ]),
    "RecordMetadata": (RecordMetadata, [("id", "string", "never"), ("asker", "string", "never"), ("key", "string", "never"), ("about", "string", "absent"), ("text", "string", "never"), ("options", "list<string>", "never"), ("asked", "string", "never"), ("option", "string", "absent"), ("answered", "string", "absent"), ("kept", "bool", "zero"), ("yes", "bool", "zero"), ]),
    "ResponseMetadata": (ResponseMetadata, [("code", "string", "absent"), ("error", "string", "absent"), ("answer", "Answer", "absent"), ("records", "list<RecordMetadata>", "zero"), ]),
    "ApplicationQuestion": (ApplicationQuestion, [("request_key", "string", "never"), ("key", "string", "never"), ("slots", "map<string,string>", "never"), ]),
    "QuestionObservation": (QuestionObservation, [("outcome", "enum", "never"), ("answer", "Answer", "absent"), ]),
    "OperatorPage": (OperatorPage, [("outcome", "enum", "never"), ("records", "list<RecordMetadata>", "never"), ("next", "string", "never"), ("complete", "bool", "never"), ]),
    "OperatorDecision": (OperatorDecision, [("outcome", "enum", "never"), ("record", "RecordMetadata", "absent"), ]),
    "OperatorRetirement": (OperatorRetirement, [("outcome", "enum", "never"), ("record", "RecordMetadata", "absent"), ]),
    "OAQuestionApplicationAskArguments": (_QuestionApplicationAskArguments, [("question", "ApplicationQuestion", "never"), ]),
    "OAQuestionApplicationObserveArguments": (_QuestionApplicationObserveArguments, [("request_key", "string", "never"), ("wait_ms", "i64", "never"), ]),
    "OAQuestionOperatorListQuestionsArguments": (_QuestionOperatorListQuestionsArguments, [("cursor", "string", "never"), ("limit", "i64", "never"), ]),
    "OAQuestionOperatorAnswerQuestionArguments": (_QuestionOperatorAnswerQuestionArguments, [("id", "string", "never"), ("option", "string", "never"), ]),
    "OAQuestionOperatorRetireQuestionArguments": (_QuestionOperatorRetireQuestionArguments, [("id", "string", "never"), ]),
    "OAServiceFrame": (_ServiceFrame, [("version", "i32", "never"), ("service", "string", "never"), ("method", "string", "never"), ("arguments", "json", "never"), ]),
    "OAServiceReply": (_ServiceReply, [("version", "i32", "never"), ("service", "string", "never"), ("method", "string", "never"), ("ok", "bool", "never"), ("payload", "json", "never"), ]),
    "OAServiceError": (_ServiceError, [("code", "string", "never"), ("message", "string", "never"), ]),
    "OAQuestionApplicationAskResult": (_QuestionApplicationAskResult, [("value", "QuestionObservation", "never"), ]),
    "OAQuestionApplicationObserveResult": (_QuestionApplicationObserveResult, [("value", "QuestionObservation", "never"), ]),
    "OAQuestionOperatorListQuestionsResult": (_QuestionOperatorListQuestionsResult, [("value", "OperatorPage", "never"), ]),
    "OAQuestionOperatorAnswerQuestionResult": (_QuestionOperatorAnswerQuestionResult, [("value", "OperatorDecision", "never"), ]),
    "OAQuestionOperatorRetireQuestionResult": (_QuestionOperatorRetireQuestionResult, [("value", "OperatorRetirement", "never"), ]),
}


class QuestionApplication:
    """Application-side human question admission and observation. Server derives
    caller scope and text, preserves native Via evidence, and owns a versioned
    bounded Book. Operator answering/history use the separately authorized
    QuestionOperator service; this application service exposes no administrative
    secret or operator methods."""

    def ask(self, question: ApplicationQuestion) -> QuestionObservation:
        """Admit or replay one caller-scoped question. No automatic retry.
        Identical key/content returns the original admission even after an
        answer marked once and a service restart. Existing unscoped kept answers
        are not promoted."""
        raise NotImplementedError

    def observe(self, request_key: str, wait_ms: int) -> QuestionObservation:
        """Observe only this caller's admission, optionally waiting 0..30000
        milliseconds. Waiting expiry may return pending. Client
        timeout/cancellation ends waiting and neither answers nor cancels the
        question. Default SDK calls retain a five-second total waiting budget;
        callers explicitly requesting a longer budget must supply it through
        their transport/context API."""
        raise NotImplementedError


class QuestionApplicationClient(QuestionApplication):
    """Calls abstraction.asks/application@1 through a transport that exchanges frames."""

    def __init__(self, transport):
        self._transport = transport

    def ask(self, question: ApplicationQuestion) -> QuestionObservation:
        _service_check("ApplicationQuestion", question)
        _args = _QuestionApplicationAskArguments()
        _args.question = question
        _arguments = _service_encode(_write_oa_question_application_ask_arguments, _args, 1)
        _service_decode(_read_oa_question_application_ask_arguments, _arguments, 1)
        _request = _service_request("abstraction.asks/application@1", "Ask", _arguments)
        _payload = _service_response(self._transport.exchange_frame(_request), "abstraction.asks/application@1", "Ask")
        _result = _service_decode(_read_oa_question_application_ask_result, _payload, 1)
        return _result.value

    def observe(self, request_key: str, wait_ms: int) -> QuestionObservation:
        _service_check("string", request_key)
        _service_check("i64", wait_ms)
        _args = _QuestionApplicationObserveArguments()
        _args.request_key = request_key
        _args.wait_ms = wait_ms
        _arguments = _service_encode(_write_oa_question_application_observe_arguments, _args, 1)
        _service_decode(_read_oa_question_application_observe_arguments, _arguments, 1)
        _request = _service_request("abstraction.asks/application@1", "Observe", _arguments)
        _payload = _service_response(self._transport.exchange_frame(_request), "abstraction.asks/application@1", "Observe")
        _result = _service_decode(_read_oa_question_application_observe_result, _payload, 1)
        return _result.value


class QuestionOperator:
    """Operator history, answering and retirement on the configured application
    Book. Host must explicitly authorize the receiving operator; requests
    contain no credentials, authority claims or provider paths. Authorization
    callbacks are trusted service configuration and may use the rights service.
    Retirement and native Forget both retain admission tombstones."""

    def list_questions(self, cursor: str, limit: int) -> OperatorPage:
        """Read bounded current-book pages. Empty cursor starts enumeration; a gap
        requires an explicit restart. Receiver checks same-account Program
        identity and its configured operator authorization on every call before
        reading the Book. Slow/disconnected callers retain no server enumeration
        state."""
        raise NotImplementedError

    def answer_question(self, id: str, option: str) -> OperatorDecision:
        """Record an explicitly authorized operator's choice using the catalog's
        existing options. ID and option are 1..128 UTF-8 bytes without control
        characters. Atomic same-option replay preserves the original decision.
        No automatic retry and no implicit resource authorization. A missing
        operator policy refuses; account identity alone is insufficient."""
        raise NotImplementedError

    def retire_question(self, id: str) -> OperatorRetirement:
        """Retire one question for an explicitly authorized operator. ID is 1..128
        UTF-8 bytes without control characters. Authorization and context are
        rechecked inside the atomic edit before removal. Retiring an already
        retired ID replays retired without a record. No automatic retry;
        retirement grants and revokes no resource authority."""
        raise NotImplementedError


class QuestionOperatorClient(QuestionOperator):
    """Calls abstraction.asks/operator@1 through a transport that exchanges frames."""

    def __init__(self, transport):
        self._transport = transport

    def list_questions(self, cursor: str, limit: int) -> OperatorPage:
        _service_check("string", cursor)
        _service_check("i64", limit)
        _args = _QuestionOperatorListQuestionsArguments()
        _args.cursor = cursor
        _args.limit = limit
        _arguments = _service_encode(_write_oa_question_operator_list_questions_arguments, _args, 1)
        _service_decode(_read_oa_question_operator_list_questions_arguments, _arguments, 1)
        _request = _service_request("abstraction.asks/operator@1", "ListQuestions", _arguments)
        _payload = _service_response(self._transport.exchange_frame(_request), "abstraction.asks/operator@1", "ListQuestions")
        _result = _service_decode(_read_oa_question_operator_list_questions_result, _payload, 1)
        return _result.value

    def answer_question(self, id: str, option: str) -> OperatorDecision:
        _service_check("string", id)
        _service_check("string", option)
        _args = _QuestionOperatorAnswerQuestionArguments()
        _args.id = id
        _args.option = option
        _arguments = _service_encode(_write_oa_question_operator_answer_question_arguments, _args, 1)
        _service_decode(_read_oa_question_operator_answer_question_arguments, _arguments, 1)
        _request = _service_request("abstraction.asks/operator@1", "AnswerQuestion", _arguments)
        _payload = _service_response(self._transport.exchange_frame(_request), "abstraction.asks/operator@1", "AnswerQuestion")
        _result = _service_decode(_read_oa_question_operator_answer_question_result, _payload, 1)
        return _result.value

    def retire_question(self, id: str) -> OperatorRetirement:
        _service_check("string", id)
        _args = _QuestionOperatorRetireQuestionArguments()
        _args.id = id
        _arguments = _service_encode(_write_oa_question_operator_retire_question_arguments, _args, 1)
        _service_decode(_read_oa_question_operator_retire_question_arguments, _arguments, 1)
        _request = _service_request("abstraction.asks/operator@1", "RetireQuestion", _arguments)
        _payload = _service_response(self._transport.exchange_frame(_request), "abstraction.asks/operator@1", "RetireQuestion")
        _result = _service_decode(_read_oa_question_operator_retire_question_result, _payload, 1)
        return _result.value
