# Code generated by abstraction-idl from abstraction-asks/asks.thrift. DO NOT EDIT.

_HEX = b"0123456789abcdef"
_WS = (0x20, 0x09, 0x0A, 0x0D)
_SHORT = {0x22: b'\\"', 0x5C: b"\\\\", 0x08: b"\\b", 0x0C: b"\\f",
          0x0A: b"\\n", 0x0D: b"\\r", 0x09: b"\\t"}


def esc_byte(out, c):
    short = _SHORT.get(c)
    if short is not None:
        out += short
    elif c < 0x20:
        out += b"\\u00" + bytes([_HEX[c >> 4], _HEX[c & 0xF]])
    else:
        out.append(c)


def num(out, n):
    out += str(int(n)).encode("ascii")


def pad(out, depth):
    out += b" " * (depth * 2)


def strs(out, v, depth):
    if not v:
        out += b"[]"
        return
    out += b"[\n"
    for i, s in enumerate(v):
        pad(out, depth + 1)
        esc(out, s)
        if i + 1 < len(v):
            out += b","
        out += b"\n"
    pad(out, depth)
    out += b"]"


def raw(out, s, depth):
    b = s.encode("utf-8") if isinstance(s, str) else s
    i, n = 0, len(b)
    while i < n:
        c = b[i]
        if c in _WS:
            i += 1
        elif c == 0x22:
            j = i + 1
            while j < n:
                if b[j] == 0x5C:
                    j += 2
                    continue
                if b[j] == 0x22:
                    j += 1
                    break
                j += 1
            out += b[i:j]
            i = j
        elif c in (0x7B, 0x5B):
            out.append(c)
            i += 1
            j = i
            while j < n and b[j] in _WS:
                j += 1
            if j < n and b[j] in (0x7D, 0x5D):
                out.append(b[j])
                i = j + 1
            else:
                depth += 1
                out += b"\n"
                pad(out, depth)
        elif c in (0x7D, 0x5D):
            depth -= 1
            out += b"\n"
            pad(out, depth)
            out.append(c)
            i += 1
        elif c == 0x2C:
            out += b",\n"
            pad(out, depth)
            i += 1
        elif c == 0x3A:
            out += b": "
            i += 1
        else:
            out.append(c)
            i += 1


def rawmap(out, m, depth):
    keys = sorted(m, key=lambda k: k.encode("utf-8"))
    if not keys:
        out += b"{}"
        return
    out += b"{\n"
    for i, k in enumerate(keys):
        pad(out, depth + 1)
        esc(out, k)
        out += b": "
        raw(out, m[k], depth + 1)
        if i + 1 < len(keys):
            out += b","
        out += b"\n"
    pad(out, depth)
    out += b"}"

def esc(out, s):
    out += b'"'
    for c in s.encode("utf-8"):
        esc_byte(out, c)
    out += b'"'


def strmap(out, m, depth):
    keys = sorted(m, key=lambda k: k.encode("utf-8"))
    if not keys:
        out += b"{}"
        return
    out += b"{\n"
    for i, k in enumerate(keys):
        pad(out, depth + 1)
        esc(out, k)
        out += b": "
        esc(out, m[k])
        if i + 1 < len(keys):
            out += b","
        out += b"\n"
    pad(out, depth)
    out += b"}"


def enc_list(out, v, depth, enc):
    if not v:
        out += b"[]"
        return
    out += b"[\n"
    for i, x in enumerate(v):
        pad(out, depth + 1)
        enc(out, x, depth + 1)
        if i + 1 < len(v):
            out += b","
        out += b"\n"
    pad(out, depth)
    out += b"]"


OBSERVATIONOUTCOME_NAMES = ["pending", "answered", "unknown", "gone", "invalid", "conflict", "forbidden", "unavailable"]
OBSERVATIONOUTCOME_UNKNOWN = "refuse"


OPERATORPAGEOUTCOME_NAMES = ["page", "gap", "invalid", "forbidden", "unavailable"]
OPERATORPAGEOUTCOME_UNKNOWN = "refuse"


OPERATORDECISIONOUTCOME_NAMES = ["answered", "conflict", "unknown", "invalid", "forbidden", "unavailable"]
OPERATORDECISIONOUTCOME_UNKNOWN = "refuse"


OPERATIONS = ["ask", "pending", "answered", "answer", "forget"]


REFUSAL_CODES = ["internal", "invalid_request", "caller_refused", "unknown_operation", "not_administrator", "withdrawn", "unknown_question", "unknown_option", "bad_slot", "nothing_pending", "no_record"]


class Question:
    def __init__(self, **kw):
        self.asker = kw.get("asker", "")
        self.key = kw.get("key", "")
        self.slots = kw.get("slots", {})


class Request:
    def __init__(self, **kw):
        self.op = kw.get("op", "")
        self.ask = kw.get("ask", None)
        self.wait = kw.get("wait", False)
        self.id = kw.get("id", "")
        self.option = kw.get("option", "")
        self.admin = kw.get("admin", "")


class Answer:
    def __init__(self, **kw):
        self.id = kw.get("id", "")
        self.pending = kw.get("pending", False)
        self.option = kw.get("option", "")
        self.yes = kw.get("yes", False)
        self.kept = kw.get("kept", False)


class RecordMetadata:
    def __init__(self, **kw):
        self.id = kw.get("id", "")
        self.asker = kw.get("asker", "")
        self.key = kw.get("key", "")
        self.about = kw.get("about", "")
        self.text = kw.get("text", "")
        self.options = kw.get("options", [])
        self.asked = kw.get("asked", "")
        self.option = kw.get("option", "")
        self.answered = kw.get("answered", "")
        self.kept = kw.get("kept", False)
        self.yes = kw.get("yes", False)


class ResponseMetadata:
    def __init__(self, **kw):
        self.code = kw.get("code", "")
        self.error = kw.get("error", "")
        self.answer = kw.get("answer", None)
        self.records = kw.get("records", [])


class ApplicationQuestion:
    def __init__(self, **kw):
        self.request_key = kw.get("request_key", "")
        self.key = kw.get("key", "")
        self.slots = kw.get("slots", {})


class QuestionObservation:
    def __init__(self, **kw):
        self.outcome = kw.get("outcome", "")
        self.answer = kw.get("answer", None)


class OperatorPage:
    def __init__(self, **kw):
        self.outcome = kw.get("outcome", "")
        self.records = kw.get("records", [])
        self.next = kw.get("next", "")
        self.complete = kw.get("complete", False)


class OperatorDecision:
    def __init__(self, **kw):
        self.outcome = kw.get("outcome", "")
        self.record = kw.get("record", None)


class OAQuestionApplicationAskArguments:
    def __init__(self, **kw):
        self.question = kw.get("question", ApplicationQuestion())


class OAQuestionApplicationObserveArguments:
    def __init__(self, **kw):
        self.request_key = kw.get("request_key", "")
        self.wait_ms = kw.get("wait_ms", 0)


class OAQuestionOperatorListQuestionsArguments:
    def __init__(self, **kw):
        self.cursor = kw.get("cursor", "")
        self.limit = kw.get("limit", 0)


class OAQuestionOperatorAnswerQuestionArguments:
    def __init__(self, **kw):
        self.id = kw.get("id", "")
        self.option = kw.get("option", "")


class OAServiceFrame:
    def __init__(self, **kw):
        self.version = kw.get("version", 0)
        self.service = kw.get("service", "")
        self.method = kw.get("method", "")
        self.arguments = kw.get("arguments", "")


class OAServiceReply:
    def __init__(self, **kw):
        self.version = kw.get("version", 0)
        self.service = kw.get("service", "")
        self.method = kw.get("method", "")
        self.ok = kw.get("ok", False)
        self.payload = kw.get("payload", "")


class OAServiceError:
    def __init__(self, **kw):
        self.code = kw.get("code", "")
        self.message = kw.get("message", "")


class OAQuestionApplicationAskResult:
    def __init__(self, **kw):
        self.value = kw.get("value", QuestionObservation())


class OAQuestionApplicationObserveResult:
    def __init__(self, **kw):
        self.value = kw.get("value", QuestionObservation())


class OAQuestionOperatorListQuestionsResult:
    def __init__(self, **kw):
        self.value = kw.get("value", OperatorPage())


class OAQuestionOperatorAnswerQuestionResult:
    def __init__(self, **kw):
        self.value = kw.get("value", OperatorDecision())


def enc_question(out, v, depth):
    out += b"{"
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "asker")
    out += b": "
    esc(out, v.asker)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "key")
    out += b": "
    esc(out, v.key)
    if v.slots:
        out += b","
        out += b"\n"
        pad(out, depth + 1)
        esc(out, "slots")
        out += b": "
        strmap(out, v.slots, depth + 1)
    out += b"\n"
    pad(out, depth)
    out += b"}"


def enc_request(out, v, depth):
    out += b"{"
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "op")
    out += b": "
    esc(out, v.op)
    if v.ask is not None:
        out += b","
        out += b"\n"
        pad(out, depth + 1)
        esc(out, "ask")
        out += b": "
        enc_question(out, v.ask, depth + 1)
    if v.wait:
        out += b","
        out += b"\n"
        pad(out, depth + 1)
        esc(out, "wait")
        out += b": "
        out += b"true" if v.wait else b"false"
    if v.id:
        out += b","
        out += b"\n"
        pad(out, depth + 1)
        esc(out, "id")
        out += b": "
        esc(out, v.id)
    if v.option:
        out += b","
        out += b"\n"
        pad(out, depth + 1)
        esc(out, "option")
        out += b": "
        esc(out, v.option)
    if v.admin:
        out += b","
        out += b"\n"
        pad(out, depth + 1)
        esc(out, "admin")
        out += b": "
        esc(out, v.admin)
    out += b"\n"
    pad(out, depth)
    out += b"}"


def enc_answer(out, v, depth):
    out += b"{"
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "id")
    out += b": "
    esc(out, v.id)
    if v.pending:
        out += b","
        out += b"\n"
        pad(out, depth + 1)
        esc(out, "pending")
        out += b": "
        out += b"true" if v.pending else b"false"
    if v.option:
        out += b","
        out += b"\n"
        pad(out, depth + 1)
        esc(out, "option")
        out += b": "
        esc(out, v.option)
    if v.yes:
        out += b","
        out += b"\n"
        pad(out, depth + 1)
        esc(out, "yes")
        out += b": "
        out += b"true" if v.yes else b"false"
    if v.kept:
        out += b","
        out += b"\n"
        pad(out, depth + 1)
        esc(out, "kept")
        out += b": "
        out += b"true" if v.kept else b"false"
    out += b"\n"
    pad(out, depth)
    out += b"}"


def enc_recordmetadata(out, v, depth):
    out += b"{"
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "id")
    out += b": "
    esc(out, v.id)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "asker")
    out += b": "
    esc(out, v.asker)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "key")
    out += b": "
    esc(out, v.key)
    if v.about:
        out += b","
        out += b"\n"
        pad(out, depth + 1)
        esc(out, "about")
        out += b": "
        esc(out, v.about)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "text")
    out += b": "
    esc(out, v.text)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "options")
    out += b": "
    strs(out, v.options, depth + 1)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "asked")
    out += b": "
    esc(out, v.asked)
    if v.option:
        out += b","
        out += b"\n"
        pad(out, depth + 1)
        esc(out, "option")
        out += b": "
        esc(out, v.option)
    if v.answered:
        out += b","
        out += b"\n"
        pad(out, depth + 1)
        esc(out, "answered")
        out += b": "
        esc(out, v.answered)
    if v.kept:
        out += b","
        out += b"\n"
        pad(out, depth + 1)
        esc(out, "kept")
        out += b": "
        out += b"true" if v.kept else b"false"
    if v.yes:
        out += b","
        out += b"\n"
        pad(out, depth + 1)
        esc(out, "yes")
        out += b": "
        out += b"true" if v.yes else b"false"
    out += b"\n"
    pad(out, depth)
    out += b"}"


def enc_responsemetadata(out, v, depth):
    out += b"{"
    first = True
    if v.code:
        first = False
        out += b"\n"
        pad(out, depth + 1)
        esc(out, "code")
        out += b": "
        esc(out, v.code)
    if v.error:
        if not first:
            out += b","
        first = False
        out += b"\n"
        pad(out, depth + 1)
        esc(out, "error")
        out += b": "
        esc(out, v.error)
    if v.answer is not None:
        if not first:
            out += b","
        first = False
        out += b"\n"
        pad(out, depth + 1)
        esc(out, "answer")
        out += b": "
        enc_answer(out, v.answer, depth + 1)
    if v.records:
        if not first:
            out += b","
        first = False
        out += b"\n"
        pad(out, depth + 1)
        esc(out, "records")
        out += b": "
        enc_list(out, v.records, depth + 1, enc_recordmetadata)
    if not first:
        out += b"\n"
        pad(out, depth)
    out += b"}"


def enc_applicationquestion(out, v, depth):
    out += b"{"
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "request_key")
    out += b": "
    esc(out, v.request_key)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "key")
    out += b": "
    esc(out, v.key)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "slots")
    out += b": "
    strmap(out, v.slots, depth + 1)
    out += b"\n"
    pad(out, depth)
    out += b"}"


def enc_questionobservation(out, v, depth):
    if type(v.outcome) is not str: raise Refusal("wrong_type",0)
    if v.outcome != "pending" and v.outcome != "answered" and v.outcome != "unknown" and v.outcome != "gone" and v.outcome != "invalid" and v.outcome != "conflict" and v.outcome != "forbidden" and v.outcome != "unavailable": raise Refusal("bad_enum",0)
    out += b"{"
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "outcome")
    out += b": "
    esc(out, v.outcome)
    if v.answer is not None:
        out += b","
        out += b"\n"
        pad(out, depth + 1)
        esc(out, "answer")
        out += b": "
        enc_answer(out, v.answer, depth + 1)
    out += b"\n"
    pad(out, depth)
    out += b"}"


def enc_operatorpage(out, v, depth):
    if type(v.outcome) is not str: raise Refusal("wrong_type",0)
    if v.outcome != "page" and v.outcome != "gap" and v.outcome != "invalid" and v.outcome != "forbidden" and v.outcome != "unavailable": raise Refusal("bad_enum",0)
    out += b"{"
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "outcome")
    out += b": "
    esc(out, v.outcome)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "records")
    out += b": "
    enc_list(out, v.records, depth + 1, enc_recordmetadata)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "next")
    out += b": "
    esc(out, v.next)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "complete")
    out += b": "
    out += b"true" if v.complete else b"false"
    out += b"\n"
    pad(out, depth)
    out += b"}"


def enc_operatordecision(out, v, depth):
    if type(v.outcome) is not str: raise Refusal("wrong_type",0)
    if v.outcome != "answered" and v.outcome != "conflict" and v.outcome != "unknown" and v.outcome != "invalid" and v.outcome != "forbidden" and v.outcome != "unavailable": raise Refusal("bad_enum",0)
    out += b"{"
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "outcome")
    out += b": "
    esc(out, v.outcome)
    if v.record is not None:
        out += b","
        out += b"\n"
        pad(out, depth + 1)
        esc(out, "record")
        out += b": "
        enc_recordmetadata(out, v.record, depth + 1)
    out += b"\n"
    pad(out, depth)
    out += b"}"


def enc_oaquestionapplicationaskarguments(out, v, depth):
    out += b"{"
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "question")
    out += b": "
    enc_applicationquestion(out, v.question, depth + 1)
    out += b"\n"
    pad(out, depth)
    out += b"}"


def enc_oaquestionapplicationobservearguments(out, v, depth):
    out += b"{"
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "request_key")
    out += b": "
    esc(out, v.request_key)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "wait_ms")
    out += b": "
    num(out, v.wait_ms)
    out += b"\n"
    pad(out, depth)
    out += b"}"


def enc_oaquestionoperatorlistquestionsarguments(out, v, depth):
    out += b"{"
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "cursor")
    out += b": "
    esc(out, v.cursor)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "limit")
    out += b": "
    num(out, v.limit)
    out += b"\n"
    pad(out, depth)
    out += b"}"


def enc_oaquestionoperatoranswerquestionarguments(out, v, depth):
    out += b"{"
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "id")
    out += b": "
    esc(out, v.id)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "option")
    out += b": "
    esc(out, v.option)
    out += b"\n"
    pad(out, depth)
    out += b"}"


def enc_oaserviceframe(out, v, depth):
    out += b"{"
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "version")
    out += b": "
    num(out, v.version)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "service")
    out += b": "
    esc(out, v.service)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "method")
    out += b": "
    esc(out, v.method)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "arguments")
    out += b": "
    out += v.arguments.encode("utf-8") if isinstance(v.arguments, str) else v.arguments
    out += b"\n"
    pad(out, depth)
    out += b"}"


def enc_oaservicereply(out, v, depth):
    out += b"{"
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "version")
    out += b": "
    num(out, v.version)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "service")
    out += b": "
    esc(out, v.service)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "method")
    out += b": "
    esc(out, v.method)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "ok")
    out += b": "
    out += b"true" if v.ok else b"false"
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "payload")
    out += b": "
    out += v.payload.encode("utf-8") if isinstance(v.payload, str) else v.payload
    out += b"\n"
    pad(out, depth)
    out += b"}"


def enc_oaserviceerror(out, v, depth):
    out += b"{"
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "code")
    out += b": "
    esc(out, v.code)
    out += b","
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "message")
    out += b": "
    esc(out, v.message)
    out += b"\n"
    pad(out, depth)
    out += b"}"


def enc_oaquestionapplicationaskresult(out, v, depth):
    out += b"{"
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "value")
    out += b": "
    enc_questionobservation(out, v.value, depth + 1)
    out += b"\n"
    pad(out, depth)
    out += b"}"


def enc_oaquestionapplicationobserveresult(out, v, depth):
    out += b"{"
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "value")
    out += b": "
    enc_questionobservation(out, v.value, depth + 1)
    out += b"\n"
    pad(out, depth)
    out += b"}"


def enc_oaquestionoperatorlistquestionsresult(out, v, depth):
    out += b"{"
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "value")
    out += b": "
    enc_operatorpage(out, v.value, depth + 1)
    out += b"\n"
    pad(out, depth)
    out += b"}"


def enc_oaquestionoperatoranswerquestionresult(out, v, depth):
    out += b"{"
    out += b"\n"
    pad(out, depth + 1)
    esc(out, "value")
    out += b": "
    enc_operatordecision(out, v.value, depth + 1)
    out += b"\n"
    pad(out, depth)
    out += b"}"


def encode(v):
    out = bytearray()
    enc_request(out, v, 0)
    out += b"\n"
    return bytes(out)


_QUOTE, _BACKSLASH, _COLON, _COMMA = 0x22, 0x5C, 0x3A, 0x2C
_LBRACE, _RBRACE, _LBRACK, _RBRACK = 0x7B, 0x7D, 0x5B, 0x5D
_MINUS, _ZERO, _NINE, _DOT, _LOWER_U, _LOWER_N = 0x2D, 0x30, 0x39, 0x2E, 0x75, 0x6E
_UNESCAPE = {0x22: 0x22, 0x5C: 0x5C, 0x2F: 0x2F, 0x62: 0x08,
             0x66: 0x0C, 0x6E: 0x0A, 0x72: 0x0D, 0x74: 0x09}
_DEPTH_LIMIT = 64
_I64_DIGITS = 19


class Refusal(ValueError):
    def __init__(self, word, offset):
        super().__init__("refused: %s at byte %d" % (word, offset))
        self.word = word
        self.offset = offset


class _Reader:
    __slots__ = ("buf", "pos", "depth")

    def __init__(self, buf):
        self.buf = buf
        self.pos = 0
        self.depth = 0

    def refuse(self, word):
        return Refusal(word, self.pos)

    def at(self):
        return self.buf[self.pos] if self.pos < len(self.buf) else 0

    def ws(self):
        while self.pos < len(self.buf) and self.buf[self.pos] in _WS:
            self.pos += 1

    def enter(self):
        self.depth += 1
        if self.depth > _DEPTH_LIMIT:
            raise self.refuse("depth_exceeded")

    def digit(self):
        return _ZERO <= self.at() <= _NINE

    def string(self):
        if self.at() != _QUOTE:
            raise self.refuse("wrong_type")
        self.pos += 1
        out = bytearray()
        while True:
            if self.pos >= len(self.buf):
                raise self.refuse("malformed")
            c = self.buf[self.pos]
            if c == _QUOTE:
                self.pos += 1
                try:
                    return out.decode("utf-8")
                except UnicodeDecodeError:
                    raise self.refuse("bad_string") from None
            if c < 0x20:
                raise self.refuse("bad_string")
            if c == _BACKSLASH:
                self.escape(out)
            else:
                out.append(c)
                self.pos += 1

    def escape(self, out):
        self.pos += 1
        if self.pos >= len(self.buf):
            raise self.refuse("malformed")
        c = self.buf[self.pos]
        self.pos += 1
        plain = _UNESCAPE.get(c)
        if plain is not None:
            out.append(plain)
            return
        if c != _LOWER_U:
            raise self.refuse("bad_string")
        u = self.hex4()
        if 0xDC00 <= u <= 0xDFFF:
            raise self.refuse("bad_string")
        if 0xD800 <= u <= 0xDBFF:
            if (self.pos + 1 >= len(self.buf) or self.buf[self.pos] != _BACKSLASH
                    or self.buf[self.pos + 1] != _LOWER_U):
                raise self.refuse("bad_string")
            self.pos += 2
            low = self.hex4()
            if not 0xDC00 <= low <= 0xDFFF:
                raise self.refuse("bad_string")
            u = 0x10000 + ((u - 0xD800) << 10) + (low - 0xDC00)
        out += chr(u).encode("utf-8")

    def hex4(self):
        if self.pos + 4 > len(self.buf):
            raise self.refuse("bad_string")
        u = 0
        for i in range(4):
            c = self.buf[self.pos + i]
            if _ZERO <= c <= _NINE:
                u = u << 4 | (c - _ZERO)
            elif 0x61 <= c <= 0x66:
                u = u << 4 | (c - 0x61 + 10)
            elif 0x41 <= c <= 0x46:
                u = u << 4 | (c - 0x41 + 10)
            else:
                raise self.refuse("bad_string")
        self.pos += 4
        return u

    def integer(self, low, high):
        c = self.at()
        if c != _MINUS and not _ZERO <= c <= _NINE:
            raise self.refuse("wrong_type")
        negative = c == _MINUS
        if negative:
            self.pos += 1
        if not self.digit():
            raise self.refuse("malformed")
        start = self.pos
        if self.at() == _ZERO:
            self.pos += 1
        else:
            while self.digit():
                self.pos += 1
        if self.at() in (_DOT, 0x65, 0x45) or self.digit():
            raise self.refuse("number_spelling")
        if self.pos - start > _I64_DIGITS:
            raise self.refuse("number_spelling")
        n = int(self.buf[start:self.pos])
        if negative:
            if n == 0:
                raise self.refuse("number_spelling")
            n = -n
        if n < low or n > high:
            raise self.refuse("number_spelling")
        return n

    def boolean(self):
        if self.at() == 0x74:
            self.literal(b"true")
            return True
        if self.at() == 0x66:
            self.literal(b"false")
            return False
        raise self.refuse("wrong_type")

    def literal(self, word):
        if self.buf[self.pos:self.pos + len(word)] != word:
            raise self.refuse("malformed")
        self.pos += len(word)

    def str_list(self):
        if self.at() != _LBRACK:
            raise self.refuse("wrong_type")
        self.enter()
        self.pos += 1
        out = []
        self.ws()
        if self.at() != _RBRACK:
            while True:
                self.ws()
                out.append(self.string())
                self.ws()
                if self.at() != _COMMA:
                    break
                self.pos += 1
        if self.at() != _RBRACK:
            raise self.refuse("malformed")
        self.pos += 1
        self.depth -= 1
        return out

    def raw_map(self):
        if self.at() != _LBRACE:
            raise self.refuse("wrong_type")
        self.enter()
        self.pos += 1
        out = {}
        self.ws()
        if self.at() != _RBRACE:
            while True:
                self.ws()
                if self.at() != _QUOTE:
                    raise self.refuse("malformed")
                k = self.string()
                if k in out:
                    raise self.refuse("duplicate_key")
                self.ws()
                if self.at() != _COLON:
                    raise self.refuse("malformed")
                self.pos += 1
                self.ws()
                out[k] = self.raw_value()
                self.ws()
                if self.at() != _COMMA:
                    break
                self.pos += 1
        if self.at() != _RBRACE:
            raise self.refuse("malformed")
        self.pos += 1
        self.depth -= 1
        return out

    def raw_value(self):
        start = self.pos
        self.skip_value()
        return self.buf[start:self.pos]

    def skip_value(self):
        c = self.at()
        if c == _QUOTE:
            self.skip_string()
        elif c in (_LBRACE, _LBRACK):
            self.skip_container()
        elif c == 0x74:
            self.literal(b"true")
        elif c == 0x66:
            self.literal(b"false")
        elif c == 0x6E:
            self.literal(b"null")
        elif c == _MINUS or _ZERO <= c <= _NINE:
            self.skip_number()
        else:
            raise self.refuse("malformed")

    # An opaque value is validated and carried, never interpreted. Its syntax is
    # the record's own — the same string reader, so an escape, a control byte or
    # a lone surrogate is judged identically at any depth — and what it is free
    # to spell, it keeps: the bytes between these two offsets are what a writer
    # re-emits. A number is walked, never converted, so a value no host type
    # holds survives the reader that carried it.
    def skip_string(self):
        self.string()

    def some_digits(self):
        n = 0
        while _ZERO <= self.at() <= _NINE:
            self.pos += 1
            n += 1
        if n == 0:
            raise self.refuse("number_spelling")

    def skip_number(self):
        if self.at() == _MINUS:
            self.pos += 1
        c = self.at()
        if c == _ZERO:
            self.pos += 1
        elif _ZERO < c <= _NINE:
            while _ZERO <= self.at() <= _NINE:
                self.pos += 1
        else:
            raise self.refuse("number_spelling")
        if self.at() == _DOT:
            self.pos += 1
            self.some_digits()
        if self.at() in (0x65, 0x45):
            self.pos += 1
            if self.at() in (0x2B, _MINUS):
                self.pos += 1
            self.some_digits()

    def skip_container(self):
        opener = self.at()
        shut = _RBRACE if opener == _LBRACE else _RBRACK
        self.enter()
        self.pos += 1
        self.ws()
        seen = set()
        if self.at() != shut:
            while True:
                self.ws()
                if opener == _LBRACE:
                    if self.at() != _QUOTE:
                        raise self.refuse("malformed")
                    k = self.string()
                    if k in seen:
                        raise self.refuse("duplicate_key")
                    seen.add(k)
                    self.ws()
                    if self.at() != _COLON:
                        raise self.refuse("malformed")
                    self.pos += 1
                    self.ws()
                self.skip_value()
                self.ws()
                if self.at() != _COMMA:
                    break
                self.pos += 1
        if self.at() != shut:
            raise self.refuse("malformed")
        self.pos += 1
        self.depth -= 1

    def str_map(self):
        if self.at() != _LBRACE:
            raise self.refuse("wrong_type")
        self.enter()
        self.pos += 1
        out = {}
        self.ws()
        if self.at() != _RBRACE:
            while True:
                self.ws()
                if self.at() != _QUOTE:
                    raise self.refuse("malformed")
                k = self.string()
                if k in out:
                    raise self.refuse("duplicate_key")
                self.ws()
                if self.at() != _COLON:
                    raise self.refuse("malformed")
                self.pos += 1
                self.ws()
                out[k] = self.string()
                self.ws()
                if self.at() != _COMMA:
                    break
                self.pos += 1
        if self.at() != _RBRACE:
            raise self.refuse("malformed")
        self.pos += 1
        self.depth -= 1
        return out


def _decode_list(r, elem):
    if r.at() != _LBRACK:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    out = []
    r.ws()
    if r.at() != _RBRACK:
        while True:
            r.ws()
            out.append(elem(r))
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACK:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    return out


def _decode_question(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = Question()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "asker":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.asker = r.string()
            elif key == "key":
                if seen & 2:
                    raise r.refuse("duplicate_field")
                seen |= 2
                v.key = r.string()
            elif key == "slots":
                if seen & 4:
                    raise r.refuse("duplicate_field")
                seen |= 4
                v.slots = r.str_map()
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 3 != 3:
        raise r.refuse("missing_field")
    return v


def _decode_request(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = Request()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "op":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.op = r.string()
            elif key == "ask":
                if seen & 2:
                    raise r.refuse("duplicate_field")
                seen |= 2
                v.ask = _decode_question(r)
            elif key == "wait":
                if seen & 4:
                    raise r.refuse("duplicate_field")
                seen |= 4
                v.wait = r.boolean()
            elif key == "id":
                if seen & 8:
                    raise r.refuse("duplicate_field")
                seen |= 8
                v.id = r.string()
            elif key == "option":
                if seen & 16:
                    raise r.refuse("duplicate_field")
                seen |= 16
                v.option = r.string()
            elif key == "admin":
                if seen & 32:
                    raise r.refuse("duplicate_field")
                seen |= 32
                v.admin = r.string()
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 1 != 1:
        raise r.refuse("missing_field")
    return v


def _decode_answer(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = Answer()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "id":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.id = r.string()
            elif key == "pending":
                if seen & 2:
                    raise r.refuse("duplicate_field")
                seen |= 2
                v.pending = r.boolean()
            elif key == "option":
                if seen & 4:
                    raise r.refuse("duplicate_field")
                seen |= 4
                v.option = r.string()
            elif key == "yes":
                if seen & 8:
                    raise r.refuse("duplicate_field")
                seen |= 8
                v.yes = r.boolean()
            elif key == "kept":
                if seen & 16:
                    raise r.refuse("duplicate_field")
                seen |= 16
                v.kept = r.boolean()
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 1 != 1:
        raise r.refuse("missing_field")
    return v


def _decode_recordmetadata(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = RecordMetadata()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "id":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.id = r.string()
            elif key == "asker":
                if seen & 2:
                    raise r.refuse("duplicate_field")
                seen |= 2
                v.asker = r.string()
            elif key == "key":
                if seen & 4:
                    raise r.refuse("duplicate_field")
                seen |= 4
                v.key = r.string()
            elif key == "about":
                if seen & 8:
                    raise r.refuse("duplicate_field")
                seen |= 8
                v.about = r.string()
            elif key == "text":
                if seen & 16:
                    raise r.refuse("duplicate_field")
                seen |= 16
                v.text = r.string()
            elif key == "options":
                if seen & 32:
                    raise r.refuse("duplicate_field")
                seen |= 32
                v.options = r.str_list()
            elif key == "asked":
                if seen & 64:
                    raise r.refuse("duplicate_field")
                seen |= 64
                v.asked = r.string()
            elif key == "option":
                if seen & 128:
                    raise r.refuse("duplicate_field")
                seen |= 128
                v.option = r.string()
            elif key == "answered":
                if seen & 256:
                    raise r.refuse("duplicate_field")
                seen |= 256
                v.answered = r.string()
            elif key == "kept":
                if seen & 512:
                    raise r.refuse("duplicate_field")
                seen |= 512
                v.kept = r.boolean()
            elif key == "yes":
                if seen & 1024:
                    raise r.refuse("duplicate_field")
                seen |= 1024
                v.yes = r.boolean()
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 119 != 119:
        raise r.refuse("missing_field")
    return v


def _decode_responsemetadata(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = ResponseMetadata()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "code":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.code = r.string()
            elif key == "error":
                if seen & 2:
                    raise r.refuse("duplicate_field")
                seen |= 2
                v.error = r.string()
            elif key == "answer":
                if seen & 4:
                    raise r.refuse("duplicate_field")
                seen |= 4
                v.answer = _decode_answer(r)
            elif key == "records":
                if seen & 8:
                    raise r.refuse("duplicate_field")
                seen |= 8
                v.records = _decode_list(r, _decode_recordmetadata)
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    return v


def _decode_applicationquestion(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = ApplicationQuestion()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "request_key":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.request_key = r.string()
            elif key == "key":
                if seen & 2:
                    raise r.refuse("duplicate_field")
                seen |= 2
                v.key = r.string()
            elif key == "slots":
                if seen & 4:
                    raise r.refuse("duplicate_field")
                seen |= 4
                v.slots = r.str_map()
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 7 != 7:
        raise r.refuse("missing_field")
    return v


def _decode_questionobservation(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = QuestionObservation()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "outcome":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.outcome = r.string()
            elif key == "answer":
                if seen & 2:
                    raise r.refuse("duplicate_field")
                seen |= 2
                v.answer = _decode_answer(r)
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 1 != 1:
        raise r.refuse("missing_field")
    if v.outcome != "pending" and v.outcome != "answered" and v.outcome != "unknown" and v.outcome != "gone" and v.outcome != "invalid" and v.outcome != "conflict" and v.outcome != "forbidden" and v.outcome != "unavailable": raise r.refuse("bad_enum")
    return v


def _decode_operatorpage(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = OperatorPage()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "outcome":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.outcome = r.string()
            elif key == "records":
                if seen & 2:
                    raise r.refuse("duplicate_field")
                seen |= 2
                v.records = _decode_list(r, _decode_recordmetadata)
            elif key == "next":
                if seen & 4:
                    raise r.refuse("duplicate_field")
                seen |= 4
                v.next = r.string()
            elif key == "complete":
                if seen & 8:
                    raise r.refuse("duplicate_field")
                seen |= 8
                v.complete = r.boolean()
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 15 != 15:
        raise r.refuse("missing_field")
    if v.outcome != "page" and v.outcome != "gap" and v.outcome != "invalid" and v.outcome != "forbidden" and v.outcome != "unavailable": raise r.refuse("bad_enum")
    return v


def _decode_operatordecision(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = OperatorDecision()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "outcome":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.outcome = r.string()
            elif key == "record":
                if seen & 2:
                    raise r.refuse("duplicate_field")
                seen |= 2
                v.record = _decode_recordmetadata(r)
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 1 != 1:
        raise r.refuse("missing_field")
    if v.outcome != "answered" and v.outcome != "conflict" and v.outcome != "unknown" and v.outcome != "invalid" and v.outcome != "forbidden" and v.outcome != "unavailable": raise r.refuse("bad_enum")
    return v


def _decode_oaquestionapplicationaskarguments(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = OAQuestionApplicationAskArguments()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "question":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.question = _decode_applicationquestion(r)
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 1 != 1:
        raise r.refuse("missing_field")
    return v


def _decode_oaquestionapplicationobservearguments(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = OAQuestionApplicationObserveArguments()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "request_key":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.request_key = r.string()
            elif key == "wait_ms":
                if seen & 2:
                    raise r.refuse("duplicate_field")
                seen |= 2
                v.wait_ms = r.integer(-9223372036854775808, 9223372036854775807)
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 3 != 3:
        raise r.refuse("missing_field")
    return v


def _decode_oaquestionoperatorlistquestionsarguments(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = OAQuestionOperatorListQuestionsArguments()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "cursor":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.cursor = r.string()
            elif key == "limit":
                if seen & 2:
                    raise r.refuse("duplicate_field")
                seen |= 2
                v.limit = r.integer(-9223372036854775808, 9223372036854775807)
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 3 != 3:
        raise r.refuse("missing_field")
    return v


def _decode_oaquestionoperatoranswerquestionarguments(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = OAQuestionOperatorAnswerQuestionArguments()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "id":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.id = r.string()
            elif key == "option":
                if seen & 2:
                    raise r.refuse("duplicate_field")
                seen |= 2
                v.option = r.string()
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 3 != 3:
        raise r.refuse("missing_field")
    return v


def _decode_oaserviceframe(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = OAServiceFrame()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "version":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.version = r.integer(-2147483648, 2147483647)
            elif key == "service":
                if seen & 2:
                    raise r.refuse("duplicate_field")
                seen |= 2
                v.service = r.string()
            elif key == "method":
                if seen & 4:
                    raise r.refuse("duplicate_field")
                seen |= 4
                v.method = r.string()
            elif key == "arguments":
                if seen & 8:
                    raise r.refuse("duplicate_field")
                seen |= 8
                v.arguments = r.raw_value()
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 15 != 15:
        raise r.refuse("missing_field")
    return v


def _decode_oaservicereply(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = OAServiceReply()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "version":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.version = r.integer(-2147483648, 2147483647)
            elif key == "service":
                if seen & 2:
                    raise r.refuse("duplicate_field")
                seen |= 2
                v.service = r.string()
            elif key == "method":
                if seen & 4:
                    raise r.refuse("duplicate_field")
                seen |= 4
                v.method = r.string()
            elif key == "ok":
                if seen & 8:
                    raise r.refuse("duplicate_field")
                seen |= 8
                v.ok = r.boolean()
            elif key == "payload":
                if seen & 16:
                    raise r.refuse("duplicate_field")
                seen |= 16
                v.payload = r.raw_value()
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 31 != 31:
        raise r.refuse("missing_field")
    return v


def _decode_oaserviceerror(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = OAServiceError()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "code":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.code = r.string()
            elif key == "message":
                if seen & 2:
                    raise r.refuse("duplicate_field")
                seen |= 2
                v.message = r.string()
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 3 != 3:
        raise r.refuse("missing_field")
    return v


def _decode_oaquestionapplicationaskresult(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = OAQuestionApplicationAskResult()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "value":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.value = _decode_questionobservation(r)
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 1 != 1:
        raise r.refuse("missing_field")
    return v


def _decode_oaquestionapplicationobserveresult(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = OAQuestionApplicationObserveResult()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "value":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.value = _decode_questionobservation(r)
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 1 != 1:
        raise r.refuse("missing_field")
    return v


def _decode_oaquestionoperatorlistquestionsresult(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = OAQuestionOperatorListQuestionsResult()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "value":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.value = _decode_operatorpage(r)
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 1 != 1:
        raise r.refuse("missing_field")
    return v


def _decode_oaquestionoperatoranswerquestionresult(r):
    if r.at() != _LBRACE:
        raise r.refuse("wrong_type")
    r.enter()
    r.pos += 1
    v = OAQuestionOperatorAnswerQuestionResult()
    seen = 0
    r.ws()
    if r.at() != _RBRACE:
        while True:
            r.ws()
            if r.at() != _QUOTE:
                raise r.refuse("malformed")
            key = r.string()
            r.ws()
            if r.at() != _COLON:
                raise r.refuse("malformed")
            r.pos += 1
            r.ws()
            if key == "value":
                if seen & 1:
                    raise r.refuse("duplicate_field")
                seen |= 1
                v.value = _decode_operatordecision(r)
            else:
                raise r.refuse("unknown_field")
            r.ws()
            if r.at() != _COMMA:
                break
            r.pos += 1
    if r.at() != _RBRACE:
        raise r.refuse("malformed")
    r.pos += 1
    r.depth -= 1
    if seen & 1 != 1:
        raise r.refuse("missing_field")
    return v


def decode(data):
    r = _Reader(bytes(data))
    r.ws()
    v = _decode_request(r)
    r.ws()
    if r.pos < len(r.buf):
        raise r.refuse("trailing_bytes")
    return v


# REFUSALS is in the order two of them are chosen between.

REFUSALS = ["malformed", "bad_string", "number_spelling", "wrong_type", "depth_exceeded", "duplicate_key", "duplicate_field", "unknown_field", "missing_field", "bad_enum", "trailing_bytes"]


def refusal_rank(word):
    return REFUSALS.index(word) if word in REFUSALS else -1


class DispatchError(ValueError):
    def __init__(self, code):
        super().__init__(code)
        self.code = code


def _service_decode(decoder, frame, depth=0):
    if not isinstance(frame, (bytes, bytearray, memoryview)):
        raise TypeError("transport frame must be bytes")
    r = _Reader(bytes(frame))
    r.depth = depth
    r.ws()
    value = decoder(r)
    r.ws()
    if r.pos != len(r.buf):
        raise r.refuse("trailing_bytes")
    return value


def _service_encode(encoder, value, depth):
    out = bytearray()
    try:
        encoder(out, value, depth)
    except UnicodeError:
        raise Refusal("bad_string", 0) from None
    return bytes(out)


def _service_request(service, method, arguments):
    v = OAServiceFrame(version=1, service=service, method=method, arguments=arguments)
    frame = _service_encode(enc_oaserviceframe, v, 0)
    _service_decode(_decode_oaserviceframe, frame)
    return frame


def _service_check(kind, value, depth=0):
    # Python coercions must not silently change typed service arguments.
    if depth >= _DEPTH_LIMIT and (kind.startswith(("list<", "map<")) or kind in _SERVICE_RECORDS):
        raise Refusal("depth_exceeded", 0)
    if kind == "string":
        valid = type(value) is str
    elif kind in ("i32", "i64"):
        valid = type(value) is int
        if valid:
            limit = 1 << (31 if kind == "i32" else 63)
            if not -limit <= value < limit:
                raise Refusal("number_spelling", 0)
    elif kind == "bool":
        valid = type(value) is bool
    elif kind == "json":
        valid = isinstance(value, (str, bytes, bytearray, memoryview))
    elif kind.startswith("list<"):
        valid = type(value) is list
        if valid:
            for item in value:
                _service_check(kind[5:-1], item, depth + 1)
    elif kind.startswith("map<string,"):
        valid = type(value) is dict
        if valid:
            for key, item in value.items():
                _service_check("string", key, depth + 1)
                _service_check(kind[11:-1], item, depth + 1)
    else:
        cls, fields = _SERVICE_RECORDS[kind]
        valid = isinstance(value, cls)
        if valid:
            for name, field_kind, omit in fields:
                if not hasattr(value, name):
                    raise Refusal("missing_field", 0)
                item = getattr(value, name)
                if omit == "absent" and item is None:
                    continue
                _service_check(field_kind, item, depth + 1)
    if not valid:
        raise Refusal("wrong_type", 0)

def service_name(frame):
    """Validate envelope/version for routing; dispatchers validate typed arguments."""
    value = _service_decode(_decode_oaserviceframe, frame)
    if value.version != 1:
        raise DispatchError("unknown_version")
    return value.service



class ServiceError(Exception):
    def __init__(self, code, message=""):
        super().__init__(message if message else code)
        self.code = code
        self.message = message


def _service_response(frame, service, method):
    reply = _service_decode(_decode_oaservicereply, frame)
    if reply.version != 1:
        raise DispatchError("unknown_version")
    if reply.service != service or reply.method != method:
        raise DispatchError("mismatched_response")
    if not reply.ok:
        error = _service_decode(_decode_oaserviceerror, reply.payload, 1)
        if not error.code:
            raise DispatchError("invalid_error")
        raise ServiceError(error.code, error.message)
    return reply.payload

_SERVICE_RECORDS = {
    "Question": (Question, [("asker","string","never"),("key","string","never"),("slots","map<string,string>","zero"),]),
    "Request": (Request, [("op","string","never"),("ask","Question","absent"),("wait","bool","zero"),("id","string","absent"),("option","string","absent"),("admin","string","absent"),]),
    "Answer": (Answer, [("id","string","never"),("pending","bool","zero"),("option","string","absent"),("yes","bool","zero"),("kept","bool","zero"),]),
    "RecordMetadata": (RecordMetadata, [("id","string","never"),("asker","string","never"),("key","string","never"),("about","string","absent"),("text","string","never"),("options","list<string>","never"),("asked","string","never"),("option","string","absent"),("answered","string","absent"),("kept","bool","zero"),("yes","bool","zero"),]),
    "ResponseMetadata": (ResponseMetadata, [("code","string","absent"),("error","string","absent"),("answer","Answer","absent"),("records","list<RecordMetadata>","zero"),]),
    "ApplicationQuestion": (ApplicationQuestion, [("request_key","string","never"),("key","string","never"),("slots","map<string,string>","never"),]),
    "QuestionObservation": (QuestionObservation, [("outcome","string","never"),("answer","Answer","absent"),]),
    "OperatorPage": (OperatorPage, [("outcome","string","never"),("records","list<RecordMetadata>","never"),("next","string","never"),("complete","bool","never"),]),
    "OperatorDecision": (OperatorDecision, [("outcome","string","never"),("record","RecordMetadata","absent"),]),
    "OAQuestionApplicationAskArguments": (OAQuestionApplicationAskArguments, [("question","ApplicationQuestion","never"),]),
    "OAQuestionApplicationObserveArguments": (OAQuestionApplicationObserveArguments, [("request_key","string","never"),("wait_ms","i64","never"),]),
    "OAQuestionOperatorListQuestionsArguments": (OAQuestionOperatorListQuestionsArguments, [("cursor","string","never"),("limit","i64","never"),]),
    "OAQuestionOperatorAnswerQuestionArguments": (OAQuestionOperatorAnswerQuestionArguments, [("id","string","never"),("option","string","never"),]),
    "OAServiceFrame": (OAServiceFrame, [("version","i32","never"),("service","string","never"),("method","string","never"),("arguments","json","never"),]),
    "OAServiceReply": (OAServiceReply, [("version","i32","never"),("service","string","never"),("method","string","never"),("ok","bool","never"),("payload","json","never"),]),
    "OAServiceError": (OAServiceError, [("code","string","never"),("message","string","never"),]),
    "OAQuestionApplicationAskResult": (OAQuestionApplicationAskResult, [("value","QuestionObservation","never"),]),
    "OAQuestionApplicationObserveResult": (OAQuestionApplicationObserveResult, [("value","QuestionObservation","never"),]),
    "OAQuestionOperatorListQuestionsResult": (OAQuestionOperatorListQuestionsResult, [("value","OperatorPage","never"),]),
    "OAQuestionOperatorAnswerQuestionResult": (OAQuestionOperatorAnswerQuestionResult, [("value","OperatorDecision","never"),]),
}


class QuestionApplication:
    __doc__ = "Application-side human question admission and observation. Server derives caller scope and text, preserves native Via evidence, and owns a versioned bounded Book. Operator answering/history use the separately authorized QuestionOperator service; this application service exposes no administrative secret or operator methods."
    def Ask(self, question: "ApplicationQuestion") -> "QuestionObservation":
        raise NotImplementedError
    def Observe(self, request_key: "str", wait_ms: "int") -> "QuestionObservation":
        raise NotImplementedError


class QuestionApplicationClient(QuestionApplication):
    def __init__(self, transport):
        self._transport = transport

    def Ask(self, question: "ApplicationQuestion") -> "QuestionObservation":
        _service_check("ApplicationQuestion", question)
        _oa_args = OAQuestionApplicationAskArguments()
        _oa_args.question = question
        _oa_arguments = _service_encode(enc_oaquestionapplicationaskarguments, _oa_args, 1)
        _service_decode(_decode_oaquestionapplicationaskarguments, _oa_arguments, 1)
        _oa_request = _service_request("abstraction.asks/application@1", "Ask", _oa_arguments)
        _oa_payload = _service_response(self._transport.exchange_frame(_oa_request), "abstraction.asks/application@1", "Ask")
        _oa_result = _service_decode(_decode_oaquestionapplicationaskresult, _oa_payload, 1)
        return _oa_result.value

    def Observe(self, request_key: "str", wait_ms: "int") -> "QuestionObservation":
        _service_check("string", request_key)
        _service_check("i64", wait_ms)
        _oa_args = OAQuestionApplicationObserveArguments()
        _oa_args.request_key = request_key
        _oa_args.wait_ms = wait_ms
        _oa_arguments = _service_encode(enc_oaquestionapplicationobservearguments, _oa_args, 1)
        _service_decode(_decode_oaquestionapplicationobservearguments, _oa_arguments, 1)
        _oa_request = _service_request("abstraction.asks/application@1", "Observe", _oa_arguments)
        _oa_payload = _service_response(self._transport.exchange_frame(_oa_request), "abstraction.asks/application@1", "Observe")
        _oa_result = _service_decode(_decode_oaquestionapplicationobserveresult, _oa_payload, 1)
        return _oa_result.value


class QuestionOperator:
    __doc__ = "Operator history and answering on the configured application Book. Host must explicitly authorize the receiving operator; requests contain no credentials, authority claims or provider paths. Authorization callbacks are trusted service configuration and may use the rights service. Native Forget remains explicit provider integration and retains admission tombstones."
    def ListQuestions(self, cursor: "str", limit: "int") -> "OperatorPage":
        raise NotImplementedError
    def AnswerQuestion(self, id: "str", option: "str") -> "OperatorDecision":
        raise NotImplementedError


class QuestionOperatorClient(QuestionOperator):
    def __init__(self, transport):
        self._transport = transport

    def ListQuestions(self, cursor: "str", limit: "int") -> "OperatorPage":
        _service_check("string", cursor)
        _service_check("i64", limit)
        _oa_args = OAQuestionOperatorListQuestionsArguments()
        _oa_args.cursor = cursor
        _oa_args.limit = limit
        _oa_arguments = _service_encode(enc_oaquestionoperatorlistquestionsarguments, _oa_args, 1)
        _service_decode(_decode_oaquestionoperatorlistquestionsarguments, _oa_arguments, 1)
        _oa_request = _service_request("abstraction.asks/operator@1", "ListQuestions", _oa_arguments)
        _oa_payload = _service_response(self._transport.exchange_frame(_oa_request), "abstraction.asks/operator@1", "ListQuestions")
        _oa_result = _service_decode(_decode_oaquestionoperatorlistquestionsresult, _oa_payload, 1)
        return _oa_result.value

    def AnswerQuestion(self, id: "str", option: "str") -> "OperatorDecision":
        _service_check("string", id)
        _service_check("string", option)
        _oa_args = OAQuestionOperatorAnswerQuestionArguments()
        _oa_args.id = id
        _oa_args.option = option
        _oa_arguments = _service_encode(enc_oaquestionoperatoranswerquestionarguments, _oa_args, 1)
        _service_decode(_decode_oaquestionoperatoranswerquestionarguments, _oa_arguments, 1)
        _oa_request = _service_request("abstraction.asks/operator@1", "AnswerQuestion", _oa_arguments)
        _oa_payload = _service_response(self._transport.exchange_frame(_oa_request), "abstraction.asks/operator@1", "AnswerQuestion")
        _oa_result = _service_decode(_decode_oaquestionoperatoranswerquestionresult, _oa_payload, 1)
        return _oa_result.value
